### ISSUE TITLE
java.lang.NullPointerException at io.netty.handler.codec.MessageToMessageEncoder

### ISSUE THREAD

**Issue by cauliflower69** [McJty/TheOneProbe#1]
I was holding the wand looking at a pig. I did not get a crash report so I have uploaded the client log

https://mega.nz/#!0ZU0UIAb!JLbafciKXLS0im_twX46L8zoeqP4oaleuIS-dr0Sw5k

**Comment by McJty** [comment]
Could you upload that to a more normal pastebin like bpaste.com or pastebin.com?

**Comment by cauliflower69** [comment]
Nope its 7.5mb

**Comment by McJty** [comment]
Well I cannot do anything with the link above as I'm on linux and it wants me to download a windows executable.

**Comment by cauliflower69** [comment]
Do you not see download through browser?

http://imgur.com/19O86YQ

**Comment by McJty** [comment]
Ok, that works. Will check it out soon

**Comment by cauliflower69** [comment]
Thanks

**Comment by McJty** [comment]
Fixed in upcoming release
