### ISSUE TITLE
AppleSkin and TheOneProbe conflicts

### ISSUE THREAD

**Issue by Drakma** [McJty/TheOneProbe#101]
Food items do not display their tooltips when TOP is installed.

**Comment by rcooknet** [comment]
Noticed the same issue while playing the WyldLife (v 1.2.3) pack on Curse.

![screen shot 2016-11-28 at 5 39 04 pm](https://cloud.githubusercontent.com/assets/1759382/20690679/9993385c-b591-11e6-88e9-b9a86111995d.png)

**Comment by McJty** [comment]
That cannot have anything to do with TOP directly as TOP does not do anything with item tooltips. Only with tooltips in the world. If this happens then that's caused by whatever that other mod does. Maybe it thinks that it does not have to show that if TOP is installed or something.
