### ISSUE TITLE
TOP 1.10.2 with AE2 integration

### ISSUE THREAD

**Issue by notacompletemoron** [McJty/TheOneProbe#107]
So, I just saw the update to 1.11 with AE2 integration, however, I'm running like 130 mods altogether.

Can we get an update for the 1.10.2 version to have AE2 integration?

Thank you.

**Comment by McJty** [comment]
I did not do that AE2 integration. That's part of AE2 itself. So you'll have to ask them to do it in their 1.10 version as well

**Comment by notacompletemoron** [comment]
Well, we're no longer working on 1.10.2.
