### ISSUE TITLE
Not pulling block names from resource pack

### ISSUE THREAD

**Issue by darkphan** [McJty/TheOneProbe#109]
It appears that The One Probe is not pulling the names of items you are looking at from the language file of the loaded resource packs.

**Comment by McJty** [comment]
More info please. What version? What block are you looking at exactly? Screenshot perhaps?

**Comment by darkphan** [comment]
Version 1.3.3 of The One Probe. What I am looking at are blocks from the WTF Expedition Mod, which uses a resource pack for some of the textures/overlays. One thing that is interesting is that in single player it is fine, but does not display the name correctly on multiplayer, see this screenshot: 

[Screenshot](http://puu.sh/t4npW/e29bf7b2cd.png)

I also installed TUMAT which does something similar to TOP to see if it was an issue with WTF Expedition or TOP.

**Comment by McJty** [comment]
Um that's weird... The only thing I can think of is that WTF is doing something weird but no idea what atm

**Comment by McJty** [comment]
Probably fixed in 1.4
