### ISSUE TITLE
Problem with nightvision

### ISSUE THREAD

**Issue by MrRiegel** [McJty/TheOneProbe#11]
the screen becomes light blue

![topgood](https://cloud.githubusercontent.com/assets/13290261/15831666/fbe6331c-2c1e-11e6-86a2-11178f0030c2.png)

![topbad](https://cloud.githubusercontent.com/assets/13290261/15831667/ffb54596-2c1e-11e6-9fca-b547ec94c7ab.png)

the minecraft screenshot (F2) didn't show the blue

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Should be fixed next release
