### ISSUE TITLE
Custom Probe Item

### ISSUE THREAD

**Issue by Voidi** [McJty/TheOneProbe#112]
1. Whats the correct way to make my own Probe Item? Is it sufficient to have an item with [this](https://github.com/McJty/TheOneProbe/blob/1.10/src/main/java/mcjty/theoneprobe/items/ModItems.java#L36) NBTtag?

2. Consider using the [API Annotation](https://github.com/MinecraftForge/MinecraftForge/blob/1.11.x/src/main/java/net/minecraftforge/fml/common/API.java) and tell addon/compat developers to check against the API-ID. So (addons/mods with compatibility) would independent of the actual TheOneProbe implementation.

**Comment by McJty** [comment]
1. yes

2. I'm not a fan of annotations. TheOneProbe api already allows you to be independent of TheOneProbe and still supporting it. All my mods support TheOneProbe but work just fine without it as well

**Comment by Voidi** [comment]
Thanks!
