### ISSUE TITLE
Client crash when looking at TConstruct Smelting Controller

### ISSUE THREAD

**Issue by kostanakis** [McJty/TheOneProbe#116]
http://pastebin.com/ZBkSpt2c, reproduced on certain PC under Windows 10, but can't be reproduced on Linux. Clients are identical,afaik.

**Comment by McJty** [comment]
More information please. Full log, versions of all the relevant mods, version of MC, and so on...

**Comment by kostanakis** [comment]
Troubles was caused by TOPAddons, not TOP.
