### ISSUE TITLE
Bauble broken in 1.4.0

### ISSUE THREAD

**Issue by xannor** [McJty/TheOneProbe#117]
Just updated 1.10.2 to TOP 1.4.0, I have been using the bauble version of TOP and when I logged in it was not working and when I attempted to remove it from my bauble slot the client crashed with the following:

https://gist.github.com/xannor/2ebb88d5cf3832bd2574020088ede254

**Comment by McJty** [comment]
I'll check it out

**Comment by gdude2002** [comment]
I can confirm this issue; we're having the same problem.

**Comment by McJty** [comment]
Fixed in upcoming 1.4.1 release
