### ISSUE TITLE
[1.10.2][1.4.0] Harvest tool level displays incorrectly

### ISSUE THREAD

**Issue by codetaylor** [McJty/TheOneProbe#118]
Thanks for this awesome mod! Love it!

When I set `this.setHarvestLevel("shovel", 0);`, implicating that the player must use a wooden shovel to harvest the block, TOP displays "(stone)" instead. When changing to `this.setHarvestLevel("shovel", 1);`, it should read stone, yet it reads as iron.

I believe adding `"wood"` to the array [here](https://github.com/McJty/TheOneProbe/blob/1.10/src/main/java/mcjty/theoneprobe/apiimpl/providers/HarvestInfoTools.java#L24) would do the trick.

**Comment by McJty** [comment]
TOP displays what you can harvest. i.e. with a wooden shovel you can harvest stone. That's why it says stone
