### ISSUE TITLE
1.9.4 1.0.5 not showing rf per tick for deep ressonance crystals

### ISSUE THREAD

**Issue by keramond** [McJty/TheOneProbe#12]
it just shows 0 rf/t

**Comment by McJty** [comment]
I cannot reproduce this. What version of Deep Resonance? Also can you give a screenshot?

**Comment by keramond** [comment]
deep ressonance  1.9.4 1.14beta32

![2016-06-07_15 15 38](https://cloud.githubusercontent.com/assets/7138192/15858881/fbbfbc88-2cc2-11e6-99ea-d433b8f4d7b1.png)

**Comment by McJty** [comment]
Fixed next release of Deep Resonance (actually a bug in DR and not in TOP)
