### ISSUE TITLE
Adding/removing energy efficiency upgrades to Mekanism machines causes power-fill bar to extend past TOP

### ISSUE THREAD

**Issue by JaSpr** [McJty/TheOneProbe#121]
A story in pictures: http://imgur.com/a/VTd7t

TOP seems to rely on the efficiency multiplier incorrectly. Each time an efficiency upgrade is removed from the machine, TOP appears to properly adjust the "total available" energy that the machine can hold, but doesn't update the total actual energy that the item is holding.

The energy bar can thus extend all the way across the screen.

**Comment by McJty** [comment]
Does it restore if you exit the GUI?

**Comment by McJty** [comment]
In any case, this is most likely a bug in Mekanism itself. TOP simply reports the numbers as the mod gives them. It is not aware of multipliers and things like that. It simply uses the CoFH API

**Comment by JaSpr** [comment]
Not when you exit, no.  It does restore eventually somehow (It won't last forever) but I've never been paying attention to see when it restores.

**Comment by tomelfring** [comment]
I can confirm it's an issue of Mekanism. On removal of upgrades it only recalculates the new maxEnergy, and allowing the current stored energy to be larger than the max energy stored.
Not an TOP issue.

**Comment by JaSpr** [comment]
We may want to re-assess this issue, as Mekanism's implementation might be intentional.  The actual energy stored in the mekanism device CAN BE above it's (current) maxEnergy, if the machine was charged up while the maxEnergy was temporarily higher than its default maxEnergy.

NOTE:  I can't think of any case where we would WANT the charge progress bar to extend past the bounds of the bar graph, and it shouldn't be too difficult to allow the bar graph to continue to show the (artificially high) current energy value in the text, while still cropping the bar graph at the current max.

**Comment by JaSpr** [comment]
https://github.com/aidancbrady/Mekanism/issues/4172

**Comment by JaSpr** [comment]
That being said, we can't always rely on the developers of other mods to enforce that "getEnergyStored" will always return a value equal or less than "getMaxEnergyStored", so we should probably run a Math.min on both values anyway, so that this issue doesn't come up with other mods.

**Comment by JaSpr** [comment]
#122
