### ISSUE TITLE
Information TechReborn not displayed in multiplayer

### ISSUE THREAD

**Issue by Umiyaki** [McJty/TheOneProbe#124]
Minecraft 1.11.2
Forge 13.20.0.2226
theoneprobe-1.1x-1.4.1.jar (installed on the server and client)
TechReborn-1.11.2-2.1.3.54-universal.jar
RebornCore-1.11.2-2.13.3.34-universal.jar

compare pictures: (singl/multiplayer)
https://justpaste.it/1328k

**Comment by McJty** [comment]
Report to TechReborn please. That is their bug

**Comment by McJty** [comment]
Hint to them: they are most likely using client side code in their top handler. TOP handler is server side

**Comment by Umiyaki** [comment]
Ok,
Thanks
