### ISSUE TITLE
Crash on Look To Banana

### ISSUE THREAD

**Issue by ghost** [McJty/TheOneProbe#125]
My game has crashed when i look to banana on the tree (from Terraqueous mod).
[TOP crash mcjty.txt](https://github.com/McJty/TheOneProbe/files/748551/TOP.crash.mcjty.txt)

**Comment by McJty** [comment]
Thanks. I'll check it out soon. Chances are the bug are in the 'banana' mod (whatever that is) though

**Comment by ghost** [comment]
and aaah, i should add a note here; it didn't crash again when i look to that "banana leaves" and "banana flower" items. only i remember is i just looked to the banana tree, then bananas.

**Comment by tomelfring** [comment]
Are you sure it's an item from Biomes O' Plenty? As far as I know it doesn't add anything related to bananas. The only I know of (and is present in all the mods 2) is the one of Pam's HarvestCraft. And that one doesn't seem to cause crashes.

**Comment by ghost** [comment]
ahhh so sorry for that, it is from Terraqueous.  fixed the content.

**Comment by ghost** [comment]
actually this thing:
![banana](https://cloud.githubusercontent.com/assets/24831406/22567592/34a46d8a-e999-11e6-8714-cd56c807f763.PNG)

**Comment by McJty** [comment]
Can you still reproduce this? In any case, this doesn't look like a bug in TOP but in Terraqueous. The problem seems to be that a wrong item is returned from block.getPickBlock(). That's something they should fix on their side

**Comment by ghost** [comment]
hmmm... okay. and no, i couldn't make it happen again. thanks.

**Comment by ghost** [comment]
it happens again :/

**Comment by McJty** [comment]
Please report to Terraqueous
