### ISSUE TITLE
IC2 Machines have .name attached since 1.4.0

### ISSUE THREAD

**Issue by davqvist** [McJty/TheOneProbe#126]
Minecraft 1.10.2
Forge 12.18.3.2221
TOP starting from 1.4.0
IC2 2.6.142-ex110

Starting from The One Probe 1.4.0 IC2 machines have .name attached when you look at them, for example. "Generator.name". I tried it with TOP 1.3.3 and worked perfectly fine, that's why I'm reporting here and not in the IC2 bug tracker because your update seemed to have broken it. If I should also report in the IC2 bug tracker or need more information, let me know.

**Comment by McJty** [comment]
In IC2 top does localization on the client instead of the server. I find it weird that TOP would do this wrong only for IC2 and not for other mods

**Comment by davqvist** [comment]
I knew it was localization, but not sure why it broke for IC2. So you did change localization in 1.4.0? Can this be fixed? Or can I change some configs to fix it?

**Comment by McJty** [comment]
What changed is that in 1.3.3 localization was done server-side. But that's actually wrong since the server doesn't know the language that the player has on the client and also it wasn't working for 1.11 anymore.
So in 1.4.0 localization is done on the client instead. The server simply sends over the unlocalized name to the client which translates it.

**Comment by davqvist** [comment]
Okay makes sense. But how can this be fixed? I guess I should post on the IC2 bug tracker, maybe they know how they are handling translations differently and contact you. Or what do you propose?

**Comment by McJty** [comment]
I need input from the IC2 guys on this. Maybe they can explain what is going on here

**Comment by JaSpr** [comment]
Also happens for NON-machines

[screenshot](http://i.imgur.com/vXoiVPk.jpg)

modpack All the mods 1.10.2
IC2 version 2.6.142-ex110
TOP version 1.1x-1.4.1

**Comment by McJty** [comment]
This is actually a bug in IC2. It seems to be returning localized names (instead of unlocalized) in Item.getUnlocalizedNameInefficiently() which is not the intention. I can work around this in TOP (which I will do) but this will have to be addressed in IC2 as well.

**Comment by davqvist** [comment]
Thanks for investigating. Did you talk to the IC2 guys or should I report on their bug tracker?

**Comment by McJty** [comment]
Would be nice if you could do it. Thanks
