### ISSUE TITLE
Reports ActuallyAdditions crops as their Seed versions (with seed images) instead of the plant version.

### ISSUE THREAD

**Issue by JaSpr** [McJty/TheOneProbe#128]
Running "All The Mods" for 1.10.2.

http://i.imgur.com/lTqEAEb.jpg

Strangely (as the screenshot shows) WAILA gets it right, and WAILA is usually the one that's wrong.

**Comment by JaSpr** [comment]
https://github.com/Ellpeck/ActuallyAdditions/issues/620

**Comment by Ellpeck** [comment]
This can be closed as it's the intended behavior.

**Comment by JaSpr** [comment]
Why would this be the intended behavior?
