### ISSUE TITLE
Shows lang key as name for multiple items from Pam's Harvest Craft

### ISSUE THREAD

**Issue by JaSpr** [McJty/TheOneProbe#130]
Shows Avocado as `tile.pamAvocado.name`.
Shows Maple Wood as `tile.pamMaple.name`'

JEI and WAILA have the correct names.

[Avocado](http://i.imgur.com/36bL101.jpg)
[Maple](http://i.imgur.com/af928CI.jpg)

TOP 1.1x-1.4.1
Pam's 1.9.4-1.10.2g

**Comment by McJty** [comment]
This is actually a bug in Pam's Harvestcraft but next version of TOP will most likely work around it anyway
