### ISSUE TITLE
Incorrect harvest tool.  Certain vanilla and mod stones list "no tool" when the tools should be pickaxe.

### ISSUE THREAD

**Issue by JaSpr** [McJty/TheOneProbe#133]
Tested and confirmed that the stone has to be harvested with a pickaxe.  TOP does state that using OTHER tools won't work (shows X), just has the wrong NAME for the required tool.

TOP 1.1x-1.4.1
Abyssal 1.10.2-1.9.3.10

[With pickaxe](http://i.imgur.com/7nB66m6.png) / [Without pickaxe](http://i.imgur.com/kqcRdR8.png)

**Comment by McJty** [comment]
then AbyssalCraft is doing something wrong and WAILA is correcting that (but I'm not as forgiving :-)

**Comment by JaSpr** [comment]
It's actually the WAILA Harvestability mod that is getting right. This modpack uses the unmaintained version of WAILA, so I'd be surprised if it had that right on its own.  I can take a look at this later in the week.

**Comment by JaSpr** [comment]
So Waila Harvestability does go an extra step if block.getHarvestTool(blockState) comes up empty... [source](https://github.com/squeek502/WailaHarvestability/blob/1.10.x/java/squeek/wailaharvestability/helpers/BlockHelper.java)

Using an enum of wooden tools, it compares each tool's getStrVsBlock to the tool material's getEfficiencyOnProperMaterial, and if it finds a match, it sets that as the required tool type (e.g. pickaxe for Abyssal's Darkstone)

It looks rather simple to implement, but I wanted to hear your thoughts.

**Comment by JaSpr** [comment]
Unfortunately, confirmed an issue with TOP:  Vanilla End stone has the exact same results:

http://i.imgur.com/tA8TUmS.png
http://i.imgur.com/eglBHQd.png

**Comment by JaSpr** [comment]
@McJty any thoughts on this?  I can implement the fix the way WAILA harvestability has, but wanted to get your thoughts first.

**Comment by McJty** [comment]
Haven't had a chance to look at it but feel free to try it

**Comment by JaSpr** [comment]
Linking #139

**Comment by JaSpr** [comment]
Fixed by pr #139 (merged).
