### ISSUE TITLE
Suggestion: Toggle Entity/Mob info

### ISSUE THREAD

**Issue by SirSwerving** [McJty/TheOneProbe#136]
The ability to toggle the info boxes of entity data would be nice, Especially when you got a unit plate mod such as Neat displaying their information already.

**Comment by Cerugon** [comment]
Or when you got Minecraft comes alive (MCA) installed. Causes extreme lag if looking at one of the villagers while both MCA and The one Probe present,

**Comment by MCJediYoda** [comment]
I was also looking for this ability.  I would like the option to completely disable showing the mob information.

**Comment by McJty** [comment]
Is the client-side config renderBlacklist not sufficient for this?

**Comment by McJty** [comment]
Implemented with this config:

- New 'blacklistEntities' config (common type). This is a list of entities that will be blacklisted from showing the TOP tooltip. You can specify an entire mod here as well and you can also specify '*' for all entities. Server side this will prevent sending over the needed information for the entity. Client side this will prevent showing the tooltip in the first place
