### ISSUE TITLE
RayTraceResult missing from pickBlock()

### ISSUE THREAD

**Issue by HenryLoenwind** [McJty/TheOneProbe#14]
DefaultProbeInfoProvider.showStandardBlockInfo(DefaultProbeInfoProvider.java:130) is calling pickBlock without a RayTraceResult leading to NPEs/missing information for blocks where that matters (e.g. micro blocks, slabs with different halves).

Test case: Paint 2 slabs with different blocks in Ender IO's Painter and place them into the same block.

![image](https://cloud.githubusercontent.com/assets/1485873/15983703/011b4ea4-2fb1-11e6-8c90-1f4abe77cdec.png)

![image](https://cloud.githubusercontent.com/assets/1485873/15983709/148440b8-2fb1-11e6-8129-af66ad0122c3.png)

**Comment by McJty** [comment]
I will fix this

**Comment by McJty** [comment]
Should be fixed in theoneprobe-1.9.4-1.0.6-18.jar

**Comment by HenryLoenwind** [comment]
thx
