### ISSUE TITLE
[1.10.2] NoSuchMethodError when looking at a block

### ISSUE THREAD

**Issue by XFactHD** [McJty/TheOneProbe#140]
After updating to th latest version of TheOneProbe for 1.10.2 I crashed as soon as I looked at a block close enough to be inspected by TheOneProbe.
Crash: http://pastebin.com/NdPRWY58
If you need any more details I will try my best to provide them.

EDIT: I just restarted the game and now it shows the block icon, then "ERROR: theoneprobe:default" and below that, if applicable, the block specific integration like "Infused: 0%" when looking at a RFTools machine.

**Comment by XFactHD** [comment]
While displaying what I described in my edit above, the game seems to randomly crash with the crash from above.

**Comment by McJty** [comment]
I suspect another mod is bundling an outdated TOP API. If you could figure out which one that would be great

**Comment by XFactHD** [comment]
After taking a close look at the loaded APIs listed in the crash report, the only thing that kinda looks like it could be connected to this is this: mcjtylib_ng (2.3.9) from mcjtylib-1.1x-2.3.9.jar. When I am at home in the afternoon I will see if I can get some more info on this.

**Comment by McJty** [comment]
It is ok. We have found the mod that causes this:
https://github.com/MikeLydeamore/ExNihiloAdscensio/issues/101

**Comment by XFactHD** [comment]
Great.
