### ISSUE TITLE
SERVER PROBLEMS WITH LATEST UPDATE

### ISSUE THREAD

**Issue by Arythflight** [McJty/TheOneProbe#142]

**Comment by Arythflight** [comment]
HARVEST LEVEL OUTOF BOUNDS?

**Comment by Arythflight** [comment]
(LESS THAN 0)

**Comment by Arythflight** [comment]
I thought someone would like to know.. its making my server run high on the memory usage

**Comment by Arythflight** [comment]
21.02 00:45:24 [Server] Server thread/INFO [theoneprobe]: HarvestLevel out of bounds (less than 0). Found -1

**Comment by McJty** [comment]
You know you can edit comments?

**Comment by Arythflight** [comment]
oh yea, it says this non stop by the way my server console is non stop with that same message

**Comment by Arythflight** [comment]
no I'm sorry I didn't this my first time on here

**Comment by Arythflight** [comment]
I just figured you might want to know. so far everything is fine on the server other than that message going crazy and the memory higher than ussuall

**Comment by McJty** [comment]
Will fix this soon

**Comment by Arythflight** [comment]
right on no worries thank you and your mods are AWESOME I don't play modded without them

**Comment by DeadSix27** [comment]
Just to make sure and make it easier for other visitors to realize.
@Arythflight Is talking about the spam in the server console with:

`[11:24:03] [Server thread/INFO] [theoneprobe]: HarvestLevel out of bounds (less than 0).`

Which I thought is a incompatibly with SilentGems and similar. (Not tested)

But @McJty you know what this server message is about and will fix it right? Then its all good.

**Comment by McJty** [comment]
Fixed in the upcoming next version

**Comment by JaSpr** [comment]
Sorry should not have left that output message in there.
