### ISSUE TITLE
API: Allow overriding which block TOP displays

### ISSUE THREAD

**Issue by shadowfacts** [McJty/TheOneProbe#143]
In my mod, Facade Everything, there's a Facade block which has a base block and a facade block for each side. I'd like to be able to modify which block TOP shows based on the side hit using the API, and as far as I can tell, this isn't currently possible.

Here's an example of what I want to do, but with Waila: https://twitter.com/ShadowfactsDev/status/834142899637993472

As you can see, the block that Waila displays changes depending on which side of the Facade block the player's looking at.

**Comment by McJty** [comment]
The latest version of TOP actually has a very new API for this:

https://github.com/McJty/TheOneProbe/blob/1.11/src/main/java/mcjty/theoneprobe/api/IBlockDisplayOverride.java

With that you should be able to do this as the side at which you are looking at the block is given in the 'data' parameter. Let me know if that is sufficient for you

**Comment by shadowfacts** [comment]
Ah, I didn't see that. I'll try to use that later.

**Comment by shadowfacts** [comment]
That worked perfectly, thanks!
