### ISSUE TITLE
java.lang.NoSuchMethodError: net.minecraft.potion.Potion.func_188410_a(Lnet/minecraft/potion/PotionEffect;F)Ljava/lang/String;

### ISSUE THREAD

**Issue by johnfriedrich** [McJty/TheOneProbe#149]
No idea when this happens, but just saw it in log.
https://pastebin.com/cPP1vwju
Seems like theOneProb tries to useoutdated potion effects. (because built with old forge?)

Using mc 1.10.2
Forge 2254
Theoneprobe 1.4.4

After this error, the players gets a kick.

**Comment by McJty** [comment]
That's very weird . This function exists on 1.10.2 too

**Comment by Chocohead** [comment]
It is marked with `@SideOnly(Side.CLIENT)` though, so if it was being called on the server it would error with that.

**Comment by McJty** [comment]
Good catch. I'll fix it

**Comment by McJty** [comment]
Fixed next release
