### ISSUE TITLE
Forced client disconnect when looking at particular items after server restart

### ISSUE THREAD

**Issue by JaSpr** [McJty/TheOneProbe#153]
Our server was restarted, then multiple users started getting repeatedly disconnected with the message "A fatal error has occurred. This connection has been terminated".  After viewing the crash log (below) I was able to determine that turning off TOP resolved the issue.  The item that was crashing me was my Thermal Expansion Steam Dynamo.  A couple other people had an issue with the Tinkers' Construct Smeltery Controller.  

Breaking and replacing the block DID NOT resolve the issue. Setting TOP's isVisible flag to False resolved the issue.  (Turning it back on caused the disconnections again).

A full server restart resolved the issue entirely.

TOP 1.1x-1.4.4
FTB Beyond 1.2.1-1.10.2
Forge 12.18.3.2254
OptiFine = NO!

[Client log](https://gist.github.com/JaSpr/6e5fef12243d6f7767dabd43dfe7307e)

**Comment by McJty** [comment]
Did you report this to the CoFH team as well? It could be on their side too

**Comment by JaSpr** [comment]
I did not, but that's because it was happening by looking at items from various mods. Two different people confirmed that their Tinkers' smelteries were crashing them.

Additionally, we did confirm that anybody looking at one of the broken items would get disconnected.  I had a mod look at my dynamo and immediately get kicked just as I had when I looked at it.

The only constant was that disabling TOP resolved the issue for each user until the server was restarted, then the issue was resolved entirely.

**Comment by McJty** [comment]
Did you by chance remove rftools dimensions on the server?

**Comment by JaSpr** [comment]
YES! How did you know that?!

**Comment by McJty** [comment]
Because some of your clients may not have removed that mod. If so that causes these kinds of problems. Always remove mods on both sides (server *and* client)

**Comment by McJty** [comment]
Better is to keep dimensions and restrict nr of dimensions to 1 per player

**Comment by JaSpr** [comment]
Ok.  But how did you know it was THAT mod.  I mean, it was literally what he did before the problem started.  

Although in this case, it's an FTB Beyond server, and having additional requirements for players to join (other than just installing FTB Beyond) would cause additional barriers for entry.  The admin is saying it wouldn't really be an option to have anyone wanting to join (a non-whitelist server) to remove that mod first.  Many of the users might not even know how to accomplish that.

**Comment by McJty** [comment]
Yes but it is required that the mod is deleted on both sides. If that's a problem then go with the config solution.  Note that dimensions don't have to be bad for a server 

I know it will likely RFTools dimensions because server owners are often afraid of that mod

**Comment by McJty** [comment]
I assume this can be closed now?

**Comment by JaSpr** [comment]
Yes. Thanks for the feedback

**Comment by goreacraft** [comment]
McJty thank you for the feedback, but this seems a bit counter-intuitive for why clients have to crash though even with RFTools diabled, this seems like a bug that a simple try/catch could fix it.. is there a solution/plan to prevent this in the future?

**Comment by McJty** [comment]
Yes, make sure servers and clients have the same mods (except for client side mods of course). You risk instability and crashes if the mod list is not the same. That has nothing to do with any particular mod. That's just a general principle
