### ISSUE TITLE
Show Immersive Engineering Multiblock Machines Info

### ISSUE THREAD

**Issue by calloatti** [McJty/TheOneProbe#159]
I don't know if this is something IE should implement or you can do it from TOP.

IE multiblock machines don't display fluid information at all, unlike EnderIO machines that do:

Fine:

![image](https://cloud.githubusercontent.com/assets/12817862/25133164/3f02923e-2422-11e7-90ea-b43dc8b4792a.png)

No fluid info:

![image](https://cloud.githubusercontent.com/assets/12817862/25133180/4a210826-2422-11e7-99a9-50360f788d89.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25133230/71a28050-2422-11e7-9277-54e051c27663.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25133257/8311ab68-2422-11e7-9f40-43b5b95c3fc3.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25133270/8af1e4c4-2422-11e7-8818-46e9f9a1e567.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25133278/915dd55c-2422-11e7-8570-394b20e03d49.png)

Also, pickaxe can be used on IE multiblocks.

Minecraft 1.10.2
theoneprobe-1.1x-1.4.6
ImmersiveEngineering-0.10-57

**Comment by McJty** [comment]
That's on IE's side to implement
