### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by ghost** [McJty/TheOneProbe#162]
[crash-2017-05-02_16.21.45-client.txt](https://github.com/McJty/TheOneProbe/files/970567/crash-2017-05-02_16.21.45-client.txt)
it crashes when look to [homecraft mineware's](https://minecraft.curseforge.com/projects/homecraft-mineware?gameCategorySlug=mc-mods&projectID=256356) bed...
forge 2294

**Comment by McJty** [comment]
Problem in their mod. They are returning null for a block.getItem() and that's invalid in 1.11
