### ISSUE TITLE
[1.12] Crash when opening "Controls" Menu

### ISSUE THREAD

**Issue by level555** [McJty/TheOneProbe#171]
**Issue Description:**

Minecraft crashes when attemting to to open the Controls menu in minecrafts settings

**What happens:**

Game crashes
What you expected to happen:

Controls menu opens

**Steps to reproduce:**

    Create minecraft 1.12 instance with forge and TheOneProbe
    Launch minecraft
    Click "Options..."
    Click "Controls..."

Affected Versions:

    theoneprobe-1.2-1.4.7
    Minecraft: 1.12
    Forge: 14.21.0.2322

[crash-2017-06-13_22.32.20-client.txt](https://github.com/McJty/TheOneProbe/files/1072835/crash-2017-06-13_22.32.20-client.txt)

**Comment by McJty** [comment]
Why is this related to my mod? It doesn't crash in my mod. I think it is a bug in the current version of Forge

**Comment by level555** [comment]
It doesn't crash without this mod installed and there is atleast one mod that has an entry in the controls menu without crashing

**Comment by TheSaucyWelshman** [comment]
Fairly certain it was a Forge bug. I got the same crash with a few different mods. It's not happening anymore with Forge 14.21.0.2324

**Comment by level555** [comment]
Works finr with latest versions of the mod and forge
