### ISSUE TITLE
MC 1.11 TOP reporting harvest level one above what it is

### ISSUE THREAD

**Issue by sandalle** [McJty/TheOneProbe#174]
Similar to https://github.com/McJty/TheOneProbe/issues/118, I saw this and first thought it was another mod (see https://github.com/Rohzek/SimpleOreGeneration/issues/11 ), but the mining level is correct while The One Probe says it's one level higher.

e.g. Simple Ore Generation Copper Ore has a pickaxe harvest level of 2 "iron" (see https://github.com/Rohzek/SimpleOreGeneration/blob/master/1.11.2/main/java/com/gmail/rohzek/blocks/GenericBlock.java#L24 ), yet The One Probe reports "diamond" as the tool level needed to mine it. I believe this is what #118 was trying to say as well.

The issue only shows when I'm using a tool which does not match that harvest level, and then it shows that I need one harvest level above what I actually need (e.g. showing I need diamond when I really need iron).

Example: Simple Ore Generation Copper Ore (iron harvest level)
Stone Pickaxe
![simple ore generation copper ore - stone pickaxe](https://user-images.githubusercontent.com/2447608/27264648-c8a26b82-5437-11e7-9d9c-499255b6874d.png)

Iron Pickaxe
![simple ore generation copper ore - iron pickaxe](https://user-images.githubusercontent.com/2447608/27264637-ab3a60c2-5437-11e7-9a24-a8b6990c10cb.png)

Example: Thermal Foundation Copper Ore (stone harvest level)
Stone Pickaxe
![thermal foundation copper ore - stone pickaxe](https://user-images.githubusercontent.com/2447608/27264645-c441bb6a-5437-11e7-97dd-cb1f8cdc0d8f.png)

Iron Pickaxe
![thermal foundation copper ore - iron pickaxe](https://user-images.githubusercontent.com/2447608/27264638-ade6ee3a-5437-11e7-9505-dba2933dc9f5.png)

Forge: 1.11.2-13.20.0.2315
The One Probe: 1.1x-1.4.7
Modpack: [NST Unofficial - Exploration](https://minecraft.curseforge.com/projects/nst-unofficial-exploration)

**Comment by McJty** [comment]
The probe shows the harvest level of what the tool can harvest. i.e. when it says 'Pickaxe (diamond)' like in your first screenshot then that means you need a pickaxe that can mine diamond (i.e. an iron pickaxe)

**Comment by sandalle** [comment]
That makes sense, thank you @McJty for the explanation. :) I'm unsure why I was expecting TOP to tell me the material I need the pickaxe made out of (e.g. iron pickaxe to mine diamond), since that wouldn't be true for all modded tools. I was thinking this would be the mining level described, though (e.g. iron-level pickaxe to mine diamond), but again that may not be clear for other mod pickaxes/tools, so your method makes more sense now. :)
