### ISSUE TITLE
(in creative tabs) ALL Mods Have TOP Items

### ISSUE THREAD

**Issue by ghost** [McJty/TheOneProbe#175]
![1](https://user-images.githubusercontent.com/24831406/27352510-ab2c402c-5609-11e7-82a0-b625d897a492.PNG)
![2](https://user-images.githubusercontent.com/24831406/27352513-ab9e361e-5609-11e7-8477-54b20a86caf5.PNG)
![Uploading 3.PNG…]()
used forge 2337
TOP 1.4.8

**Comment by ghost** [comment]
and ah, i just noticed; it's not only TOP, a hammer from sparks hammers and some items from extreme reactors too.
hope it isn't a forge bug...

**Comment by tomelfring** [comment]
It's a change in 1.12 minecraft, each mod has to check for itself in which tabs stuff needs displaying. 
#169 and #173 for more info ;)

**Comment by ghost** [comment]
hmm so i should close this :D
