### ISSUE TITLE
[1.12] Max Stack Sizes are not Consistent

### ISSUE THREAD

**Issue by SnowShock35** [McJty/TheOneProbe#181]
Hi @McJty,

I believe I have found an issue with The One Probe in Minecraft 1.12, here's the details:

### Issue Information 

- Minecraft 1.12
- Minecraft Forge 14.21.1.2387
- The One Probe 1.4.11

### Issue Description

Max Stack Sizes are a bit random. By which only one of the items has a max stack size of 64 (All should be 1 IMO) 

### Issue Media

![](https://ss.blamesnow.co.uk/2017/06/1498736943-783a3c5b.png)

**Comment by McJty** [comment]
Fixed next release
