### ISSUE TITLE
[Question] Change Horse Owner

### ISSUE THREAD

**Issue by ExDomino** [McJty/TheOneProbe#182]
Hello, the One Probe indicates that a horse is mine when it's the horse of another player on my server. In fact, I tammed the horse but I gived it to him. How to change the horse's owner name indicated by The One Probe? Because it's no longer my horse. Thank in advance! Version of The One Probe: 1.4.11 on MC 1.12.

**Comment by McJty** [comment]
How did you give that horse to him? The One Probe shows who tamed the horse. That's the only information that is kept by the entity. So unless there is a way to change that information on a horse there is nothing I can do

**Comment by ExDomino** [comment]
I checked the NBT tags list for horses, there is no owner name listed.
https://www.digminecraft.com/data_tags/horse.php
How your mod know who have tamed the horse? Is it an hidden NBT tag? What is its name?

**Comment by McJty** [comment]
I call EntityHorse.getOwnerUniqueId(). Not sure where that is kept in the NBT though. I don't work with NBT here

**Comment by tomelfring** [comment]
http://minecraft.gamepedia.com/Horse under Data values does mention a OwnerUUID nbt tag.

**Comment by ExDomino** [comment]
We're seeking a way to change the name displayed on the horse with The One Probe. The horse of a friend is indicated that is mine. Is there a command EntityHorse.setOwnerUniqueId() ? If so, can you add a command like /horse_set_ownwer [name] where name should be a player connected and then transformed into its UUID. If name is not recognize, the command tells an error. Also, this command should not work for anyone except the horse owner itself, to prevent thieft. Or if you know another mod that can do that?

**Comment by tomelfring** [comment]
You can edit it with some commands, only allowing the server owner (or ops) to change the owner. 

(just writing this down, haven't tested the commend)
`/entitydata @e[type=horse, r=3] {OwnerUUID:new-owner-uuid-here}`
This does require you know the uuid of the new owner.

**Comment by ExDomino** [comment]
Ok, I will do that. I'm the server owner and I think I can retrieve UUID inside the whitelist.
But if you can make this command, this would be easier and player-accessible. Just only change one mod at the time (tell an error if there more than one in the radius) and only for its owner (tell another error if the mob if not owned by the command sender). The command would also retrieve the UUIDs. But I change the Horse Owner manualy this time. Thanks!

**Comment by josephcsible** [comment]
Horse ownership is a vanilla feature, and it isn't TOP's responsibility to let it be changed just because it exposes it.
