### ISSUE TITLE
[1.12] Crash when opening crafting table's recipe book

### ISSUE THREAD

**Issue by blu0191** [McJty/TheOneProbe#183]
The crash seems to be because of TOP, judging by the crashlog. I'm using 1.12-1.4.13 and heres the crash:

https://pastebin.com/eJfwiaPf

**Comment by McJty** [comment]
How did you ever come to that conclusion? It is crashing in CraftTweaker:

    at crafttweaker.mc1120.recipebook.RecipeBookCustomClient.func_193830_f(RecipeBookCustomClient.java:14)

**Comment by blu0191** [comment]
Oh, whoops, sorry
