### ISSUE TITLE
Packet Performance

### ISSUE THREAD

**Issue by Sir-Will** [McJty/TheOneProbe#184]
hey,
can the performance of this be improved?
![](http://i.imgur.com/EvsSIs4.jpg)
![](http://i.imgur.com/rq7WgrK.jpg)

**Comment by McJty** [comment]
That's really not bad at all. Basically 0.6%. Not sure there is much that can be done there. Suggestions always welcome

**Comment by Sir-Will** [comment]
All functions combined it is 4,4% which I feel like is a lot for this, the only other mod which higher then that right now is ender io.

**Comment by McJty** [comment]
What is this benchmarking exactly? Is this client or server?

**Comment by McJty** [comment]
Also what were you looking at when you did this?

**Comment by Sir-Will** [comment]
Server with 36 players.

**Comment by Sir-Will** [comment]
Changed I:timeout from 200 to 5000 but didn't change the performance it seems.
![](http://i.imgur.com/yPbJAK7.jpg)

**Comment by McJty** [comment]
I will see if there is something that I can do but still 4.4% is not *that* much really. But I'll investigate

**Comment by McJty** [comment]
You have to change that 200 to 5000 on the clients btw. Not the server. Because that's the client asking info to the server

**Comment by McJty** [comment]
I have found a way to optimize it a bit

**Comment by McJty** [comment]
Next version of The One Probe (1.4.14) should optimize this considerably.

**Comment by Sir-Will** [comment]
Thanks!

So the players could set it to 10 and cause even more performance issues?
Would be great if it is using the setting from the server and not the client when they are on a server.

**Comment by McJty** [comment]
yes they technically could. The problem is that this is initiated from the client and the client cannot know the value on the server so there really is no way to do this with a server setting. Anyway, the issue should be a lot better now at least
