### ISSUE TITLE
[1.10.2] Error in console with some Ex Nihilo Adscensio blocks

### ISSUE THREAD

**Issue by kaal-1** [McJty/TheOneProbe#185]
Minecraft 1.10.2 - Forge 2281
SpongeForge 1.10.2-2281-5.2.0-BETA-2464

https://hastebin.com/mipawebeqo.rb

**Comment by McJty** [comment]
That looks like a bug in ex nihilo. Report to them

**Comment by kaal-1** [comment]
Ok, thank you =)
