### ISSUE TITLE
Helmet + Probe not working

### ISSUE THREAD

**Issue by ghost** [McJty/TheOneProbe#186]
MC 1.12
TOP 1.4.15
Forge 2424

Using a probe on a helmet (only tested a diamond one) does not show the 'popup'. Using a probe in hand does.

**Comment by SoniEx2** [comment]
Forge issue. You can't add NBT to recipe outputs.

**Comment by McJty** [comment]
Well I thought I fixed it on my side anyway but apparently it is not working.  I will check it out when I am back from vacation

**Comment by McJty** [comment]
Fixed next release
