### ISSUE TITLE
[1.12]  LEAK: ByteBuf.release() was not called before it's garbage-collected

### ISSUE THREAD

**Issue by FiveEYZ** [McJty/TheOneProbe#187]
seems to be a memory leak

https://gist.github.com/FiveEYZ/c35435adc869c127a1ea3eadd2fac2d8

using:
theoneprobe-1.12-1.4.15
forge-1.12-14.21.1.2428-universal

**Comment by McJty** [comment]
When does this happen? What block were you looking at?

**Comment by FiveEYZ** [comment]
maybe any of this will help or maybe its all unrelated:
https://gist.github.com/FiveEYZ/2c213f124f9f0424f569480540d91df1

**Comment by FiveEYZ** [comment]
sorry i have been trying to test it, seems to only be shortly after someone logs in, and that person does not have to look anywhere (air)

**Comment by tomelfring** [comment]
Related to: https://github.com/MinecraftForge/MinecraftForge/issues/4282

**Comment by josephcsible** [comment]
I caught this too: https://gist.github.com/josephcsible/69d32639f2211f89188c563abc1b5631

**Comment by josephcsible** [comment]
Turns out that this is a Forge bug that was fixed back in 14.23.0.2538: MinecraftForge/MinecraftForge#4510
