### ISSUE TITLE
Azanor change API in Baubles

### ISSUE THREAD

**Issue by Rumaruka** [McJty/TheOneProbe#188]
Crashlog : https://pastebin.com/FLr25HjU
Minecraft 1.11.2

**Comment by josephcsible** [comment]
This looks like an issue with Botania and/or Baubles. Why do you think it's a TOP issue?

**Comment by Rumaruka** [comment]
First,  look crashlog 
Second,  Azanor make new build 
Third,  half years ago,  Carl 
Closed :)
