### ISSUE TITLE
Crashed When Look to Lantern of BiblioCraft (1.12)

### ISSUE THREAD

**Issue by ghost** [McJty/TheOneProbe#190]
[crash-2017-08-06_22.44.51-client.txt](https://github.com/McJty/TheOneProbe/files/1203379/crash-2017-08-06_22.44.51-client.txt)
@Nuchaz maybe wants to see, or need him help

**Comment by ghost** [comment]
uhm, need to tell that it happened only 1 time. u can close it if not necessary

**Comment by McJty** [comment]
In any case that would be a bug on their side
