### ISSUE TITLE
Reprint mod to MCBBS

### ISSUE THREAD

**Issue by P1nWheel0v0** [McJty/TheOneProbe#192]
McJty,

Hello, my name is P1nWheel.I really like your mod 'The One Probe'.It is a useful mod because I can know about the information of a block that shows on screen.There is a mod called Walia which is similar to this mod.TOP need tools while Walia not.But I think it is more funny and interesting!As I know, TOP supplies many mods. I hope I can reprint this mod on [MCBBS](http://www.mcbbs.net/portal.php) which is the largest Chinese Minecraft forum. Due to the barriers of language, most of the Chinese players don't know this mod even how to play.I know that TOP has translated to Simplified Chinese but still, not many players know this mod.Therefore I would like to introduce this mod to Chinese players so that they can enjoy this great mod. I will also submit the zh_TW.lang to your GitHub as I can do.

I will obey the rules below and your special request.

- I will **NOT**  take any credits of this mod and I will clearly state your official website(CurseForge, Minecraft forum, and GitHub)
- I will give the official download link and clearly note that 'This is the official download link, please click here first to support McJty.
- Due to the GFW （Great Firewall of China） and network speed, I probably prepare a mirror link for players to backup. The mirror will direct to an **Ad-free page** just like Dropbox. I would only prepare this mirror while the official download link is useless. 
- Last but not least, I would **NOT** use TOP  to earn any money/benefits, etc. I would also clearly state that everyone must not use this mod to earn any money/benefits, etc.

If you think the rules upsides is not enough, you can tell me.I really appreciate if you can give me permission to reprint.By the way, thank you for bringing this great mod to us.

Yours sincerely,
P1nWheel

**Comment by McJty** [comment]
You can put a link to be curse download page but not a separate download as then I would not get the curse reward points

**Comment by P1nWheel0v0** [comment]
Ok.Then I would not put a separate download link.

**Comment by smallxiaoxiaoB** [comment]
This player has not been updated for a long time. I want to continue to share with MCBBS on the basis of him. I will link to the author's plug-in page. I still hope to get your authorization.
