### ISSUE TITLE
1.4.16 Asks for 1.12.1

### ISSUE THREAD

**Issue by ghost** [McJty/TheOneProbe#194]
Latest version (1.4.16) asks for minecraft 1.12.1 when loaded in 1.12

**Comment by McJty** [comment]
I will fix this soon

**Comment by tomelfring** [comment]
Would be as easy as adding `acceptedMinecraftVersions = "[1.12,1.13)"` to the @ mod

**Comment by McJty** [comment]
Fixed in next release (waiting approval on curseforge)
