### ISSUE TITLE
1.12.1 Client crash while looking at a placed Bibliocraft clipboard

### ISSUE THREAD

**Issue by DingoX3** [McJty/TheOneProbe#200]
I have the baubles one probe on. I placed a clipboard on the side of a Extra Utilities 2 indexer. After placing it I crashed to desktop. I was able to log back into the smp server by moving my mouse while logging in to not look at the clipboard.

Full crash: https://pastebin.com/rTa17YLz

Modpack: Modern Skyblock 2 v2.4.4
MC: 1.12.1
TOP: 1.4.18
Bibliocraft: v2.4.3
Forge: 2484

**Comment by McJty** [comment]
Looks like a bug in BiblioCraft. Report to them as well

**Comment by tyler489** [comment]
https://github.com/Nuchaz/BiblioCraft/issues/510

**Comment by Xules01** [comment]
I'm having this issue as well.  When I get to close to the clipboard it crashes the game.  Posted on Oneprobe and Bibliocraft.

[crash-2018-05-03_19.36.25-client.txt](https://github.com/McJty/TheOneProbe/files/1973060/crash-2018-05-03_19.36.25-client.txt)

**Comment by LemADEC** [comment]
Issue was fixed on BiblioCraft side, so this one could be closed
