### ISSUE TITLE
Server Crash - MC-1.12.2 Forge 94 (Interaction with lootables mod) Debugging please leave open!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [McJty/TheOneProbe#201]
Crash Log
https://gist.github.com/P3rf3ctXZer0/d00c22035a9b27266dc37c66aefbe4b8

Full Log
https://gist.github.com/P3rf3ctXZer0/026e26c17d61391c96bdc29bf51fcc8f

**Comment by P3rf3ctXZer0** [comment]
https://github.com/MinecraftModDevelopmentMods/AdditionalLootTables/issues/9

**Comment by McJty** [comment]
That's a bug on their side. Wrong usage of the capability for players
