### ISSUE TITLE
[1.12.2] Strange crash maybe related to TOP

### ISSUE THREAD

**Issue by digi-tal-it** [McJty/TheOneProbe#204]
I experience client crashes while playing on my 1.12.2 server.

The client disconnects but doesn't close. I have found this in the logfile:

https://pastebin.com/ugcjZjRq

mc 1.12.2
TOP 2.4.18
Forge 14.23.0.2512

**Comment by McJty** [comment]
Looks like an issue in the TOPAddons mod. Report to them

**Comment by digi-tal-it** [comment]
I will do, thanks for looking into it!

**Comment by DrManganese** [comment]
This was fixed in TOPAddons.
