### ISSUE TITLE
High internet usage

### ISSUE THREAD

**Issue by SnowyCoder** [McJty/TheOneProbe#212]
This mod causes high internet usage and sometimes even saturates the client upload.
When tested with TickProfiler this mod uses even 3Mb per player (with 10'000 packet count)
Tested with infinity lite (1.10.2)

**Comment by McJty** [comment]
Infinity uses an old version. This network issue has been resolved since then

**Comment by SnowyCoder** [comment]
yep, didn't check.
sorry for the trouble
