### ISSUE TITLE
Doesn't show drawer contents for non Oak wood drawers

### ISSUE THREAD

**Issue by scottcher** [McJty/TheOneProbe#218]
Looks like the One Probe shows me a grid of icons and quantities when I'm looking at an Oak Storage Drawer but when i'm looking at another non-vanilla wood-type drawer (Lime, for example) I don't see those item icons or the quantities.
![2017-12-24_02 12 52](https://user-images.githubusercontent.com/1816300/34324911-045f4968-e850-11e7-820a-0c55c15a8dec.png)
![2017-12-24_02 12 56](https://user-images.githubusercontent.com/1816300/34324912-04678b6e-e850-11e7-9e26-8913c8b8b15b.png)

**Comment by McJty** [comment]
Hmm aren't you looking at an empty barrel? Can't really see clearly

**Comment by scottcher** [comment]
No but I'll include a better picture. This may be something with non oak drawers anyway because I can't use lime drawers in some recipes either. For example, I can't make compacting drawer with lime drawer as part of the recipe. Does that mean it's an ore dictionary issue with storage drawers?

**Comment by scottcher** [comment]
McJty - here's a better set of pictures.  Also I'm running Direwolf20 1.12 v1.3 - should have provided that information earlier.
![2017-12-24_13 30 38](https://user-images.githubusercontent.com/1816300/34328536-0ae4cb64-e8af-11e7-9edd-62faa2a1059d.png)
![2017-12-24_13 30 45](https://user-images.githubusercontent.com/1816300/34328537-0aecf7f8-e8af-11e7-8b74-5e26a3a9eda4.png)

**Comment by DrManganese** [comment]
The *showContentsWithoutSneaking* list only includes `storagedrawers:basicDrawers` by default, add `storagedrawersextra:extra_drawers` if you want it to show that info on *non-vanilla* drawers.

**Comment by josephcsible** [comment]
@DrManganese Good find. As of the next release, that will be there by default.
