### ISSUE TITLE
Crash - Divide by Zero

### ISSUE THREAD

**Issue by Mohron** [McJty/TheOneProbe#22]
Version: theoneprobe-1.9.4-1.0.11.jar
Crashlog: http://pastebin.com/LJ8NHnBU

**Comment by McJty** [comment]
i need more information. When are you getting that? What blook are you looking at?

**Comment by Mohron** [comment]
A Furnus. It's running and i'm looking right at it so every time I log in.

Version: Furnus-1.9.4-1.81.jar

https://github.com/MrRiegel/Furnus/issues/10

**Comment by McJty** [comment]
Will be fixed next release
