### ISSUE TITLE
Error with newest version of integrated dynamics

### ISSUE THREAD

**Issue by digi-tal-it** [McJty/TheOneProbe#228]
Today I updated the version of integrated dynamics and get this weird display anywhere I look:

https://imgur.com/SmJre7F

MC: 1.12.2
Forge: 14.23.1.2601
TOP: 1.4.19
Integrated Dynamics: 0.11.0

I will post this to the integrated dynamics dev, too.

**Comment by DasBrain** [comment]
See also https://github.com/CyclopsMC/IntegratedDynamics/issues/522.

**Comment by josephcsible** [comment]
Fixed by CyclopsMC/IntegratedDynamics-Compat@b6dc191

**Comment by DrGonzo94** [comment]
Seems to be fixed in latest version of Integrated Dynamics.
