### ISSUE TITLE
Mod incompatibility- Millenaire - When you look at villagers, they disappear.

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/TheOneProbe#229]
https://gyazo.com/11a8c22b2d9007971cc46f39957624f8

https://minecraft.curseforge.com/projects/millenaire

**Comment by McJty** [comment]
Please report it to them. That's most likely a bug on their side

**Comment by Kinniken** [comment]
Only happens with your mod though. Apparently even Wawla + Hwyla does not cause it, though I haven't check that.

What kind of interactions to you so with entities the player is seeing?

**Comment by josephcsible** [comment]
@Kinniken Where's the source for the 1.12.2 version of Millenaire?

**Comment by McJty** [comment]
When looking at an entity with TOP it will first call entity.serializeNBT() on the server side (TOP runs server-side in contrast with WAWLA and others). This data is sent to the client and on the client I call:

                entity = EntityList.createEntityFromNBT(entityNBT, Minecraft.getMinecraft().world);

To render that entity in the tooltip

**Comment by ProsperCraft** [comment]
@josephcsible 1.12.2 port is closed source.

**Comment by josephcsible** [comment]
Wow, that's quite disappointing. (It always rubs me the wrong way when someone makes a closed-source fork of an open-source mod.) Anyway, that means there's no practical way for us to try to troubleshoot this, so either open the source, fix it on your end, or figure out the problem on our end yourself and send us a PR.

**Comment by ProsperCraft** [comment]
Its confusing, but the original author of his closed source mod, is making a closed source update to his mod.

**Comment by josephcsible** [comment]
What's https://github.com/Millenaire/Millenaire of then? And while that may be true, it doesn't change the fact that it still prevents us from attempting to fix this.

**Comment by Kinniken** [comment]
I'll give you access to the 1.12 repo on GitLab if you want, no problem with that.

And yes, the fork is the open source one, and it's actually a rewrite in its early stage, very different from the current mod.

In any cases I'll try and test what you are doing with serializeNBT and see if I can reproduce the issue myself. Otherwise, is there any simple way of disabling your extra informations for a specific entity?

**Comment by ArcaneFlash** [comment]
Joseph. Millenaire is in parallel development. The original author is porting it to 1.12.2, while another dev team is rewriting Millenaire for 1.8.9... the closed source on github.

**Comment by josephcsible** [comment]
> I'll give you access to the 1.12 repo on GitLab if you want, no problem with that.

Yes, this would be nice to help get this fixed.

**Comment by Kinniken** [comment]
Same login on GitLab?

**Comment by josephcsible** [comment]
Yes.

**Comment by Kinniken** [comment]
Done. The class in question is MillVillager.

**Comment by Kinniken** [comment]
Thinking about it some more, just an idea: I keep track of the villager entities both client side as server side to make sure there's always one entity for each villager, respawning them if Minecraft despawn them etc. It's possible that your code, by recreating the entity client-side, causes my code to remove the original one. Just a thought, needs testing.

**Comment by Kinniken** [comment]
![capture d ecran 2018-02-25 a 10 42 50](https://user-images.githubusercontent.com/1891007/36640051-b23679b8-1a18-11e8-89ec-958d7572c46f.png)

My hunch was correct. Your preview entity is created just like a normal one, and that triggers my anti-duplication code.

The easier fix would be on my side, if I could detect the entity is being spawned by your code I could avoid entering it in my tracking system. What's the easiest way to do that? Anything standard for other mods to use? Thanks.

**Comment by Kinniken** [comment]
Got a workaround working, with this method to detect when the call is from OP:

`	/**
	 * Ugly hacky method to protect villagers from the One Probe mode, that
	 * re-instantiate villagers client-side for its rendering, triggering
	 * Millénaire's anti-villager duplication safeguard.
	 * 
	 * This will check whether this call is from One Probe, and if it is, mark
	 * that the entity is "virtual" and should not be registered with Millénaire.
	 */
	private void checkForOneProbe() {
		/**
		 * For now, no better way of doing this than checking the stack trace.
		 * This is a) dirty and b) relatively slow
		 * TODO find a better way to detect One Probe calls
		 */
		String stackTrace = Arrays.toString(new Throwable().getStackTrace());
		
		if (stackTrace.contains("theoneprobe")) {
			oneProbeVillagerCall  = true;
		} else {
			oneProbeVillagerCall = false;
		}
	}`

I hope there is a cleaner way to achieve this :P

**Comment by josephcsible** [comment]
Why not just do your check when the entity is added to the world instead of when it's read in from NBT?

**Comment by Kinniken** [comment]
Could do that I guess. I'd have to be careful of side-effects though.

**Comment by josephcsible** [comment]
@Kinniken Any update on this? Which approach did you end up releasing? Anything else we need to do?

**Comment by Kinniken** [comment]
Hi, for now I've left the stack trace system, which is really not ideal but works fine. You can try it out: http://millenaire.org/forum/viewtopic.php?f=5&t=1306

I looked at moving my code to the entity joining the world event, but it seemed risky, the kind of stuff that can have unintended side effects.

And no, nothing to be done on your side :)
