### ISSUE TITLE
Crash OutOfBounds Mekanism Energy Cube

### ISSUE THREAD

**Issue by Mohron** [McJty/TheOneProbe#230]
theoneprobe-1.12-1.4.20

https://gist.github.com/Mohron/65edb153226a151aa2d02224c94fa343

Looked at a Basic Mekanism Energy Cube to cause the crash.

**Comment by josephcsible** [comment]
Will be fixed in the next release. In the meantime, you can work around this by editing `theoneprobe.cfg` and changing `rfFormat` to any of the choices except for `1` (compact).
