### ISSUE TITLE
Crashing when looking at a placed bibliocraft clipboard

### ISSUE THREAD

**Issue by SnowMntGaming** [McJty/TheOneProbe#231]
This is the crash report. I think it's a render crash with the clipboard. I'm not 100% sure it's TOP crashing me or not. I have removed the mod and will be finding out soon if that's the issue. If it's not I'll remove this. Thanks!

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.4.0-64.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-76-core.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  Wizardry Plugin (wizardry-0.7.2.jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.8.jar)
  RandomPatches (randompatches-1.12.2-1.0.1.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  FMLPlugin (elulib-0.1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b148.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  LoadingPlugin (Quark-r1.4-122.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-79-core.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 3/24/18 9:15 PM
Description: Unexpected error

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.BufferBuilder.func_181668_a(BufferBuilder.java:291)
	at mcjty.theoneprobe.rendering.RenderHelper.drawTexturedModalRect(RenderHelper.java:294)
	at mcjty.theoneprobe.apiimpl.client.ElementIconRender.render(ElementIconRender.java:28)
	at mcjty.theoneprobe.apiimpl.elements.ElementIcon.render(ElementIcon.java:45)
	at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:41)
	at mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:41)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:429)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:277)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:117)
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:123)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1266_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:710)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:172)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1418)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BufferBuilder.func_181668_a(BufferBuilder.java:291)
	at mcjty.theoneprobe.rendering.RenderHelper.drawTexturedModalRect(RenderHelper.java:294)
	at mcjty.theoneprobe.apiimpl.client.ElementIconRender.render(ElementIconRender.java:28)
	at mcjty.theoneprobe.apiimpl.elements.ElementIcon.render(ElementIcon.java:45)
	at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:41)
	at mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:41)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:429)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDBlock(OverlayRenderer.java:277)
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:117)
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:123)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1266_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:710)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:172)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Snow_Wolf'/1555412, l='MpServer', x=-83.19, y=41.00, z=-460.11]]
	Chunk stats: MultiplayerChunkCache: 438, 438
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-9,71,501), Chunk: (at 7,4,5 in -1,31; contains blocks -16,0,496 to -1,255,511), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 16936934 game time, 1922647 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 210 total; [EntityWolf['Wolf'/1555476, l='MpServer', x=-39.54, y=70.00, z=-452.41], EntitySheep['Sheep'/1555475, l='MpServer', x=-25.51, y=73.00, z=-467.80], EntityPig['Pig'/1555474, l='MpServer', x=-25.22, y=71.00, z=-474.49], EntityRabbit['Rabbit'/1556022, l='MpServer', x=-124.51, y=72.00, z=-409.59], EntityHorse['Horse'/1556026, l='MpServer', x=-132.12, y=75.00, z=-386.06], EntityZombie['Zombie'/1557024, l='MpServer', x=-111.50, y=37.00, z=-388.50], EntitySkeleton['Skeleton'/1560659, l='MpServer', x=-23.50, y=32.00, z=-395.50], EntityPlayerSP['Snow_Wolf'/1555412, l='MpServer', x=-83.19, y=41.00, z=-460.11], EntityLatchedRenderer['unknown'/81, l='MpServer', x=8.50, y=65.00, z=8.50], EntityPig['Pig'/1556037, l='MpServer', x=-139.66, y=80.00, z=-402.23], EntityPig['Pig'/1556036, l='MpServer', x=-136.53, y=80.00, z=-400.73], EntityPig['Pig'/1556035, l='MpServer', x=-133.99, y=80.00, z=-400.55], EntityHorse['Horse'/1556034, l='MpServer', x=-142.89, y=75.00, z=-417.00], EntityPig['Pig'/1556033, l='MpServer', x=-128.48, y=73.00, z=-412.75], EntityHorse['Horse'/1556032, l='MpServer', x=-143.96, y=78.00, z=-442.84], EntityCreeper['Creeper'/1560693, l='MpServer', x=-25.50, y=37.00, z=-517.50], EntityBat['Bat'/1543794, l='MpServer', x=-87.25, y=2.10, z=-492.25], EntityHorse['Horse'/114, l='MpServer', x=-125.16, y=6.00, z=-517.30], EntityPig['Pig'/1555557, l='MpServer', x=-4.72, y=70.00, z=-475.35], EntityHorse['Horse'/115, l='MpServer', x=-125.68, y=6.00, z=-511.51], EntityCow['Cow'/116, l='MpServer', x=-121.75, y=6.00, z=-506.86], EntityPig['Pig'/117, l='MpServer', x=-124.15, y=6.00, z=-530.70], EntityCow['Cow'/118, l='MpServer', x=-117.19, y=6.00, z=-496.09], EntityHorse['Horse'/120, l='MpServer', x=-119.84, y=6.00, z=-485.08], EntityHorse['Horse'/121, l='MpServer', x=-37.91, y=6.00, z=-507.84], EntityWolf['Wolf'/122, l='MpServer', x=-82.98, y=41.00, z=-462.28], EntityPig['Pig'/123, l='MpServer', x=-120.59, y=6.00, z=-509.75], EntityBat['Bat'/1560172, l='MpServer', x=-43.92, y=3.01, z=-523.67], EntityPig['Pig'/124, l='MpServer', x=-123.94, y=6.00, z=-535.28], EntityCow['Cow'/125, l='MpServer', x=-126.13, y=6.00, z=-531.64], EntityHorse['Horse'/126, l='MpServer', x=-118.30, y=6.00, z=-512.15], EntityIronGolem['Iron Golem'/127, l='MpServer', x=-111.68, y=6.00, z=-495.82], EntityPig['Pig'/128, l='MpServer', x=-125.25, y=6.00, z=-530.66], EntityHorse['Horse'/129, l='MpServer', x=-124.84, y=6.00, z=-528.16], EntityHorse['Horse'/132, l='MpServer', x=-97.32, y=6.00, z=-477.72], EntityIronGolem['Iron Golem'/133, l='MpServer', x=-66.41, y=6.00, z=-490.17], EntityPig['Pig'/136, l='MpServer', x=-125.55, y=6.00, z=-533.53], EntityBat['Bat'/1556127, l='MpServer', x=-70.42, y=44.25, z=-396.25], EntityWolf['Wolf'/137, l='MpServer', x=-110.31, y=6.00, z=-526.28], EntitySkeleton['Skeleton'/1556126, l='MpServer', x=-70.50, y=45.00, z=-393.50], EntityWolf['Wolf'/138, l='MpServer', x=-111.72, y=6.00, z=-513.20], EntityBat['Bat'/1556125, l='MpServer', x=-71.56, y=43.03, z=-400.07], EntityHorse['Horse'/139, l='MpServer', x=-78.15, y=6.00, z=-492.87], EntityZombie['Zombie'/1556124, l='MpServer', x=-69.50, y=43.00, z=-397.50], EntityCreeper['Creeper'/1556123, l='MpServer', x=-71.50, y=43.00, z=-395.50], EntityCow['Cow'/142, l='MpServer', x=-116.36, y=6.00, z=-532.83], EntityPig['Pig'/1556121, l='MpServer', x=-88.96, y=67.00, z=-381.51], EntityCow['Cow'/143, l='MpServer', x=-94.82, y=6.00, z=-531.73], EntityHorse['Horse'/144, l='MpServer', x=-37.80, y=6.00, z=-522.79], EntityCow['Cow'/145, l='MpServer', x=-100.97, y=6.00, z=-536.71], EntityWolf['Wolf'/147, l='MpServer', x=-70.40, y=6.00, z=-482.17], EntityCow['Cow'/151, l='MpServer', x=-49.13, y=6.00, z=-475.45], EntityPig['Pig'/152, l='MpServer', x=-98.89, y=6.00, z=-485.88], EntityRabbit['Rabbit'/1555595, l='MpServer', x=-140.72, y=76.00, z=-451.50], EntityRabbit['Rabbit'/1555594, l='MpServer', x=-135.98, y=76.00, z=-457.04], EntityMinecartModular['entity.Minecart.Vswe.0.name'/159, l='MpServer', x=-72.50, y=6.06, z=-510.15], EntityBat['Bat'/1559176, l='MpServer', x=-93.75, y=2.10, z=-537.25], EntityHorse['Horse'/160, l='MpServer', x=-49.35, y=6.00, z=-479.97], EntityPig['Pig'/1556151, l='MpServer', x=-85.45, y=77.00, z=-425.19], EntityHorse['Horse'/161, l='MpServer', x=-43.25, y=6.00, z=-490.34], EntityZombie['Zombie'/1556150, l='MpServer', x=-108.50, y=41.00, z=-403.50], EntityPig['Pig'/162, l='MpServer', x=-52.23, y=6.00, z=-489.73], EntityHorse['Horse'/163, l='MpServer', x=-40.13, y=6.00, z=-492.10], EntityHorse['Horse'/166, l='MpServer', x=-39.47, y=6.00, z=-511.34], EntityHorse['Black Widow'/169, l='MpServer', x=-98.17, y=6.00, z=-479.30], EntityMinecartModular['entity.Minecart.Vswe.0.name'/472237, l='MpServer', x=-81.03, y=4.06, z=-496.50], EntityHorse['Horse'/170, l='MpServer', x=-44.01, y=6.00, z=-486.12], EntityPig['Pig'/1556157, l='MpServer', x=-71.30, y=80.00, z=-422.40], EntityHorse['Horse'/171, l='MpServer', x=-39.54, y=70.00, z=-471.05], EntityPig['Pig'/1556156, l='MpServer', x=-77.73, y=79.00, z=-423.51], EntitySheep['Sheep'/172, l='MpServer', x=-43.66, y=69.00, z=-475.00], EntityHorse['Horse'/1556155, l='MpServer', x=-78.96, y=79.00, z=-418.89], EntitySheep['Sheep'/173, l='MpServer', x=-36.74, y=70.00, z=-470.78], EntityWolf['Wolf'/1556154, l='MpServer', x=-84.66, y=77.00, z=-406.50], EntityZombie['Zombie'/1556153, l='MpServer', x=-82.23, y=45.00, z=-401.49], EntitySheep['Sheep'/175, l='MpServer', x=-43.48, y=69.00, z=-477.23], EntityCreeper['Creeper'/1556152, l='MpServer', x=-82.50, y=47.00, z=-402.50], EntityItem['item.item.egg'/1556135, l='MpServer', x=-56.00, y=82.00, z=-411.13], EntityChicken['Chicken'/1556134, l='MpServer', x=-53.43, y=82.00, z=-403.82], EntityRabbit['Rabbit'/1556133, l='MpServer', x=-65.36, y=82.00, z=-394.11], EntityHorse['Horse'/179, l='MpServer', x=-34.73, y=6.00, z=-511.12], EntitySheep['Sheep'/1556132, l='MpServer', x=-67.72, y=72.00, z=-389.50], EntitySheep['Sheep'/1556131, l='MpServer', x=-76.44, y=68.00, z=-386.97], EntityHorse['Horse'/181, l='MpServer', x=-49.94, y=6.00, z=-532.89], EntityCreeper['Creeper'/1556130, l='MpServer', x=-70.78, y=54.00, z=-389.19], EntityWolf['Wolf'/182, l='MpServer', x=-36.30, y=6.00, z=-493.14], EntityWolf['Wolf'/183, l='MpServer', x=-36.30, y=6.00, z=-492.30], EntityZombie['Zombie'/1556128, l='MpServer', x=-76.23, y=49.00, z=-386.50], EntityWolf['Wolf'/184, l='MpServer', x=-35.30, y=6.00, z=-494.30], EntityIronGolem['Iron Golem'/185, l='MpServer', x=-42.20, y=6.00, z=-524.47], EntityHorse['Horse'/186, l='MpServer', x=-58.91, y=6.00, z=-470.95], EntityHorse['Horse'/187, l='MpServer', x=-37.00, y=6.00, z=-498.63], EntityPig['Pig'/188, l='MpServer', x=-72.77, y=6.00, z=-481.05], EntityBat['Bat'/1556138, l='MpServer', x=-53.23, y=13.10, z=-388.39], EntityCow['Cow'/191, l='MpServer', x=-35.48, y=6.00, z=-495.17], EntityBat['Bat'/1556136, l='MpServer', x=-53.64, y=13.10, z=-387.53], EntityHorse['Horse'/192, l='MpServer', x=-61.99, y=6.00, z=-528.46], EntityHorse['Horse'/193, l='MpServer', x=-40.70, y=6.00, z=-540.27], EntityHorse['Horse'/195, l='MpServer', x=-46.19, y=6.00, z=-538.93], EntityIronGolem['Iron Golem'/197, l='MpServer', x=-48.58, y=6.00, z=-518.55], EntityWolf['Wolf'/198, l='MpServer', x=-34.30, y=6.00, z=-497.35], EntityWolf['Wolf'/199, l='MpServer', x=-34.30, y=6.00, z=-498.06], EntityPig['Pig'/200, l='MpServer', x=-32.45, y=6.00, z=-505.45], EntityCow['Cow'/201, l='MpServer', x=-33.46, y=6.00, z=-504.25], EntityCow['Cow'/203, l='MpServer', x=-42.62, y=6.00, z=-502.51], EntityWolf['Wolf'/204, l='MpServer', x=-110.34, y=6.00, z=-535.95], EntityCow['Cow'/206, l='MpServer', x=-32.45, y=6.00, z=-506.38], EntityHorse['Horse'/207, l='MpServer', x=-79.15, y=6.00, z=-465.46], EntityHorse['Cobra'/208, l='MpServer', x=-56.86, y=6.00, z=-516.92], EntityCow['Cow'/209, l='MpServer', x=-64.89, y=6.00, z=-538.79], EntityRabbit['Rabbit'/5329, l='MpServer', x=-14.52, y=71.00, z=-481.79], EntityHorse['Horse'/1556166, l='MpServer', x=-80.05, y=68.00, z=-385.98], EntityHorse['Horse'/1556165, l='MpServer', x=-62.93, y=80.00, z=-418.95], EntityCreeper['Creeper'/1556163, l='MpServer', x=-101.99, y=35.00, z=-389.37], EntityZombie['Zombie'/1556162, l='MpServer', x=-101.30, y=35.00, z=-390.16], EntitySheep['Sheep'/1236676, l='MpServer', x=-63.74, y=6.00, z=-468.63], EntityPig['Pig'/215, l='MpServer', x=-64.15, y=6.00, z=-488.12], EntityZombie['Zombie'/1556160, l='MpServer', x=-101.33, y=35.00, z=-389.30], EntityHorse['Horse'/218, l='MpServer', x=-35.10, y=6.00, z=-523.45], EntityHorse['Horse'/219, l='MpServer', x=-39.05, y=6.00, z=-534.79], EntityPig['Pig'/220, l='MpServer', x=-35.58, y=6.00, z=-522.22], EntityWolf['Wolf'/221, l='MpServer', x=-32.30, y=6.00, z=-519.70], EntityWolf['Wolf'/1556170, l='MpServer', x=-66.41, y=80.00, z=-411.47], EntityWolf['Wolf'/222, l='MpServer', x=-36.76, y=6.00, z=-522.43], EntityPig['Pig'/1556169, l='MpServer', x=-69.28, y=80.00, z=-415.65], EntityIronGolem['Iron Golem'/223, l='MpServer', x=-38.70, y=6.00, z=-536.30], EntitySkeleton['Skeleton'/1556168, l='MpServer', x=-77.30, y=45.00, z=-402.18], EntityChicken['Chicken'/1556215, l='MpServer', x=-40.50, y=81.00, z=-385.12], EntityPig['Pig'/1556214, l='MpServer', x=-54.31, y=82.00, z=-393.48], EntityIronGolem['Iron Fist'/226, l='MpServer', x=-129.86, y=6.00, z=-511.89], EntityCow['Cow'/1556213, l='MpServer', x=-43.85, y=82.00, z=-387.26], EntityRabbit['Rabbit'/227, l='MpServer', x=-32.45, y=71.00, z=-472.89], EntityPig['Pig'/1556212, l='MpServer', x=-46.56, y=81.00, z=-415.26], EntityWolf['Wolf'/228, l='MpServer', x=-156.19, y=83.00, z=-480.52], EntityWolf['Wolf'/1556211, l='MpServer', x=-39.31, y=79.00, z=-402.49], EntityBat['Bat'/1544946, l='MpServer', x=-61.97, y=3.10, z=-522.25], EntityPig['Pig'/1556210, l='MpServer', x=-7.35, y=71.00, z=-436.79], EntityHorse['Horse'/230, l='MpServer', x=-40.69, y=6.00, z=-518.91], EntitySheep['Sheep'/1556209, l='MpServer', x=-46.71, y=77.00, z=-424.52], EntityHorse['Horse'/1556208, l='MpServer', x=-37.99, y=79.00, z=-413.13], EntitySkeleton['Skeleton'/1556223, l='MpServer', x=-27.50, y=32.00, z=-394.50], EntityPig['Pig'/234, l='MpServer', x=-20.28, y=70.00, z=-523.58], EntityRabbit['Rabbit'/235, l='MpServer', x=-25.56, y=80.00, z=-509.52], EntityRabbit['Rabbit'/236, l='MpServer', x=-139.65, y=69.00, z=-495.62], EntityWolf['Wolf'/237, l='MpServer', x=-159.38, y=75.00, z=-507.50], EntitySheep['Sheep'/1556218, l='MpServer', x=-10.28, y=72.00, z=-421.51], EntityHorse['Horse'/1556217, l='MpServer', x=-24.00, y=73.00, z=-407.65], EntityRabbit['Rabbit'/240, l='MpServer', x=-16.39, y=68.00, z=-540.80], EntityPig['Pig'/241, l='MpServer', x=-154.94, y=74.00, z=-520.55], EntitySkeleton['Skeleton'/1556198, l='MpServer', x=-17.70, y=36.00, z=-384.52], EntityRabbit['Rabbit'/242, l='MpServer', x=-144.53, y=69.00, z=-515.11], EntitySheep['Sheep'/1556197, l='MpServer', x=-6.49, y=70.00, z=-388.29], EntityHorse['Horse'/245, l='MpServer', x=-155.84, y=72.00, z=-540.11], EntityRabbit['Rabbit'/246, l='MpServer', x=-150.99, y=75.00, z=-533.76], EntityPig['Pig'/247, l='MpServer', x=-129.55, y=6.00, z=-504.08], EntityHorse['Horse'/248, l='MpServer', x=-128.73, y=6.00, z=-505.24], EntityHorse['Horse'/249, l='MpServer', x=-137.86, y=69.00, z=-496.13], EntityCow['Cow'/250, l='MpServer', x=-102.51, y=6.00, z=-469.97], EntityHorse['Horse'/251, l='MpServer', x=-107.01, y=6.00, z=-471.35], EntitySpider['Spider'/1556201, l='MpServer', x=-21.43, y=34.00, z=-382.53], EntityZombie['Zombie'/1559830, l='MpServer', x=-78.82, y=55.00, z=-393.50], EntityHorse['Horse'/258, l='MpServer', x=-74.05, y=6.00, z=-479.93], EntityHorse['Horse'/259, l='MpServer', x=-117.04, y=6.00, z=-491.88], EntityCow['Cow'/260, l='MpServer', x=-119.55, y=6.00, z=-480.49], EntityCow['Cow'/261, l='MpServer', x=-106.28, y=6.00, z=-516.15], EntityHorse['Horse'/262, l='MpServer', x=-104.31, y=6.00, z=-469.70], EntityVillager['Horse'/263, l='MpServer', x=-119.29, y=6.00, z=-481.46], EntityCow['Cow'/264, l='MpServer', x=-112.27, y=6.00, z=-499.17], EntityRabbit['Rabbit'/265, l='MpServer', x=-116.65, y=74.00, z=-470.78], EntityRabbit['Rabbit'/266, l='MpServer', x=-4.49, y=70.00, z=-539.20], EntityPig['Pig'/267, l='MpServer', x=-4.50, y=70.00, z=-539.93], EntityCreeper['Creeper'/1560859, l='MpServer', x=-25.17, y=59.69, z=-500.02], EntityHorse['Horse'/269, l='MpServer', x=-67.17, y=6.00, z=-488.59], EntityWitch['Witch'/1560858, l='MpServer', x=-28.47, y=59.69, z=-500.10], EntityHorse['Horse'/270, l='MpServer', x=-86.80, y=6.00, z=-466.63], EntityHorse['Horse'/271, l='MpServer', x=-102.77, y=6.00, z=-471.18], EntitySkeleton['Skeleton'/1556760, l='MpServer', x=-18.50, y=36.00, z=-388.50], EntityCow['Cow'/272, l='MpServer', x=-114.29, y=6.00, z=-484.19], EntityCow['Cow'/273, l='MpServer', x=-90.85, y=6.00, z=-490.23], EntityChicken['Chicken'/1556227, l='MpServer', x=-15.51, y=76.00, z=-404.13], EntityPig['Pig'/1556226, l='MpServer', x=-9.51, y=74.00, z=-401.27], EntityBat['Bat'/1556225, l='MpServer', x=-21.98, y=30.10, z=-390.19], EntityLatchedRenderer['unknown'/294, l='MpServer', x=-83.19, y=41.00, z=-460.11], EntitySkeleton['Skeleton'/1558423, l='MpServer', x=-23.71, y=34.00, z=-396.51], EntityRabbit['Rabbit'/1555862, l='MpServer', x=-58.79, y=6.00, z=-474.21], EntityRabbit['Rabbit'/1555861, l='MpServer', x=-58.50, y=6.00, z=-472.50], EntityPig['Pig'/1555860, l='MpServer', x=-57.50, y=6.00, z=-473.50], EntitySheep['Sheep'/1555867, l='MpServer', x=-91.50, y=6.00, z=-529.50], EntityRabbit['Rabbit'/1555864, l='MpServer', x=-58.50, y=6.00, z=-473.50], EntityZombie['Zombie'/1558918, l='MpServer', x=-160.50, y=61.00, z=-416.50], EntityZombie['Zombie'/1558917, l='MpServer', x=-162.50, y=61.00, z=-416.50], EntityBat['Bat'/1559427, l='MpServer', x=-92.20, y=3.56, z=-521.58], EntityHorse['Horse'/1555895, l='MpServer', x=-143.13, y=77.00, z=-473.93], EntityCow['Cow'/1555894, l='MpServer', x=-147.45, y=83.00, z=-476.45], EntityWitch['Witch'/1560502, l='MpServer', x=-74.50, y=43.00, z=-402.50], EntityWitch['Witch'/1560500, l='MpServer', x=-72.50, y=43.00, z=-399.50], EntityWitch['Witch'/1560499, l='MpServer', x=-72.50, y=43.00, z=-396.50], EntitySkeleton['Skeleton'/1559974, l='MpServer', x=-28.50, y=46.00, z=-507.50], EntitySkeleton['Skeleton'/1559973, l='MpServer', x=-103.50, y=34.00, z=-388.50], EntitySkeleton['Skeleton'/1557462, l='MpServer', x=-53.50, y=13.00, z=-393.50], EntitySkeleton['Skeleton'/1557461, l='MpServer', x=-50.50, y=13.00, z=-392.50], EntitySkeleton['Skeleton'/1557460, l='MpServer', x=-51.50, y=13.00, z=-391.50], EntityCreeper['Creeper'/1560014, l='MpServer', x=-19.50, y=35.00, z=-381.50], EntityBat['Bat'/1555959, l='MpServer', x=-162.52, y=60.71, z=-417.56], EntityWolf['Wolf'/1555966, l='MpServer', x=-161.68, y=89.00, z=-466.50], EntityBat['Bat'/1559547, l='MpServer', x=-22.59, y=34.27, z=-383.26], EntitySheep['Sheep'/1555939, l='MpServer', x=-68.23, y=70.00, z=-446.48], EntitySheep['Sheep'/1555938, l='MpServer', x=-64.50, y=73.00, z=-439.50], EntityCreeper['Creeper'/1555948, l='MpServer', x=-161.50, y=60.00, z=-418.50], EntitySkeleton['Skeleton'/1555947, l='MpServer', x=-160.76, y=60.00, z=-417.66]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/81, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by McJty** [comment]
What version?

**Comment by SnowMntGaming** [comment]
1.12-1.4.21 
The pack also have the one probe addons version 1.12.2-.1.5.0

**Comment by ProsperCraft** [comment]
Same crash when placing a Bibliocraft clipboard.

https://gist.github.com/ProsperCraft/e0ae5311a9dd60d42ecab25892dd3513

1.12-1.4.22

**Comment by McJty** [comment]
This is a bug in BiblioCraft. Please report to them
