### ISSUE TITLE
[1.12.2] Game crashes when you look at the mob: 'Botfly Larva' from Erebus.

### ISSUE THREAD

**Issue by SonicX8000** [McJty/TheOneProbe#232]
Minecraft: 1.12.2
Forge: 14.23.2.2629

The One Probe: theoneprobe-1.12-1.4.21

Crash Report: https://pastebin.com/wTHk3qDX

-----
Figure I post this here as well, but anyways... in the Erebus there's a mob called "Botfly Larva which... when looked at will cause the game to crash. If you disable the 'isVisible' in the in-game config it won't crash.

**Comment by josephcsible** [comment]
This is a bug in The Erebus. There's nothing that can be done about it on our side. I opened ganymedes01/TheErebus#596 to fix it on their side.
