### ISSUE TITLE
Certain blocks saying 5%

### ISSUE THREAD

**Issue by NicosaurusRex99** [McJty/TheOneProbe#237]
![2018-04-08_12 40 39](https://user-images.githubusercontent.com/11579935/38462677-2ebab63e-3b2a-11e8-9abe-035910bcd5ac.png)
Just a note this is from a dev environment but i havent even implemented top yet
![2018-04-08_12 41 55](https://user-images.githubusercontent.com/11579935/38462681-4593dbe2-3b2a-11e8-83c4-43ea02a2edb7.png)

**Comment by josephcsible** [comment]
That's the block break indicator. Does your mod do anything unusual to block breaking?

**Comment by NicosaurusRex99** [comment]
Not a thing is changed. source can be found [`here`](https://github.com/NicosaurusRex99/JARMGit)

**Comment by NicosaurusRex99** [comment]
Ok so i restarted my instance and now its not showing?!? close the issue?

**Comment by josephcsible** [comment]
I suppose so. Let us know if you can figure out how to reproduce it.
