### ISSUE TITLE
TOP let my client crash.

### ISSUE THREAD

**Issue by zsn741656478** [McJty/TheOneProbe#239]
crash-report : http://paste.ubuntu.org.cn/4320373
Can you help me?

**Comment by McJty** [comment]
Looks like a bug in pixelmon. Please report to them. If they can show that it is not a bug in their mod I can reopen but this kind of issue is typically a problem in the other mod

**Comment by josephcsible** [comment]
Indeed, this is a bug in Pixelmon: they forgot to recompile some of their files after making a change (specifically, `BlockHiddenCube` was compiled with `itemMapping` being a `Map`, but `PixelmonBlocks` was compiled with it being a `HashMap`).
