### ISSUE TITLE
MP Server (TOP 1.4.19) "Waiting for server..." infinitely.

### ISSUE THREAD

**Issue by kamodius** [McJty/TheOneProbe#241]
I have TOP 1.4.19 installed on both my 1.12.2 MP server and locally (verified same file), and while I can see the tooltip in MP, all I get is a consistent "Waiting for server" line under the item name and addon name.

Have tried restarting the server (FTB Horizons III, up to date as of this writing), removing/reinstalling the mod, checked cfg files and nothing is jumping out at me.

Help?

Edit: I have the mod configured to act like WAILA/Hwyla, and it works fine when I'm holding the probe.  The "waiting" line only happens when I'm not holding the probe.

**Comment by McJty** [comment]
That's not a bug in top but something else. Top is just detecting the  problem

**Comment by kamodius** [comment]
I'll try the FTB forums.  Also checking with server support.

Thanks McJ.
