### ISSUE TITLE
Duplicate Item List when looking at ImmersiveCraft inventory

### ISSUE THREAD

**Issue by davqvist** [McJty/TheOneProbe#242]
Forge 2678
MC 1.12.2
The One Probe 1.4.22

When looking at an ImmersiveCraft inventory like a shelf with an item in it, the item shows up twice in TOP. Not sure if this is a TOP or IC bug, but as both mods are yours, I will just report here. See the original report with screenshot here: https://github.com/davqvist/Exoria/issues/141

**Comment by McJty** [comment]
Fixed next release (in ImmersiveCraft)
