### ISSUE TITLE
Display of Large Quanties

### ISSUE THREAD

**Issue by Mohron** [McJty/TheOneProbe#25]
Version: theoneprobe-1.9.4-1.0.11

Currently if an inventory contains large quantity of an item, the number overlap and become unreadable. 

![TOPLargeQuanities](https://s31.postimg.org/q11da0ah7/TOPLarge_Quantites.png) ![TOPLargeSingleQuantity](https://s31.postimg.org/pf5x71hrf/TOPLarge_Single_Quantity.png)

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
Will be fixed next release
