### ISSUE TITLE
[1.11.2] Crash when looking at rftools Sequencer

### ISSUE THREAD

**Issue by Spoilerfx** [McJty/TheOneProbe#250]
I keep getting a fatal error on the client side after placing/looking at the rftools sequencer block.  The server doesn't crash - just the client.  Can't get back log back in with the block is still there.

Tested two different worlds.  Problem resolved only when removing The One probe.  I have attached the latest crash log.
[latest.log](https://github.com/McJtyMods/TheOneProbe/files/2058025/latest.log)

**Comment by DrManganese** [comment]
Does the client have mods that are disabled on the server? Looks like an element id mismatch.

**Comment by Spoilerfx** [comment]
Just left for work.I will check when I get back.I don't believe so.I think I just copied the mods from the server folder to the client.thanks for the suggestion

**Comment by McJty** [comment]
Mod versions?

**Comment by Spoilerfx** [comment]
Looks like server mods folders is identical to my client mods folder; nothing different between the two from what I can see.

theoneprobe-1.12-1.4.22
topaddons-1.12.2-1.6.0-sources
rftools-1.12-7.33
rftoolsctrl-1.12-1.8.1

Need any other mod versions I'm using?  Most are from the lastest FTB Direwolf20 pack.

**Comment by Spoilerfx** [comment]
By the way, I couldn't reproduce the error while running the same mods in a single-player created world.  It only happens when running a dedicated server world.

**Comment by DrManganese** [comment]
Looked at the log again, looks like Top Addons is not on the server, probably the cause.

**Comment by Spoilerfx** [comment]
Got it working!
I just deleted my client mods folder - and copied everything from the server mods folder.  Started it up, and logged in.  I can now look at the sequencer with no crashes. Topsaddons is on the server.  I am so incredibly sorry for wasting your time.  Thank you both for creating such AWESOME mods and helping out.  Especially when its user error!

THANK YOU!
