### ISSUE TITLE
[Issue] not sure if this is to be posted here

### ISSUE THREAD

**Issue by winsrp** [McJty/TheOneProbe#251]
I had this crash, and I can no longer get into my test world due to this? is this yours or for the guy from Immersive Tech?

https://pastebin.com/6NXEth8y

**Comment by josephcsible** [comment]
Can't be fixed on our side. I submitted FerroO2000/Immersive-Tech#60 to fix it on their side though.

**Comment by josephcsible** [comment]
In the meantime, here's an unofficial build of Immersive Tech that contains my fix: [immersivetech-1.12-1.3.9-nonullstacks.zip](https://github.com/McJtyMods/TheOneProbe/files/2063982/immersivetech-1.12-1.3.9-nonullstacks.zip)

**Comment by winsrp** [comment]
cool thanks.
