### ISSUE TITLE
Block Harvest level

### ISSUE THREAD

**Issue by mpdemarco** [McJty/TheOneProbe#258]
In my minecraft the block harvest level are all high by one level.

**Comment by McJty** [comment]
No they are not. Can you show an example where it is wrong according to you?

**Comment by mpdemarco** [comment]
Attach is a image of what I get.

![minecraft pickaxe harvestable level off](https://user-images.githubusercontent.com/31849199/43051646-e4ff3e66-8dea-11e8-9a7b-0e60f635662f.png)

**Comment by josephcsible** [comment]
How is that wrong? Obviously, to mine stone, you need a pickaxe that's at least good enough to mine stone.

**Comment by mpdemarco** [comment]
Whoops my bad, I though it meant to I needed a stone pickaxe.
