### ISSUE TITLE
Support for display from the Buildcraft mod

### ISSUE THREAD

**Issue by xxxLEOPARDxxx** [McJty/TheOneProbe#259]
Do please support the display of tanks and engines from the Buildcraft fashion.
Very necessary...

**Comment by McJty** [comment]
TOP supports all tanks that support the standard capability based API for liquids. It is up to Buildcraft to support that.

**Comment by xxxLEOPARDxxx** [comment]
https://i.gyazo.com/35a506a95f9dba28d3a378ff638aeb40.jpg
https://i.gyazo.com/82683c95edf55c0eb819d8dad85430bc.jpg

Alas, but the liquid from the BC does not show ...
And this is when wearing a helmet with a sensor
Forgot to specify, version 1.12.2

**Comment by McJty** [comment]
yes, this is for Buildcraft to fix

**Comment by Generalcamo** [comment]
Engines cannot be supported as MJ is an unstable API.

As for tanks, they do support capabilities based on the code so I'm not sure what's going on there.

**Comment by McJty** [comment]
Perhaps buildcraft doesn't support getting the capability from side null? As top is nooit a block and so doesn't have a side it requests the information for side null

**Comment by josephcsible** [comment]
Don't we know the side that the player is looking at when they're looking at a block? Perhaps TOP should pass that side instead of null.

**Comment by McJty** [comment]
No because that's not the intended usage. If (for example) you would then look at a furnace you would only get to see the contents that is available through that side. The intention with TOP is that it can see the entire contents (which is what you should be able to get with null side)

**Comment by AlexIIL** [comment]
In theory Buildcraft should expose the fluid capability for the tank from all sides (including null) so so I think I'll need to test this locally to see what's going on.
