### ISSUE TITLE
Requesting an older version of forge then is installed.

### ISSUE THREAD

**Issue by Malus-Lupo** [McJty/TheOneProbe#26]
The latest version of The One Probe on Curse seems to cause loading to fail asking for a older version of Forge then the version of Forge I have installed. 

Forge 12.17.0.1987
TOP 1.0.12
Stated required version of Forge 12.17.0.1976 or newer.

**Comment by McJty** [comment]
Then you should upgrade forge

**Comment by Malus-Lupo** [comment]
Its requesting an older version not a newer version. I have the latest already.

**Comment by McJty** [comment]
Can you give me the full log?

**Comment by Malus-Lupo** [comment]
Hmm I can try one moment please.

**Comment by Malus-Lupo** [comment]
I think these are them? I am not very sure xD
[Logs.zip](https://github.com/McJty/TheOneProbe/files/339986/Logs.zip)

**Comment by McJty** [comment]
You have forge 12.17.0.1968
That's too old. You must upgrade to 12.17.0.1987

**Comment by Malus-Lupo** [comment]
Hmm thanks, forcing it to update seemed to fix it, not sure why it was telling me I had the latest version. Sorry about that!
