### ISSUE TITLE
No mod name label on items

### ISSUE THREAD

**Issue by TheMightyAtomNL** [McJty/TheOneProbe#260]
The One Probe is not displaying the mod name when hovering over items in inventories, even though showModName is set to _always_ on both my client and server:

_# Show mod name (0 = not, 1 = always, 2 = sneak) [range: 0 ~ 2, default: 1]
I:showModName=1_

I find this annoying as you can't identify unkown mod items.
It does show the mod name when looking at blocks in the world.

Game info:
Minecraft version: 1.12.2
Forge version: 14.23.4.2726
Tinker's Construct version: 1.4.23

Mod list:
![mc1122_modlist](https://user-images.githubusercontent.com/9323025/43338322-503961ea-91d6-11e8-81b0-48763cd1bab2.png)

**Comment by McJty** [comment]
There are other mods for this. It is left out on purpose

**Comment by TheMightyAtomNL** [comment]
What other mod do you recommend for that?

**Comment by McJty** [comment]
Hmm I think it is called modname or something. Mezz made it

**Comment by McJty** [comment]
https://minecraft.curseforge.com/projects/mod-name-tooltip

**Comment by TheMightyAtomNL** [comment]
Thanks. :) 👍
