### ISSUE TITLE
Question: Harvest level names

### ISSUE THREAD

**Issue by Liiw** [McJty/TheOneProbe#263]
Hello!

I would like to know from where the harvest levels are taken to be displayed? The reason I am asking is that I am using custom harvest levels with the mod "Tool progression" and I would like to edit the levels data being displayed by The One Probe to reflect the same custom harvest levels. Is that somehow already possible or would it be possible to implement a configuration option for this?

**Comment by josephcsible** [comment]
TOP gets its harvest information directly from the blocks themselves, just like the actual game engine does to determine how harvesting works: https://github.com/McJtyMods/TheOneProbe/blob/e358387cbdc7de108cb37d6bd0660355c79d3159/src/main/java/mcjty/theoneprobe/apiimpl/providers/HarvestInfoTools.java

The problem with Tool Progression is that it doesn't actually update the harvest levels. It just uses events to slow down mining and cancel drops, so as far as the game knows, it's not actually changing any harvest levels. Support for this would have to be added on their side. There's really nothing we can do about this, so just watch tyra314/ToolProgression#43 about this.

**Comment by Liiw** [comment]
Thank you for the answer! I will seek there then.

**Comment by tyra314** [comment]
Harvest level names seem to be hardcoded in TOP: (https://github.com/McJtyMods/TheOneProbe/blob/e358387cbdc7de108cb37d6bd0660355c79d3159/src/main/java/mcjty/theoneprobe/apiimpl/providers/HarvestInfoTools.java#L29)

Nothing I could do there besides evil hacks injecting something from my side.

**Comment by josephcsible** [comment]
@tyra314 Yes, but that's just the names. The actual levels come from here: https://github.com/McJtyMods/TheOneProbe/blob/e358387cbdc7de108cb37d6bd0660355c79d3159/src/main/java/mcjty/theoneprobe/apiimpl/providers/HarvestInfoTools.java#L47

You should make the `block.getHarvestLevel` method return the number that corresponds with the block's new harvest level. It's unfair to expect TOP to display a harvest level different than what `block.getHarvestLevel` returns for the block.

**Comment by tyra314** [comment]
Well. This issue is about the names and those are hardcoded in TOP. There is nothing I can do there.

But please stop claiming things, which aren't true. I update the harvest levels:
https://github.com/tyra314/ToolProgression/blob/master/src/main/java/tyra314/toolprogression/harvest/BlockOverwrite.java#L132

Having said that updating harvest levels isn't all that you have to do to make overwrites possible.
But I didn't expect TOP to pick all that up, I simply said I can't change hardcoded names. Nothing more.
