### ISSUE TITLE
Incompatible with Velocity

### ISSUE THREAD

**Issue by astei** [McJty/TheOneProbe#264]
I am running Forge 2739, Direwolf20 modpack (2.2.0), and the latest version of [Velocity](https://github.com/VelocityPowered/Velocity).

Here's the stacktrace I got when logging into the server after switching between two DW20 servers three times: https://paste.ubuntu.com/p/ZJPyrWXgpD/

**Note**: My DW20 pack is not "vanilla": there is a bug in another of your mods (Deep Resonance) I uncovered prior to finding this issue. That issue is McJtyMods/DeepResonance#271 and it's closely related to this one.

**Comment by josephcsible** [comment]
Please report this to Velocity.

**Comment by astei** [comment]
But I _am_ the author of Velocity, and I'm fairly certain this is an issue in The One Probe, not Velocity. Velocity doesn't do anything crazy to support Forge aside from sending the Join Game packet multiple times and resetting the FML handshake.

**Comment by astei** [comment]
I believe this to be fixed in 1.4.24. Closing this issue.
