### ISSUE TITLE
TOP is getting the localization for items in containers from the server instead of the client

### ISSUE THREAD

**Issue by TheLimePixel** [McJty/TheOneProbe#268]
Currently TOP is getting the names for the items in containers from the server instead of from the client which causes 2 issues when playing on servers:
1. Items from mods that don't localize items on the server (as they shouldn't have to) are unlocalized:
![image](https://user-images.githubusercontent.com/25333164/48673367-d80d8880-eb40-11e8-8a2a-2482fdfd7134.png)
2. When playing in a different language, even the items that have support for it are still displayed in English
![image](https://user-images.githubusercontent.com/25333164/48673536-a09fdb80-eb42-11e8-9c65-186ccd48cecf.png)
![image](https://user-images.githubusercontent.com/25333164/48673539-a5648f80-eb42-11e8-9834-d2e1774264a0.png)

**Comment by DrManganese** [comment]
I see you're using TOPAddons, which takes over from TOP when looking at drawers. It does seem like I'm using the server display name instead of a localized one. So I'll fix that in TOPAddons.

**Comment by TheLimePixel** [comment]
Ah.
