### ISSUE TITLE
Forestry doors show as the wrong type

### ISSUE THREAD

**Issue by mezz** [McJty/TheOneProbe#27]
![2016-07-01_14 36 42](https://cloud.githubusercontent.com/assets/916092/16535055/4941f122-3f99-11e6-95de-4d387caa20e0.png)
![2016-07-01_14 36 33](https://cloud.githubusercontent.com/assets/916092/16535054/49099d54-3f99-11e6-9c14-9ef56ba68500.png)

TOP shows an oak door instead of the type that's being viewed.
It has no issue with logs, planks, stairs, and other wood things. Please let me know if this is a Forestry issue.

**Comment by McJty** [comment]
TOP uses getPickBlock() to figure out what to show. Is your getPickBlock() implementation correct?

**Comment by mezz** [comment]
Tested and:
Forestry door getPickBlock works on singleplayer and multiplayer.
TOP works correctly on singleplayer, but not multiplayer.

**Comment by McJty** [comment]
That's strange because TOP gets that information server side in any case... Hmm....

**Comment by mezz** [comment]
Is there any special-casing for vanilla? My doors inherit from vanilla `BlockDoor`.

**Comment by McJty** [comment]
No not at all. The code can be found here:
https://github.com/McJty/TheOneProbe/blob/1.10/src/main/java/mcjty/theoneprobe/apiimpl/providers/DefaultProbeInfoProvider.java

It is the showStandardBlockInfo method. It only has a special case for the silverfish blocks so that they are not spoiled

**Comment by mezz** [comment]
I took a deeper look and I think the issue is that Forestry has it's `getItem` marked as Client-Side-Only. Thanks!
