### ISSUE TITLE
when looking at melting crucible from ZEN:Foundry the one probe crashes the client

### ISSUE THREAD

**Issue by dredhorse** [McJty/TheOneProbe#277]
running this on a server, modpack is offthebeatenpath

I look at a melting crucible from Zen:Foundry and the client crashes

https://gist.github.com/dredhorse/5a39afbe84f5534e08f7f130d47ea645

TOP Version: 1.4.25
Zen:Foundry Version:  1.7.4

**Comment by josephcsible** [comment]
I can't seem to reproduce the problem with just those mods and their dependencies installed, so I assume one of your other mods is breaking it. Can you try to find a minimal set of mods that triggers the problem?

**Comment by dredhorse** [comment]
have you tried that on a server? I can't reproduce this on singleplayer.
I also updated to latest ZEN_Foundry version, issue still exist.
I have top addons installed, might this be the issue?
Otherwise I don't know, I have several issues with ZEN:Foundry and mod interaction which are not understandable. The modpack has 240 Mods, without an idea to look it is quite cumbersome to try to add / remove every single mod.

**Comment by josephcsible** [comment]
Put this build of TOP on both the client and the server, then upload the full logs of both after the crash happens.

[theoneprobe-1.12-1.4.25+g2082019.zip](https://github.com/McJtyMods/TheOneProbe/files/2751144/theoneprobe-1.12-1.4.25%2Bg2082019.zip)

**Comment by dredhorse** [comment]
did that: https://gist.github.com/dredhorse/21748c350d457d045dcbcce946771b19

messages on on the server: 

[15:18:07] [Server thread/INFO] [STDOUT]: [mcjty.theoneprobe.apiimpl.TheOneProbeImp:registerElementFactory:163]: Registering factory ID 11 as class exter.foundry.integration.top.ElementTemperature$$Lambda$2617/1245325777
[15:18:07] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: dredhorse lost connection: Internal Exception: java.io.IOException: Connection reset by peer

**Comment by josephcsible** [comment]
This is a bug in ZEN: Foundry. There's nothing we can really do in The One Probe to fix or work around it. I opened pull request ZengineeringTeam/Foundry#44 to fix it on their side.

**Comment by dredhorse** [comment]
thanks a lot for helping me out.
