### ISSUE TITLE
Suggestion: Group large items

### ISSUE THREAD

**Issue by whitestarx0312** [McJty/TheOneProbe#28]
Currently, TOP will list every stack of items individually. For instance, when looking at a chest with 10 stacks of wheat, it will show 10 individual item stacks of 64 of wheat. This clutters up display of items when you look at a chest or any other inventory.

My solution would be to do what AE2 and some other mods do when they group large items together. Instead of the wheat coming up as 10 individual stacks, it might just show up as one stack with 640 wheat listed as opposed to 64.

I have attached an example using the mod HoloInventory.
Screens: http://imgur.com/gpdaTYA

As you can see, listing Diorite as 2.3k instead of all those stacks is much easier to read and would allow more information to be displayed while probing inventories with many items.

**Comment by McJty** [comment]
That's a very nice suggestion. I'll try to implement that today

**Comment by whitestarx0312** [comment]
Yay thanks Mcjty :)

**Comment by McJty** [comment]
Will be implemented in 1.0.13 to be released later today
