### ISSUE TITLE
LT incompatibility #2

### ISSUE THREAD

**Issue by CreativeMD** [McJty/TheOneProbe#281]
Hey there,
it's me again ... I posted an issue a well ago (https://github.com/McJtyMods/TheOneProbe/issues/265). Even though this issue was "kinda" solved, there is a new issue. This time it's not about blocks but about entities. TheOneProbe creates duplicates of the entity of LittleTiles:
https://streamable.com/ntsgj

And while we are on it, I don't think that the current solution for blocks is a good one. Our mods should work automatically without the need to modify the config file.

I saw that there are two classes `IBlockDisplayOverride` and `IEntityDisplayOverride`. Can't these be used to disable an entity or a block completely (by implementing a new method)? I don't think it's a big issue if there is no information about the blocks and entities of LittleTiles.

If you want to I can create a pull request for it, because I really want solve this incompatibility. Just let me know what you think about it.

In Regards
CreativeMD

**Comment by McJty** [comment]
This sounds like a bug in LittleTiles. The One Probe just replicates the entity client-side in order to render it but the entity is not added to the world and this works fine for all other mods.

**Comment by CreativeMD** [comment]
Yes, but those entities work quite different, because Minecraft can't handle the entities in the way I want to (they often disappear, collision does not work all the time, etc.). That's why I handle them separately. As I said the easiest solution would be to disable the hover information completely.

**Comment by McJty** [comment]
You can do that in your own mod. No need to add a PR for that. TOP has an API that gives you control over what to show and how

**Comment by CreativeMD** [comment]
But I don't see a way to disable sending the data.

**Comment by McJty** [comment]
The One Probe only sends the data that you want in your support. If you override the default entity display then it will not send that data

**Comment by McJty** [comment]
Basically using IEntityDisplayOverride is probably the best way

**Comment by CreativeMD** [comment]
I did that and returned true and this issue still occurred.

**Comment by McJty** [comment]
Show me your code

**Comment by CreativeMD** [comment]
Pushed it to the repository:
https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/common/entity/EntityAnimation.java#L67
https://github.com/CreativeMD/LittleTiles/blob/1.12/src/main/java/com/creativemd/littletiles/common/blocks/BlockTile.java#L85

I didn't test if it fixes the block issue, I only tested the entity issue which still occurred (tested it using 1.4.27).

**Comment by McJty** [comment]
That's not how IBlockDisplayOverride works. You don't implement this in your tile. You make a separate class that handles it and register it to TOP with ITheOneProbe.registerregisterEntityDisplayOverride()

**Comment by CreativeMD** [comment]
Oh okay ... how to I get the ITheOneProbe?

**Comment by McJty** [comment]
Check the big comment in the beginning of that interface:

https://github.com/McJtyMods/TheOneProbe/blob/1.12/src/main/java/mcjty/theoneprobe/api/ITheOneProbe.java

**Comment by CreativeMD** [comment]
Fixed it! Thank you very very much for your quick help.
