### ISSUE TITLE
TOP doesn't render Blocks.UNLIT_REDSTONE_TORCH

### ISSUE THREAD

**Issue by realmayus** [McJty/TheOneProbe#288]
This does not render an unlit redstone torch:
```java
probeInfo.horizontal()
                    .item(new ItemStack(Blocks.UNLIT_REDSTONE_TORCH))
                    .text(TextFormatting.RED + "Disabled");
```
However, an active redstone torch is rendered just fine:
```java
probeInfo.horizontal()
                    .item(new ItemStack(Blocks.REDSTONE_TORCH))
                    .text(TextFormatting.GREEN + "Enabled");
```

**Comment by McJty** [comment]
That's because an unlit redstone torch has no itemblock. You cannot hold that in your inventory so you cannot make ItemStacks from it. Not much that I can do about that I'm afraid

**Comment by realmayus** [comment]
Ok, no problem. I think I can show it with other items
