### ISSUE TITLE
Fatal internal server error when mousing over an AE2 grid

### ISSUE THREAD

**Issue by auddie2015** [McJty/TheOneProbe#292]
MC 1.12.2

There is no crash report. I mouse over an AE2 grid and the server disconnects. I disabled TOP and TOP Addons and it stopped.

**Comment by auddie2015** [comment]
I am not sure if it is the probe or AE2. One works fine without the other.

**Comment by McJty** [comment]
a) what if you only disable TOP Addons but keep TOP there?
b) can you give me the logs

**Comment by auddie2015** [comment]
Certainly. I will gather them up later as I can't right now. I do have additional information for you in the meantime. Waila/Hwyla also had to be uninstalled also. I do believe it might be AE2 but when I supply you with logs later, you should be able to tell. I can barely even read crash reports so I am very little help to you without them.

**Comment by auddie2015** [comment]
Ok. I was able to sneak back and get to it sooner than I expected. Sorry but this log is huge. 

What I did was create a test world, placed a mekanism creative energy cube, an ME energy accepter, an ME controller, 1 me smart cable. As soon as I placed the cable, the server shut down. (This is the internal server for single player, not a dedicated server. I don't know if that matters so I will add it.)

As a nod to you and many thanks since 1.7.10, if McJty does not work with it, it goes. :-P Gotta have my McJty toys!

[latest.log](https://github.com/McJtyMods/TheOneProbe/files/3102878/latest.log)

EDIT: Oh, I didn't answer a). It is the same with TOP Addons off.

**Comment by auddie2015** [comment]
I believe I found the problem, Sir. It's Better Hud. I have spent the past hour turning off mods until it stopped shutting down the server. I turned them all back on but Better Hud after it did not crash with it off and the server is stable.

I'm sorry to have come to you with a problem from another mod but if anyone else has the issue, you now what causes it.

**Comment by McJty** [comment]
Thanks for letting me know
