### ISSUE TITLE
1.13.2 Error during common_setup event phase

### ISSUE THREAD

**Issue by revdave33** [McJty/TheOneProbe#293]
forge-25.0.154 (actually starts at forge version 142)

The One Probe encountered an error during common_setup event phase
net/minecraftforge/fml/common/gameevent/InputEvent$KeyInputEvent

[top-error-latest.log](https://github.com/McJtyMods/TheOneProbe/files/3109582/top-error-latest.log)

**Comment by Tom-The-Geek** [comment]
Looking at the forge GitHub it appears that a class has been removed in that version and McJty hasn't updated to reflect the change.

**Comment by McJty** [comment]
Since 1.13.2 is a dead end (forge will never get a stable release) I don't plan on updating The One Probe on 1.13.2 anymore. Please use 1.14.3
