### ISSUE TITLE
Crash on launch 1.13.2

### ISSUE THREAD

**Issue by duntwave** [McJty/TheOneProbe#299]
![902782bfa5fde8f7e045e6e0117a02f5](https://user-images.githubusercontent.com/50681151/58288197-7bea2200-7d78-11e9-8a20-0fba016a139e.png)

**Comment by Tom-The-Geek** [comment]
Getting this issue too, but you proboably want to include more details, such as forge version.

**Comment by McJty** [comment]
I'm no longer supporting 1.13 since forge itself will not get updates for it anymore. Move to 1.14
