### ISSUE TITLE
Progress Bars and Number Formatting is Based on Integers

### ISSUE THREAD

**Issue by shadowfacts** [McJty/TheOneProbe#3]
The TOP progress bars and number formatting are based around `int`s. This has been fine because the RF API is `int` based as well. However this prevents using the default progress bar and number formatting utilities with APIs that aren't `int` based. For example, [Tesla](https://github.com/Darkhax-Minecraft/Tesla) uses `long`s for everything making it impossible to precisely use the default progress bar and number formats.

**Comment by McJty** [comment]
I will add an api to work with longs too

**Comment by McJty** [comment]
Support for 'long' is implemented in upcoming release
