### ISSUE TITLE
[1.14.1] Can't configure TOP

### ISSUE THREAD

**Issue by AxolotlAccount** [McJty/TheOneProbe#301]
"The One Probe Read Me" does nothing. That means I can't change position and skin of TOP.
Version: theoneprobe-1.14-1.4.29.beta

**Comment by VaiN474** [comment]
Just wanted to add that no config file is being generated for this version. I'm guessing it hasn't been coded in yet.

**Comment by McJty** [comment]
Indeed. Guis and configs were not coded yet

**Comment by duntwave** [comment]
came here to post just this, it has an interaction animation but does nothing.

**Comment by NomSTeh** [comment]
Really hoping that a config comes soon :D

**Comment by Alejandrom3** [comment]
1.14.4 and still not way to configure it  :/

**Comment by Alejandrom3** [comment]
> 1.14.4 and still not way to configure it :/

using forge 1.14.4 (28.0.45) with theoneprobe-1.14-1.4.32-alpha.jar and cant configure the position of the tooltip. I can change the colors (only between default and black-white) but i cant nor scale nor change the position

**Comment by McJty** [comment]
Be patient please. I have tons of mods to port and a lot of non-minecraft related work lately. So things are somewhat slow

**Comment by McJty** [comment]
Fixed in previous released: /top config command
