### ISSUE TITLE
[1.14.3] Looking at a fox crashes the client.

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/TheOneProbe#312]
Player looked at fox in the wild and crashed.
https://gist.github.com/ProsperCraft/2af4f0dccef60c3aed312d0bcd4465f6

Spawned a fox with a spawn egg, looked at it and crashed.
https://gist.github.com/ProsperCraft/1f0761e2e60fa60c388aedd6bec99d0c

theoneprobe-1.14-1.4.31-alpha
forge-1.14.3-27.0.24

**Comment by ProsperCraft** [comment]
This is still a problem with 1.14.4
Version- theoneprobe-1.14-1.4.32-alpha

https://gist.github.com/ProsperCraft/4cb85b6590a72775f1b5db0cdd3db1bd

**Comment by ProsperCraft** [comment]
https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk?comment=23

**Comment by clonetrooper277** [comment]
I can confirm it STILL crashes on 1.14.4's 1.4.33-alpha version when looking at a fox

[https://pastebin.com/h6J6UU8n](url)

**Comment by McJty** [comment]
Ah I keep forgetting about this. Will try to fix soon. Sorry

**Comment by McJty** [comment]
There is a possibility that this might actually be a bug in forge. Still investigating

**Comment by McJty** [comment]
Actually correction. It appears to be a bug in vanilla itself:
https://bugs.mojang.com/browse/MC-148893
I'll try to work around it

**Comment by McJty** [comment]
Will be fixed next release (today or tomorrow)
