### ISSUE TITLE
[1.14] Passable blocks aren't displayed

### ISSUE THREAD

**Issue by TheLimePixel** [McJty/TheOneProbe#315]
Blocks that mobs can pass through, such as Grass and Flowers aren't displayed in 1.14 TOP.
![image](https://user-images.githubusercontent.com/25333164/61867378-5348ea80-aed7-11e9-8862-00f340de1357.png)
 I assume that you're checking for the collision shape when ray-tracing (I have not checked as I really don't know where you're doing the ray-tracing part) and that'd be why.

**Comment by McJty** [comment]
Fixed next release
