### ISSUE TITLE
Disable TheOneProbe Mob Tooltip

### ISSUE THREAD

**Issue by jakey1995abc** [McJty/TheOneProbe#322]
Does anyone know how I can disable TOP's mob tooltip or at least move it away from the top left?

**Comment by McJty** [comment]
With /topcfg you can configure it
There is also a hotkey to turn on/off the tooltip (see controls)

**Comment by jakey1995abc** [comment]
I've tried searching the controls but nothing exists for TOP. Also the /topcfg command does nothing in game (tried both single player and multiplayer world)

**Comment by McJty** [comment]
What version?

**Comment by jakey1995abc** [comment]
1.14-1.4.34 via Twitch Launcher (forge)

**Comment by jakey1995abc** [comment]
1.14-1.4.34 via Twitch Launcher (forge)

**Comment by jakey1995abc** [comment]
1.14-1.4.34 via Twitch Launcher (forge)

**Comment by jakey1995abc** [comment]
1.14-1.4.34 via Twitch Launcher (forge)

**Comment by jakey1995abc** [comment]
1.14-1.4.34 via Twitch Launcher (forge)

**Comment by jakey1995abc** [comment]
1.14-1.4.34 via Twitch Launcher (forge)

**Comment by jakey1995abc** [comment]
1.14-1.4.34 via Twitch Launcher (forge)

**Comment by jakey1995abc** [comment]
1.14-1.4.34 via Twitch Launcher (forge)

**Comment by jakey1995abc** [comment]
1.14-1.4.34 via Twitch Launcher (forge)

**Comment by jakey1995abc** [comment]
Any idea why its not working?
