### ISSUE TITLE
Cant bind dragons with whistle in a private server(java) 1.12

### ISSUE THREAD

**Issue by Dartin64** [McJty/TheOneProbe#330]
Hey i love this mod and its awesome but when i play on my friends modded server none of us can bind a whistle to our dragons. we tried by making a new server on my pc but it didn't work either,
I tested on a single player and it worked then but not when we were at  the server. 

Yes i tested with fully grown dragons and i also tested with each breed if just one of them were bugged.

please help

**Comment by josephcsible** [comment]
I think you have the wrong mod. This mod has nothing to do with dragons or whistles.

**Comment by Dartin64** [comment]
How tf did I get this wrong, clicked the wrong link, sry...
