### ISSUE TITLE
[Twitch Launcher Interaction] Mods listed as dependents

### ISSUE THREAD

**Issue by DragonGodGrapha** [McJty/TheOneProbe#331]
The One Probe seems to list itself as a dependency of a number of other mods in the Twitch modpack launcher/builder, including EnderIO and Simply Jetpacks 2. Disabling the mod in the launcher will then disable the other mods, which are not actually dependent on The One Probe

**Comment by josephcsible** [comment]
Mods control their dependencies, not their dependents. You should report this to EnderIO and Simply Jetpacks 2 instead.
