### ISSUE TITLE
Can't get fabric to regonize it

### ISSUE THREAD

**Issue by JoshPaulie** [McJty/TheOneProbe#336]
It doesn't show up in mod list, but the jar seems to be the most up to date and properly installed through atlauncher. I also tried disabling HWYLA, as well as all the different beta jars.

**Comment by Flexico** [comment]
What version are you using? I'm on 1.15.2 and have the same problem.

**Comment by McJty** [comment]
The One Probe is a Forge mod. Fabric is no longer supported. It was for a while in 1.14.4 but that port is no longer maintained (due to lack of time)
