### ISSUE TITLE
[1.12.2] TheOneProbe screws with player head rotations

### ISSUE THREAD

**Issue by NotMyWing** [McJty/TheOneProbe#347]
# Bug Report:
When TheOneProbe is present (specifically, when looking at players with TOP), it screws with player head rotations.

# Steps to Reproduce:
1. Install TheOneProbe with default settings
2. Tell a friend to move their head around, up and down
3. Point your crosshair at them for TOP to appear
4. Watch their head rotation constantly rubberbanding to zero

# Mods:
Forge 14.23.5.2824
TOP 1.12-1.4.28

# Video:
https://i.neeve.co/CautiousDizzyAfricanjacana.mp4

**Comment by crdtrd** [comment]
I am having this same problem with version 1.15-2.0.2 and earlier. Using Forge 31.1.27

**Comment by VanillaChan6571** [comment]
Wow this is still an issue and its been a year smh. Wailia does a better job if you wish to use that.

**Comment by McJty** [comment]
What version? This bug has been fixed months ago (just forgot to close this ticket)

**Comment by NotMyWing** [comment]
1.12.2-1.4.28, as specified in the ticket.
This hasn’t been fixed and still affects 1.12.2, so using WAILA is pretty much the only solution.

**Comment by McJty** [comment]
Ah ok. Well I no longer develop on 1.12. It has been fixed in more recent versions. Also this really doesn't sound like a serious problem to me. It's just a visual glitch
