### ISSUE TITLE
Treat all tooltips equally 

### ISSUE THREAD

**Issue by LEWeee** [McJty/TheOneProbe#352]
One of the main reason I never switched completely to TOP was because it didn't treat all of the tooltips equally. A good example of this would be the vanilla shulker box, in the "in-world" tooltip TOP visualizes all of the items inside the shulker box, but when I pick it up, it just displays plain text just like in vanilla (see gif)
![ezgif-3-1e1fac0e5faa](https://user-images.githubusercontent.com/16687385/71532893-fa520800-28f5-11ea-9b2c-74ba3b28ad76.gif)
This however isn't an issue with just portable inventories. Batteries don't show how much RF they have, blocks don't show with which tool you can mine them, etc.

So I think making it so I can see how many RF I have in a battery or what I have in my shulker box without having to read that tiny text would be very much appreciated.

**Comment by McJty** [comment]
The tooltips in your inventory (when picked up) are not handled by TOP at all. Those are done by the respective mods/vanilla themselves. Can't help it that they are different.
