### ISSUE TITLE
[1.12.2] Client kicked when looking at an Ender tank on a server. FMLIndexedMessageCodec exception caught io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException:

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/TheOneProbe#354]
Modpack - TownCraft 4.2 on the official server.
theoneprobe-1.12-1.4.28.jar

Stacktraces-
https://gist.github.com/ProsperCraft/0c8a2971c04de81a2f2cbf657dee881b

Entire Client log-
[latest.log](https://github.com/McJtyMods/TheOneProbe/files/4022063/latest.log)

Entire Server log-
[latest.zip](https://github.com/McJtyMods/TheOneProbe/files/4022064/latest.zip)

**Comment by DrManganese** [comment]
Is it possible that the server and the client don't have the same mods loaded?

This stack trace looks like the ones that occur when a mod that adds a custom TOP element is loaded on the client but not the server.

**Comment by ProsperCraft** [comment]
You Totally nailed it! We had binnies mods on the client but not on the server.  Thank you.
