### ISSUE TITLE
[1.15.2] Crash on startup with One Probe installed

### ISSUE THREAD

**Issue by Boomflex** [McJty/TheOneProbe#358]
Hey McJty!

Added TOP to my WIP 1.15.2 instance and it borks on start up.

Latest log: https://pastebin.com/HM5RZ5u3
Crash report: https://pastebin.com/SnYWGf5E

Removing it fixes the issue.

Thanks :)

**Comment by McJty** [comment]
Hmm but that's a crash in Mekanism? I don't see how TOP can have anything to do with that. Please check with Mekanism

**Comment by Boomflex** [comment]
Even with just TOP and Forge:

Latest log: https://pastebin.com/LcUBzc2i

**Comment by McJty** [comment]
Latest release should fix this
