### ISSUE TITLE
1.15.1 Support for TheOneProbe?

### ISSUE THREAD

**Issue by Gbergz** [McJty/TheOneProbe#359]
Title^

Wondering if It's possible.
- Gbergz

**Comment by McJty** [comment]
No, forge is now on 1.15.2. Please update to 1.15.2

**Comment by Gbergz** [comment]
Ah alright, just that it's a large jump for modpack makers such as me, since half of the mods in packs haven't updated to 1.15.2. So they just don't work on 1.15.2. 

But thanks for the quick answer, much appreciated! :)

**Comment by McJty** [comment]
Are you sure they don't work on 1.15.2? Most 1.15.1 mods should work without issues on 1.15.2. The changes are minimal

**Comment by Gbergz** [comment]
Yeah when I start them up on 1.15.2, the Forge "Error" menu pops up for example when a core mod is missing. 

It says "X Mod requires 1.15.2, Minecraft is on 1.15.1" etc. Or Viceversa!
40+ mods.

**Comment by McJty** [comment]
Ok, but then X mod isn't written well. That shouldn't be the case

**Comment by Gbergz** [comment]
Yeah probably, here's what it looks like btw.
https://gyazo.com/68602fdf125c027ac583aedc05851f46
