### ISSUE TITLE
1.15 issue ..

### ISSUE THREAD

**Issue by DaurTheBro** [McJty/TheOneProbe#360]
i put it into the mods folder.. but it doesnt work at all...doesnt show up or anything..

**Comment by McJty** [comment]
I need a bit more details. Like versions of everything. The log

**Comment by DaurTheBro** [comment]
oh i simply put the mod into my mods folder.. started up my mc .. and i
didnt have the mod ...idk why... it can run fabric right .. ?

V V čet., 30. jan. 2020 ob 19:29 je oseba McJty <notifications@github.com>
napisala:

**Comment by McJty** [comment]
No. This is not a fabric mod. Works on forge only. Sorry

**Comment by DaurTheBro** [comment]
oh okey .. thank you for your time bud P.S on the site it says its supposed
to work on fabric too .. could you tell them to remove that please .. ?
https://www.curseforge.com/minecraft/mc-mods/the-one-probe

V V pet., 31. jan. 2020 ob 05:28 je oseba McJty <notifications@github.com>
napisala:

**Comment by McJty** [comment]
No, that simply means that I had a fabric version of TOP in the past. But that version is no longer maintained

**Comment by DaurTheBro** [comment]
oh okey .. thats a lil sad nut okey.. i was looking forward to it...well
thank you for your time !!
Have a great day !!

V V pet., 31. jan. 2020 ob 16:33 je oseba McJty <notifications@github.com>
napisala:
