### ISSUE TITLE
[1.15.2] Config Resets to default

### ISSUE THREAD

**Issue by NielsPilgaard** [McJty/TheOneProbe#361]
On Minecraft 1.15.2 with `theoneprobe-1.15-2.0.0_1`, the config resets every time I launch the game.

### Versions
- theoneprobe-1.15-2.0.0_1
- Forge-1.15.2-31.1.0

**Comment by McJty** [comment]
What config? Can you be more specific?

**Comment by NielsPilgaard** [comment]
`theoneprobe-common.toml`: `spawnNote = false`, false gets replaced with true on launch.

**Comment by NielsPilgaard** [comment]
Dammit, this was my mistake - I have DefaultSettings installed which overrode my changes, I was editing the wrong file pretty much. Sorry for the bother.
