### ISSUE TITLE
[1.12.2] Mekanism power level overfill

### ISSUE THREAD

**Issue by DevTimur** [McJty/TheOneProbe#368]
TOP can not show more then 2.1 GRF in Mekanism cubes and Induction power storega thingy...
![image](https://user-images.githubusercontent.com/22171136/76515155-c650a280-6461-11ea-8597-fc97bc746daa.png)

Version **theoneprobe-1.12-1.4.28**

**Comment by McJty** [comment]
Not a bug in TOP. The RF API simply doesn't go over 2 Gig. This is something that Mekanism has to solve on their end
