### ISSUE TITLE
Add a config to center the widget

### ISSUE THREAD

**Issue by netzgeist** [McJty/TheOneProbe#37]
I'm playing around with I:boxLeftX, I:boxRightX and it's a guesswork forcing me to restart the client after each iteration. My posX also doesn't seem to translate to other resolutions(so I probably cannot distribute a config set to general audience). Please add a config to center the widgets posX instead.

Edit:

     I:boxLeftX=-170
     I:boxRightX=-170

somehow centers it and works across resolutions. Maybe just add a textual hint for end users.

**Comment by Rated01010010** [comment]
Lol, setting it to -1 automatically centers it man. You wasted so much time for all that trouble. Perhaps he should just comment that -1 automatically centers.

**Comment by netzgeist** [comment]
Excuse me then :(
