### ISSUE TITLE
[1.15.2] Error Encountered during "process_imc" event phase on Server and Game Startup

### ISSUE THREAD

**Issue by chaseyrt** [McJty/TheOneProbe#376]
MC/Server Ver.: 1.15.2
Forge Ver.: 31.1.27
The One Probe Ver.: 2.0.1

On startup attempt both my Server and Game crash. 
Crash Logs (mod list incl.): https://pastebin.com/n6QViHQG

**Comment by chaseyrt** [comment]
More info: I don't do anything to provoke the crash, other than a mod it doesn't like maybe. Its during startup phases, specifically "process_imc". It does get past early setup though. It looks like the game is maybe 99% loaded and then it crashes.

**Comment by McJty** [comment]
Try to upgrade The One Probe to latest (2.0.2). Let me know if that version still has this problem and then I can check it out. Thanks

**Comment by chaseyrt** [comment]
That seems to have fixed it. Probably should have tried that first, huh.
