### ISSUE TITLE
Crash with planttech

### ISSUE THREAD

**Issue by worblood** [McJty/TheOneProbe#38]
Client crash when I probe _Plantalysed Iron Gear_ from _Planttech_ mod.
[crashlog probe planttech.txt](https://github.com/McJty/TheOneProbe/files/405004/crashlog.probe.planttech.txt)

**Comment by McJty** [comment]
That looks like a bug in planttech though. But I'll try to add protection for it anyway

**Comment by worblood** [comment]
Ok,thanks. Not much into this java stuff. I'll put it on their forum as well.

**Comment by McJty** [comment]
This has been rewritten so should no longer be an issue
