### ISSUE TITLE
[1.12.2] AE2 properties not showing properly

### ISSUE THREAD

**Issue by CelestialKitsune** [McJty/TheOneProbe#383]
# Versions
* **Forge** 14.23.5.2847
* **AE2:** rv6-stable-7
* **The One Probe:** 1.12-1.4.28

# Screenshots
![image](https://user-images.githubusercontent.com/30158363/80987516-72938180-8e32-11ea-976d-8e8b64eb01e7.png)
![image](https://user-images.githubusercontent.com/30158363/80987746-c56d3900-8e32-11ea-88ab-0d0bf5ea4089.png)
![image](https://user-images.githubusercontent.com/30158363/80987781-d6b64580-8e32-11ea-8156-a615ed47ccd3.png)

# Expected behavior
Tooltip showed by TOP should display the real informations about AE2 and not the related node.

**Comment by McJty** [comment]
That's something that should be fixed on AE's side. Not much I can do about that

**Comment by CelestialKitsune** [comment]
It properly worked last December though. I will check if AE had an update during these months

_EDIT:_ Last release was on July 2019 ; the issue may come from the server

**Comment by McJty** [comment]
Well The One Probe on 1.12 didn't have any recent updates

**Comment by CelestialKitsune** [comment]
This isn't a mod-side issue, closing. Sorry for wasting your time!
