### ISSUE TITLE
Beast Coin Miner have super high RF storage that doesn’t display

### ISSUE THREAD

**Issue by furtabs** [McJty/TheOneProbe#385]
The Beast Coin Miner is a block that can mine FTBQuests Currency. Fair enough but the Block can store a crap ton of power probally up to the 64bit int limit and the one probe doesn’t like this. It goes up normally, then into the legs tubes and back normally and back into the negatives but the machine’s power is still accurate.

![9E6BCE01-3982-4424-908B-AEFDA1E95F91](https://user-images.githubusercontent.com/48419040/82204106-4f58df80-98d2-11ea-8d67-c8ab5f2f4180.jpeg)

**Comment by McJty** [comment]
That's a bug in the Beast Coin Miner. If it can store that much power and it also supports the RF API (which TOP can see) then it needs to control the value itself. There is nothing that TOP can do about that

**Comment by furtabs** [comment]
@modmuss50 said it was a TOP bug since the machines GUI properally displays it but it goes up to integer limit so I’m not really aure

**Comment by McJty** [comment]
Top simply shows the value that the forge energy api reports. This is most certainly not a big in TOP. If modmuss thinks it is I would like to know how that could be
