### ISSUE TITLE
[Enhancement] Add Option to Center Info Box Regardless of MC Window Size

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [McJty/TheOneProbe#391]
Currently you cannot center TheOneProbe info box to be in the top center of the screen because when you switch screen sizes, it also changes the position of the box. 

Makes it difficult for modpack makers trying to satisfy everyone at once (in a way that is similar to WAILA where it is center top of screen).

I'm using Forge 1.12.2. 
Please add, thank you!

**Comment by 4rz0** [comment]
How did you set it to be in the center?
It actually stays in the center for me regardless of screen size.

**Comment by PiggiesGoSqueal** [comment]
Via the in-game settings. Although if you want specifics, I don't recall and I don't have time to check. Sorry. So I'll just close this I guess.

**Comment by 4rz0** [comment]
Ha, that's what I was doing for quite a while as well :)
That setting is the offset for the left alignment used by default. I don't recommend using that as this leads to the issues described.
Instead use the ToP readme paper thingie and shift-rightclick in the air with it.
This opens another GUI where you can set ToP to use a centered alignment instead (or any other).

**Comment by PiggiesGoSqueal** [comment]
> 
> 
> Ha, that's what I was doing for quite a while as well :)
> That setting is the offset for the left alignment used by default. I don't recommend using that as this leads to the issues described.
> Instead use the ToP readme paper thingie and shift-rightclick in the air with it.
> This opens another GUI where you can set ToP to use a centered alignment instead (or any other).

Ah okay, thank you! I'll try that when I get the chance.
