### ISSUE TITLE
The one Probe encountered an error during the process_imc event phase

### ISSUE THREAD

**Issue by Fidulus** [McJty/TheOneProbe#393]
![image](https://user-images.githubusercontent.com/48780170/86874358-86808b80-c0e0-11ea-8778-c33acd241300.png)

https://pastebin.com/KxqB7grM

I am playing on 1.16.1
I wish i could use this mod so badly. But i am not sure what's the cause of this error.

Thank you for the great work on this mod.

**Comment by McJty** [comment]
This is a problem in the global-xp mod:
https://www.curseforge.com/minecraft/mc-mods/global-xp
I notified the author and he will fix it soon
