### ISSUE TITLE
[1.12.2] Suggestion + bug

### ISSUE THREAD

**Issue by Alyaqdhans** [McJty/TheOneProbe#403]
fix the info not showing and add a way to disable the (entity) pictures .

![Screenshot (159)_LI](https://user-images.githubusercontent.com/58079015/90085276-a54def80-dd28-11ea-8c83-e0bf10995b7b.jpg)

**Comment by McJty** [comment]
The info not showing is not something that I can fix on my side. That's for Ice And Fire

**Comment by Alyaqdhans** [comment]
But why waila can show the info?

**Comment by McJty** [comment]
It is up to the mods to provide support for waila or TOP. Apparently Ice And Fire chose to only support WAILA. You should ask them to also add TOP support

**Comment by Alyaqdhans** [comment]
In previous version of ice and fire TOP was working fine but idk what they mass up in newer versions, anyways thank you and can you add the suggestion were you be able to disable entity pictures only?
Because look at the picture the dragon picture little disturbing the info.
By the way I found your mod more cooler then waila :)
