### ISSUE TITLE
Cant load mod in 1.16.2

### ISSUE THREAD

**Issue by UnRealDinnerbone** [McJty/TheOneProbe#409]
The One Probe crashes when trying to load in 1.16.2 due to it need a license parameter in the mods.toml 

https://gist.github.com/UnRealDinnerbone/46087b97344170507c20d249313fa156

(Im guessing this is the same for your other mods)

**Comment by McJty** [comment]
Um no this isn't. The license is present in all my mods and other people are using my mods just fine. No idea why it fails for you

**Comment by UnRealDinnerbone** [comment]
Oh, I should have mentioned that was from the maven jar 1.16-3.0.0-beta-3, and I got this error while trying to add The One Probe to my dev environment, I guess you have just not updated the maven jar yet then

**Comment by McJty** [comment]
You're also not using the latest available on the maven

**Comment by UnRealDinnerbone** [comment]
oh I read the version on maven backward the top one is the lastest sorry about that

**Comment by gamma-delta** [comment]
Hello, I'm having the same issue. I'm using version `1.16:1.16-3.0.6-8`, and that looks like the most recent one...

**Comment by McJty** [comment]
1.16:1.16-3.0.6-8? Where did you get that from? CurseForge shouldn't have the -8 added after it. Download the mod from the proper curseforge page please

**Comment by gamma-delta** [comment]
I got it from your maven, because I'm developing a mod and I would like to use it... but I think some friends are helping me.
