### ISSUE TITLE
ToP claims bedrock is harvestable

### ISSUE THREAD

**Issue by darknife25** [McJty/TheOneProbe#41]
When using a ToP helmet and holding a pickaxe, bedrock shows as harvestable, this also occurs with command blocks, so it may occur with other blocks with a hardness of -1

![](http://puu.sh/qAZiG/fe0421e1ca.jpg)

Minecraft 1.10.2
ToP: 1.0.15
Forge : 12.18.1.2056

**Comment by McJty** [comment]
Fixed next release
