### ISSUE TITLE
[1.16.2] Game crashing as I look at an item from another mod

### ISSUE THREAD

**Issue by alorg** [McJty/TheOneProbe#413]
So not certain if it's this mod that's making the game crash or the other mod (Scannable) but if I look at the tool it crashes immediately. 
[crash-2020-08-29_22.47.47-client.txt](https://github.com/McJtyMods/TheOneProbe/files/5146022/crash-2020-08-29_22.47.47-client.txt)

**Comment by McJty** [comment]
It's actually crashing in Scannable so I would report it to them
