### ISSUE TITLE
Any plans/considerations for a future Fabric version?

### ISSUE THREAD

**Issue by MechanosG** [McJty/TheOneProbe#420]
Probably not, but figured I'd ask.  Fabric is gaining popularity in 1.16.x and I made the switch, but I miss muh probe.

**Comment by McJty** [comment]
I don't get the impression that Fabric is gaining in popularity but in any case. I don't have the time for that. I barely manage to maintain my forge mods

**Comment by MechanosG** [comment]
Alright, fair enough.  Regarding Fabric, I'm sure you probably don't want Forge drama on here.  Between Lex chasing people away, and lots of devs claiming Fabric is easier to learn (and Sodium/related mods being awesome and primarily being on Fabric) there's a lot of Fabric mods and modpacks showing up now.  https://www.curseforge.com/minecraft/mc-mods/fabric?filter-game-version=2020709689:8056&filter-sort=2
