### ISSUE TITLE
Client-side config not working on multiplayer

### ISSUE THREAD

**Issue by danielmartin0** [McJty/TheOneProbe#426]
On 1.15-2.0.7, adjusting which information is displayed using theoneprobe-client.toml has an effect on singleplayer worlds, but neither that nor anything server-side appears to change which information is shown in multiplayer.

**Comment by Trnrr** [comment]
This is still an issue on version 1.16-3.0.6. Doesn't work for any of the extended information while playing on a server but works fine in singleplayer (Chests/Shulkers/Mekanism Pipes/etc). I also have TOP on the server. Not sure if it's needed but just kept it on to test if that would fix it but it didn't.

**Comment by McJty** [comment]
This is indeed only possible server side. By design
