### ISSUE TITLE
For some reason the one probe does this to create trains

### ISSUE THREAD

**Issue by ZoruaBit** [McJty/TheOneProbe#428]
![unknown](https://user-images.githubusercontent.com/39221658/102924612-8b02eb80-4457-11eb-969c-24800b1ce501.png)
This is a compatibility issue with the one probe and create it seems.

**Comment by ZoruaBit** [comment]
This is 1.16.4 btw

**Comment by Zangdorx** [comment]
I did some testing, it only happens when you look at one of the minecarts with the probe active, but once broken, it stays broken until you dismantle the contraption. Also, it is not just a visual bug. The contraption hitbox is where the contraption is shown.

**Comment by McJty** [comment]
Report to the trains mod. That's a bug on their side

**Comment by ZoruaBit** [comment]
i have and i think they said it was on your side.

**Comment by McJty** [comment]
Well I don't see how that can be. The One Probe works fine with many mods. It's a heavily used mod and the past times when something like this occurs it was always on the other side. They must make sure that their entity can properly be persisted from server to client. It's on them to fix this

**Comment by McJty** [comment]
And if they really think it's on my side then please let them give more information about what exactly they think TOP is doing wrong

**Comment by ZoruaBit** [comment]
that is fine. i gave them the bug at the same time i gave you and i just know that it was someone in their server who said it was on your side. i thought it was a dev but it may not have been. if they really do think its on your side ill ask for more info and send it your way. i am sorry if my presents has spouted any arguments

**Comment by simibubi** [comment]
Apologies for the confusion- 'The trains mod' never claimed to not be at fault here, community folks just like to point fingers when it takes another mod to break something. =)
TOP creating additional clientside entities with identical UUIDs confused our renderer- it was an unfortunate interaction, but more easily fixed on our end. 
Consider this resolved. o7

**Comment by ZoruaBit** [comment]
ok apoligies for teh confusuion on my end aswell. i never ment to point fingers. i hope you all have a very nice day

**Comment by McJty** [comment]
Happy this got resolved! Thanks
