### ISSUE TITLE
(1.12.2  RTM Problem) 

### ISSUE THREAD

**Issue by Elkrecio** [McJty/TheOneProbe#429]
hello when am install this mod or hwyla I have problems with trains models, not respawn train only two boxes 
with a polled sign https://ibb.co/Krz19Cb

**Comment by McJty** [comment]
That link doesn't work

**Comment by Elkrecio** [comment]
> That link doesn't work
 now works 
https://ibb.co/Krz19Cb

**Comment by Elkrecio** [comment]
Pla help me, because am need the one probe and RTM in my server,

and I don't know what to do to fix it

**Comment by Elkrecio** [comment]
![problem](https://user-images.githubusercontent.com/76511666/102970593-1633be00-44f8-11eb-9e2d-2b346d0528d0.png)

**Comment by McJty** [comment]
Why are you reporting this to The One Probe? That bug has nothing to do with it. Report it to the author of the trains mod
