### ISSUE TITLE
Suggestion: Center alignment

### ISSUE THREAD

**Issue by NerdMcBoon** [McJty/TheOneProbe#43]
It would be really neat to have an option to center the display.

For example, if I set the the distance to the left side of the screen to ~160, the TOP box is approximately in the center of the screen for some blocks, but not for others, as the box is alligned to the left.

**Comment by McJty** [comment]
Set both left and right to -1 and it will center

**Comment by NerdMcBoon** [comment]
Ohh, very nice! Thank you very much!
