### ISSUE TITLE
[1.12.2] bug

### ISSUE THREAD

**Issue by DarkerFALLEN** [McJty/TheOneProbe#430]
there is a bug in my minecraft from 1.12.2, I have the latest top version, and I play in a modpack with pixelmon, but my top does not appear in the information window at all and in any block or pokemon, can anyone help me?

**Comment by McJty** [comment]
Can you give me more information? Do you have the probe note item in inventory? Is the mod installed on the server?

**Comment by DarkerFALLEN** [comment]
yes in singleplayer I win the book and it doesn’t have the mod, but the mod is not a client? and either in singleplayer or on the server, no information window appears for anything.

**Comment by McJty** [comment]
TOP is also needed server-side. It sounds like the mod is not configured right. Try the /topneed or /topcfg commands to configure it
