### ISSUE TITLE
Massive false Preparing crash report in latest.log file

### ISSUE THREAD

**Issue by Ritzumi** [McJty/TheOneProbe#431]
#Log
latest.log: https://gist.github.com/Ritzumi/0a95ca9ab861da9540659a3c77b68ac8

#Mod 
Theoneprobe: 1.16-3.0.6
Forge: 35.1.28
Only The one probe is presented in the mod during test

#Step to reproduce
1. Create a new world
2. Use command /summon (In my case, I summoned Iron golem)

#Description
The log spammed when entity is summoned and player look at it. While it said it is preparing crash log, nothing actually happened.

**Comment by McJty** [comment]
Does this also happen with mobs that are not summoned? Also what command did you use exactly to summon this mob?

**Comment by Ritzumi** [comment]
The command I use is /summon minecraft:iron_golem

Update: I did tested on the mobs that spawn normally. including summon golem by using iron block and pumpkin. The result is that It also happened to normal iron golem as well. However, so far I found 2 mobs creating these report: wolf and iron golem. Not sure if there is more or not, but pig, chicken and cow seem to not produce this bug.

**Comment by McJty** [comment]
I can reproduce this. Investigating

**Comment by McJty** [comment]
Fixed in 3.0.7
