### ISSUE TITLE
There are no textures for mobs from the better animals plus mod.

### ISSUE THREAD

**Issue by GnomTocha** [McJty/TheOneProbe#434]
![2021-01-08_12 54 27](https://user-images.githubusercontent.com/75666317/104008789-fb7d6c80-51ba-11eb-8763-7db9fd61f362.png)
![2021-01-08_11 25 57](https://user-images.githubusercontent.com/75666317/104008801-01734d80-51bb-11eb-9ad2-c2d2f2951de0.png)

**Comment by McJty** [comment]
It is possible that the next release fixes this. Haven't tested it though. Reopen if not fixed
