### ISSUE TITLE
Log spam when rendering nature aura's powder

### ISSUE THREAD

**Issue by Ritzumi** [McJty/TheOneProbe#435]
#### Versions
Forge: 35.1.36
Nature aura: 33.3
The one probe: 1.16-3.0.7

#### Description
When player look at placed nature aura powder, the one probe will show nothing and spam crash report in log files.

#### Step to reproduce
1. Create a world.
2. Get nature aura powder (In my case, I use powder of the bountiful core).
3. Behold~

#### Attachments
Log: https://gist.github.com/Ritzumi/69bfe8af2de60394b3396c7bd703ca6d
Manual Crash log (In case system detail is needed): https://gist.github.com/Ritzumi/b1ac2e946ae3480362f5a69304bf943e
Picture: https://imgur.com/a/Xaee5SP

**Comment by Danekjovax** [comment]
Not sure if it's related, but I also am having massive log spam like the one your log is reporting, though it's just when I'm exploring after RTPing.  Link to log: https://gist.github.com/Danekjovax/bd49f18fbb422a2941d6b746bb3d51d2

**Comment by McJty** [comment]
I'll check it out

**Comment by Danekjovax** [comment]
Much appreciated, McJty.  Not sure how far I can help in this, but I have isolated a part of my map where this lag occurs and been watching my log real-time as I approach the lag area in question.  Nothing on the log, but I see this:
![2021-01-09_12 55 52](https://user-images.githubusercontent.com/10191173/104105458-2e3b6980-527c-11eb-9d46-5865b891d48b.png)

The "Waiting on Server" message never goes away, and punching grass and other entities don't give drops.  Waiting several minutes doesn't help; the lag is perpetual.  I have to kill the task from TaskManager to get back to the desktop.

**Comment by Ritzumi** [comment]
Hmm, I believe that "waiting for server" problem is caused by other mods. The one probe didn't get information from integrated server (Run in SP) because it was freeze or deadlock so it wait for info to be sent to it (Which never came because server already freeze). The cause is quite hard to find since it often has no log to scope down. I once had this problem too, that time it was ice and fire: dragon 2.1.4, but I believed it was fixed in the 2.1.5 . 
My recommend if you tried to find the root of the bug is to tried to remove some mods and try entering that area (Backup first). Start with mod that modify the game (Such as performant) then big content (Ice and fire) to small. It would take quite a time, but hope it would give you the answer.

**Comment by McJty** [comment]
This is actually a bug in the other mods. For example in the first log it is crashing in Nature's Aura itself. Nothing TOP can do about it I'm afraid. You can work around this bug by blacklisting the rendering of the entity (renderBlacklist in theoneprobe-common.toml) but the actual bug is not in TOP

**Comment by Ritzumi** [comment]
Affirmative, I will try to report to nature aura and hope it got fix on their end. Thanks!

**Comment by Ritzumi** [comment]
Closed, the render is working normally now. I was doing a test again since I can't blacklist it (Also I saw blacklist in client only btw) so I remove entire the one probe configurations and get a new one. While testing with these configs, the issues disappear (I still can't backlist anything btw >> ).
https://imgur.com/a/C1DyUmI

**Comment by McJty** [comment]
Why can't you blacklist things? I don't understand? Can you describe that more fully? Also what TOP version? The blacklist feature is very recent

**Comment by Ritzumi** [comment]
I would like to know too why.
This is the configuration in theoneprobe-client.toml

#This is a list of entities that will not be rendered by TOP. This option also works if it is set client-side alone
renderBlacklist = ["minecraft:villager"]

This is applied while I was in game (The config should update synchronously)

[10Jan2021 13:34:29.364] [Thread-1/DEBUG] [net.minecraftforge.fml.config.ConfigFileTypeHandler/CONFIG]: Config file theoneprobe-client.toml changed, sending notifies
[10Jan2021 13:34:29.364] [Thread-1/FATAL] [mcjty.theoneprobe.TheOneProbe/CORE]: theoneprobe config just got changed on the file system!

And this is the result: https://imgur.com/a/TqZZixV

Did I do something wrong? Or are there something that I miss?

Edit: My the one probe version is the latest (1.16-3.0.7)

**Comment by McJty** [comment]
Try restarting. Not sure that I implemented config reloading correctly

**Comment by Ritzumi** [comment]
Ok, the model no longer load now. I suppose restart is required.

Picture: https://imgur.com/a/YUDOQcJ
