### ISSUE TITLE
Weird Rendering of Paintings

### ISSUE THREAD

**Issue by GabuSilver** [McJty/TheOneProbe#439]
When using TOP and looking at a painting (also using subtitles) this happens: (Image)
![2021-01-15_16 09 44](https://user-images.githubusercontent.com/67985325/104788218-b9769c80-575f-11eb-9241-bb36e27c33d5.png)
![2021-01-15_16 10 17](https://user-images.githubusercontent.com/67985325/104788220-bb406000-575f-11eb-96f1-81fca4d9511c.png)

**Comment by McJty** [comment]
Should be fixed next release
