### ISSUE TITLE
Staring at paintings causes log spam.

### ISSUE THREAD

**Issue by Eldresh** [McJty/TheOneProbe#440]
**Minecraft Version:** 1.16.4
**Forge Version:** 35.1.13
**One Probe Version:** 3.0.7

When looking at a painting, when the one probe info box should come up lots of log spam is produced. I tested and this happens with only The One Probe installed, on a fresh install in a new world.

**Steps:**
- Create a new world or load an existing one.
- Look at a painting close enough that the one probe's info box should pop up,
- Watch your log go crazy.

I've attached my latest.log and debug.log, the error message in question is this one:

> [19Jan2021 12:21:26.077] [Render thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 8e66a1cf-5797-4d79-8b2c-9b9df23d934f
> [19Jan2021 12:21:26.093] [Render thread/ERROR] [mcjty.theoneprobe.TheOneProbe/]: Error rendering entity!
> net.minecraft.crash.ReportedException: Rendering entity in world
> 	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:279) ~[?:?]
> 	at mcjty.theoneprobe.rendering.RenderHelper.renderEntity(RenderHelper.java:66) ~[theoneprobe:1.16-3.0.7]
> 	at mcjty.theoneprobe.apiimpl.client.ElementEntityRender.renderEntity(ElementEntityRender.java:184) ~[theoneprobe:1.16-3.0.7]
> 	at mcjty.theoneprobe.apiimpl.client.ElementEntityRender.render(ElementEntityRender.java:72) ~[theoneprobe:1.16-3.0.7]
> 	at mcjty.theoneprobe.apiimpl.elements.ElementEntity.render(ElementEntity.java:68) ~[theoneprobe:1.16-3.0.7]
> 	at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:42) ~[theoneprobe:1.16-3.0.7]
> 	at mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:42) ~[theoneprobe:1.16-3.0.7]
> 	at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:433) ~[theoneprobe:1.16-3.0.7]
> 	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDEntity(OverlayRenderer.java:200) ~[theoneprobe:1.16-3.0.7]
> 	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:86) ~[theoneprobe:1.16-3.0.7]
> 	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:110) ~[theoneprobe:1.16-3.0.7]
> 	at net.minecraftforge.eventbus.ASMEventHandler_25_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic) ~[?:?]
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
> 	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:634) ~[forge:?]
> 	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:187) ~[forge:?]
> 	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:471) ~[?:?]
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
> 	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.13.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_261]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.13.jar:35.1]
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.client.renderer.entity.PaintingRenderer.func_225623_a_(SourceFile:41) ~[?:?]
> 	at net.minecraft.client.renderer.entity.PaintingRenderer.func_225623_a_(SourceFile:23) ~[?:?]
> 	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?]
> 	... 29 more

[latest.log](https://github.com/McJtyMods/TheOneProbe/files/5837849/latest.log)
[debug.log](https://github.com/McJtyMods/TheOneProbe/files/5837850/debug.log)

**Comment by McJty** [comment]
Fixing this right now

**Comment by McJty** [comment]
Fixed next release
