### ISSUE TITLE
Help with location on screen

### ISSUE THREAD

**Issue by CrazyGamer2241** [McJty/TheOneProbe#441]
I want to preset the location to the middle top 3rd of the screen (like waila) instead of having to open the probe thing and do it that way if that makes sense. is there a way i can do this through configs or something?

**Comment by McJty** [comment]
What version?

**Comment by CrazyGamer2241** [comment]
1.12.2

**Comment by McJty** [comment]
Try the /topcfg command

**Comment by CrazyGamer2241** [comment]
Will that make it so it starts at the top on the server side or just the
client side if you know what I mean, I'm trying to run it on a server with
friends and instead of getting them to do it I want to have it pre
configured.

**Comment by McJty** [comment]
Ah yes, for that you have to check the configs. The position is there somewhere (forgot where though and can't look atm). Just check the TOP config

**Comment by CrazyGamer2241** [comment]
Ok I'll check it out and let you know my findings, thank you

**Comment by CrazyGamer2241** [comment]
Ok looks like it worked. Thanks very much
