### ISSUE TITLE
Issue with Paintigns #2

### ISSUE THREAD

**Issue by AbsolemJackdaw** [McJty/TheOneProbe#444]
When looking at my gui, that draws paintings for people to select them, 
my users cannot see the GUI with your mod installed. 

i'm trying to figure out if its on my end or yours. Hope we can fix this together !

https://github.com/ArtixAllMighty/Paintings--/issues/44

**Comment by McJty** [comment]
Did you figure anything out here? I'm not really sure what to do about this from my side

**Comment by McJty** [comment]
It is possible that the next release fixes this. Let me know if it doesn't

**Comment by AbsolemJackdaw** [comment]
Okay thanks. sorry, i have been a bit inactive recently. I'll see if anyone reports issues still or i'll try and test it myself.
