### ISSUE TITLE
Update to 1.16.5

### ISSUE THREAD

**Issue by Tander** [McJty/TheOneProbe#446]
It shouldn't be too hard, considering there is not much difference between 1.16.4 and 1.16.5. TheOneProbe is the best, don't want to install Wawla =)

**Comment by McJty** [comment]
Doesn't it work on 1.16.5 already? Nothing changed

**Comment by Tander** [comment]
Sorry, I should have specifed: At this moment I can't use this mod in curseforge modpack, because it isn't marked for 1.16.5 (and via that - not listed in mods for this version of minecraft)
So it isn't exactly mod issue, but since curseforge comments are closed I had to report it here.

**Comment by McJty** [comment]
Well that's an annoying thing about curse. But I wonder though. My other mods (and also TOP) are already being used in 1.16.5 modpacks (like All The Mods 6). How did they do it then?

**Comment by Tander** [comment]
Probably by using some manual workarounds, like putting .jar files into modpack manually, keep them up to date manually, and of course having a long moderation process each modpack update. Not very convenient. So if you fix that issue on your side it would be nice. But anyway, thanks for great mods.

**Comment by McJty** [comment]
Ok, I added the 1.16.5 tag
