### ISSUE TITLE
ice and fire dragons - TOP data

### ISSUE THREAD

**Issue by WilliamBlaze** [McJty/TheOneProbe#448]
When using The One Probe on any of the dragons from the "ice and fire dragons" mod in 1.16.4/1.16.5 the TOP data window no longer show's a dragon's Gender - even when using the creative probe to view a dragon with.

I know this feature use to be working in older versions of The One Probe so I figured it worth mentioning how this feature doesn't seem to work in the 1.16.4/1.16.5 Versions of Minecraft when using the TOP and I&RD mods together. Not sure if it was intentionally removed, left out due to a lack of time or if its just a hiccup/bug on TOP's end for why this feature in the data no longer registers.

**Comment by McJty** [comment]
This is on the side of Ice and Fire to fix
