### ISSUE TITLE
Errors from console, Report only

### ISSUE THREAD

**Issue by utoc** [McJty/TheOneProbe#45]
Paste here: http://pastebin.com/pUmcYRAd
Running FML 2068 and TOP 1.10-1.0.15 with TOPAddons 1.10.2-0.5.0 in MC1.10.2

Unfortunately I don't know which user it was but I have maybe 4-5 dozen of these errors on the console for the duration while the server had been online.  This may not be of any great concern but I'd like to pass it on just in case.

**Comment by McJty** [comment]
Hmm I'll check it out but seems to be caused by some mod returning an invalid harvest level. But I'll add protection for it

**Comment by McJty** [comment]
BTW I wasn't aware of the mod TOPAddons. Do you have a link for that?

**Comment by utoc** [comment]
https://github.com/DrManganese/TOPAddons

and 

https://minecraft.curseforge.com/projects/top-addons

**Comment by utoc** [comment]
After some basic troubleshooting, this may be ActuallyAdditions crops when they are first planted (effectively 0%) and its a little inconsistent.  ExtraUtils2's Enderlilly doesn't display a growth stage but looking at it doesn't cause the error.

**Comment by McJty** [comment]
Worked around the bug for next release
