### ISSUE TITLE
Mod names with spaces are not displayed correctly

### ISSUE THREAD

**Issue by IchHabeHunger54** [McJty/TheOneProbe#451]
Well... the title pretty much says it. See these screenshots for the exact problem.
![2021-03-13_20 27 30](https://user-images.githubusercontent.com/52419336/111041949-1a0e1700-843b-11eb-9b7d-74c1284c484d.png)
![2021-03-13_20 28 03](https://user-images.githubusercontent.com/52419336/111041952-1bd7da80-843b-11eb-90c8-c7cb40e06cc0.png)
![2021-03-13_20 28 12](https://user-images.githubusercontent.com/52419336/111041954-1da19e00-843b-11eb-8f5b-b54d8e6288d5.png)

**Comment by McJty** [comment]
This is fixed in the next release
