### ISSUE TITLE
Console crash spam with GuardVillagers mod

### ISSUE THREAD

**Issue by sirben99** [McJty/TheOneProbe#452]
Forge: 36.1.0
Minecraft: 1.16.5
Singeplayer or server:  Both
GuardVillagers mod version: 1.2.0
TheOneProbe version: 3.0.7

Hey!

I noticed that when using The One Probe and GuardVillagers, my console was being spammed with preparing for crash report errors when looking/trying to right click a GuardVillager. Issue has been tested with only GuardVillagers and The One Probe.

Heres the latestl.log: 
[latest.log](https://github.com/seymourimadeit/guardvillagers/files/6203898/latest.log)

**Comment by McJty** [comment]
Hmm I need to see the crashlog. Probably in another log file

**Comment by sirben99** [comment]
> Hmm I need to see the crashlog. Probably in another log file

It doesent produce a crash file, just spams the error over and over again non stop, as seen in the latest.log. Thats whats weird about it, since it doesent accualy produce any crashes.

**Comment by sirben99** [comment]
I you need more info/files please let me know. I looked at the other logs/files and i coudnt find any more info than the spam. I assume it would be best that VillagerGuards dev gives his side of the issue.

I noticed that the log spam is similar to #419, but it could be a seperate issue.

**Comment by sirben99** [comment]
Hey!

Just to update this issues, the issue is fixed on the GuardVillagers devs side, and is no longer a problem. Thank you for ur time! Ill close this issue now, since its solved.

Ben
