### ISSUE TITLE
can't install the one probe

### ISSUE THREAD

**Issue by JonasLeo2510** [McJty/TheOneProbe#455]
After downloading file, I can't open it and install it. I've tried a lot things but it doesn't work. Could someone help?

**Comment by McJty** [comment]
What version are you trying to install? What version of forge? What are you doing exactly?

**Comment by JonasLeo2510** [comment]
I'm trying to install the 1.16 version and everytime after installing, I can't open to Jar file, to install it. And I've deleted the file and downloaded it a second time but it also didn't work. After this I've tried to open the file with the cmd in Windows but then there is an error message "can't find the file". And now I don't now, what I could do :(

**Comment by McJty** [comment]
What version of forge are you using?

**Comment by JonasLeo2510** [comment]
Uh sorry I don‘t know what you mean. Should I install forge to use this? I’ve downloaded the one probe on curseforge and there was no info for that 😅. I tried to install it with Java... was this wrong?

**Comment by McJty** [comment]
Yes, The One Probe (and many other mods) require Forge to run.  Check http://files.minecraftforge.net/

**Comment by JonasLeo2510** [comment]
Ok now I've installed forge 1.16.5. But I still can't open the theOneProbe file

**Comment by McJty** [comment]
Run Minecraft with forge. That should create a 'mods' folder. Then you put the one probe 'jar' file in

**Comment by JonasLeo2510** [comment]
Ok. I've done this, should I restart Minecraft after this?

**Comment by JonasLeo2510** [comment]
I've restarted it. Now it works! Thank you very much ! :)

An other question. Could I use Optifine too when I'm using forge?

**Comment by McJty** [comment]
No that's not required

**Comment by JonasLeo2510** [comment]
Ok thanks for helping
