### ISSUE TITLE
Null error

### ISSUE THREAD

**Issue by runescapejon** [McJty/TheOneProbe#459]
Hello, I'm my version is `1.12-1.4.28` and I am using TheOneProbe with CustomPlayerModel (link is below). It's a mod design to modify player models. When I look at a player having this it gives a null error. Is there a way to fix it or blacklist the entity?

Error: https://pastebin.com/raw/ugn3dVQy
Mod: https://www.curseforge.com/minecraft/mc-mods/custom-player-model-cpm

**Comment by McJty** [comment]
The crash actually happens in CustomPlayerModel so I would report to them
first

**Comment by runescapejon** [comment]
Unfortunately, they are not supporting 1.12 anymore that is why I have asked a possible way to blacklist the entity?

**Comment by McJty** [comment]
Well same here I'm afraid. I'm not sure if the 1.12 version already had the
blacklist option. I recommend checking the configs to see if you can find
it there.

**Comment by runescapejon** [comment]
It doesn't have it :/

**Comment by McJty** [comment]
Then I'm afraid you'll have to either remove The One Probe or else
CustomPlayerModel

**Comment by runescapejon** [comment]
It just displays weird colors to users' screens if they are attacked.  However, thank you for your time.
