### ISSUE TITLE
Probe is gone 

### ISSUE THREAD

**Issue by Amazedpnather6** [McJty/TheOneProbe#460]
So I was messing with my controls and I turned off the block identifier and now I can't turn it off

**Comment by McJty** [comment]
I need a LOT more information then this. What did you do exactly? Also what version?

**Comment by Amazedpnather6** [comment]
I changed the controls to a different key and I toggled it off and now I can't toggle it on. 
Forge 1.16.5

**Comment by McJty** [comment]
Change the control back to the original key and press it again? It's really just a toggle. If you assign it to a key that works you can just turn it on and off at will

**Comment by Amazedpnather6** [comment]
That's what I did and it still doesn't work

**Comment by Amazedpnather6** [comment]
Do you have to like hold the keys or just press it

**Comment by McJty** [comment]
Just press it once. What key did you assign it to? BTW. You didn't tell me the version yet

**Comment by Amazedpnather6** [comment]
I said 1.16.5 and alt left and alt right

**Comment by McJty** [comment]
Ah don't use those keys. Use a regular key like 'l', 'o', 'p', ... the modifier keys can't be used for this

**Comment by Amazedpnather6** [comment]
still doesn't work

**Comment by Amazedpnather6** [comment]
which one of the 2 do I need to press

**Comment by McJty** [comment]
What key did you use? And what did you mean by 2?

**Comment by Amazedpnather6** [comment]
I used i for toggle liquid view 
and m for visibility toggle

**Comment by McJty** [comment]
And you made sure there are no conflicts? 'm' is the key to press for visibility toggle. Perhaps show a screenshot of your keyboard control configuration

**Comment by Amazedpnather6** [comment]
![2021-04-23_05 10 29](https://user-images.githubusercontent.com/83051062/115848997-75e09e00-a3f2-11eb-9f59-7d2c7d679a12.png)

**Comment by McJty** [comment]
yes. Pressing 'm' should work. If it doesn't then I don't know

**Comment by Amazedpnather6** [comment]
but which one do I need to press the first one or the second one

**Comment by McJty** [comment]
Read my previous comment where I tell you which key to press

**Comment by Amazedpnather6** [comment]
ok just making sure
