### ISSUE TITLE
Custom Damage Bars not supported

### ISSUE THREAD

**Issue by Speiger** [McJty/TheOneProbe#461]
Forge added in 1.14.4 custom damage bar colors and i noticed they are not supported.

Would you consider adding support for that?

Also since you are ignoring basically issues or don't have enough time for maintaining the mod (since a lot of 1.12 bugs are still in the 1.14-1.16 version) would you consider allowing other people to maintain it for you?

Because one probe is much much better then the other options, just the bugs within the mod just almost kill it.
(I already rewrote in my fixes that i use around 50% of your components and added so much more flexibility, like padding etc)

@McJty would you consider that or allow a fork release?

**Comment by McJty** [comment]
What are custom damage bar colors? Any pointers to where I can find that and what it looks like?

**Comment by Speiger** [comment]
```java
	@Override
	public int getRGBDurabilityForDisplay(ItemStack stack)
	{
		return -1 //custom RGB value for the durability
	}
```
This is not supported Look up item rendering you will find it pretty quickly

**Comment by Speiger** [comment]
Fixed
