### ISSUE TITLE
Tank color not working?

### ISSUE THREAD

**Issue by McJty** [McJty/TheOneProbe#481]
For Speiger, I was expecting this to show the color of lava?

![2021-05-13_07 42 21](https://user-images.githubusercontent.com/8188472/118083387-19541b80-b3bf-11eb-867e-c9e0aa599324.png)

**Comment by Speiger** [comment]
@McJty what is the fluid color for lava? I bet its -1 (white)

**Comment by Speiger** [comment]
Oh i have not replaced the default tank component i thought the patch showed that.

**Comment by Speiger** [comment]
@McJty dont forget to close this once you tested it.
