### ISSUE TITLE
TOP gui doesn't show.

### ISSUE THREAD

**Issue by KristjanKr** [McJty/TheOneProbe#49]
TOP Gui doesn't show when holding the probe or wearing helmet.

Some pictures that should help:

http://imgur.com/a/6rA76
http://imgur.com/GlOrFps
wearing helmet(pressing visibility button) changes nothing.

 Extra info:
Only overlay mod I have is Mapwriter, which shows minimap at top right corner. Anything else isn't active. 
I do have topaddons installed too.

Here is my modlist: https://paste.ee/p/3HBUn

And also latest client log if it should help anyhow:  http://paste.ee/p/ZnOOH

**Comment by McJty** [comment]
It is likely this is fixed in latest release. Can you check this? Reopen this ticket if it is still not working. Also make sure you didn't accidently hide the probe tooltip
