### ISSUE TITLE
it happen after updated some mods 

### ISSUE THREAD

**Issue by bbadrider** [McJty/TheOneProbe#497]
[crash-2021-07-14_18.58.48-fml.txt](https://github.com/McJtyMods/TheOneProbe/files/6815822/crash-2021-07-14_18.58.48-fml.txt)

**Comment by joklbash** [comment]
Having the same crash. For me, it was an update to Entangled from 1.3.4 to 1.3.5.

**Comment by bbadrider** [comment]
> Having the same crash. For me, it was an update to Entangled from 1.3.4 to 1.3.5.

does revert it back work for you? its not for me

**Comment by joklbash** [comment]
Yes, reverting back down a version of Entangled solved it for me. In your crash report, it says what happened on line 41. I didn't look at the code to see which side it happened on. I'm assuming Entangled didn't open their TOP support as expected.

java.lang.ClassCastException: com.supermartijn642.entangled.integration.TheOneProbePlugin cannot be cast to java.util.function.Function

**Comment by bbadrider** [comment]
> Yes, reverting back down a version of Entangled solved it for me. In your crash report, it says what happened on line 41. I didn't look at the code to see which side it happened on. I'm assuming Entangled didn't open their TOP support as expected.
> 
> java.lang.ClassCastException: com.supermartijn642.entangled.integration.TheOneProbePlugin cannot be cast to java.util.function.Function

its fix now i just didn't delete the latest  version.
thankyou!

**Comment by joklbash** [comment]
I put a crash report on Entangled's site.
https://github.com/SuperMartijn642/Entangled1.12/issues/23#issue-944405825
