### ISSUE TITLE
Console Spam when looking at chisel and bits and beetroot plants

### ISSUE THREAD

**Issue by TheClaus** [McJty/TheOneProbe#5]
I am not sure about the beetroot.  It won't show growth.  All other vanilla plants are fine.  When I look at growth it errors and according to the log it errors because of chisel and bits.  If I look at chisel and bits things it errors out also.

Could I exclude chisel and bits from the probe so it won't show it?

Here is the [log](http://pastebin.com/ih5vGdzV)

**Comment by McJty** [comment]
Not sure about beetroot but the Chisel & Bits thing is as far as I can see a bug in Chisel & Bits. Their implementation of getPickBlock() doesn't seem to work server-side.

**Comment by TheClaus** [comment]
Is there a way to tell TheOneProbe to not show anything from Chisel and Bits?

**Comment by McJty** [comment]
I'm going to talk to the author of Chisel & bits about this and try to get this bug fixed. For the moment you cannot avoid it doing this I'm afraid

**Comment by TheClaus** [comment]
Here is a log without Chisel & Bits.  Just looking at the growth of beetroots.

http://pastebin.com/wsDJsJvL

**Comment by McJty** [comment]
Ok. I will check that out

**Comment by McJty** [comment]
The beetroot problem will be fixed next release
