### ISSUE TITLE
Config Option Suggestion: TOP Item required for "bonus" information

### ISSUE THREAD

**Issue by BBoldt** [McJty/TheOneProbe#50]
I'm getting a lot of complaints that waila is not in my pack and that TOP sucks because it does not show by default. I don't have it showing by default as I would like to get people to use the TOP items and mod integrations. I don't want to render them useless, so here is my idea:

Without the item, TOP displays only very basic information. Like the block's name and picture. Then, when you craft the item you unlock all the "bonus" information that you need to sneak to find out. Such as the harvest level, rf level, etc.

That way, the items aren't useless, and people used to waila not needing an item are happy.

**Comment by McJty** [comment]
Implemented next release
