### ISSUE TITLE
[1.17] NewRegistry

### ISSUE THREAD

**Issue by Speiger** [McJty/TheOneProbe#504]
https://github.com/McJtyMods/TheOneProbe/blob/1.17/src/main/java/mcjty/theoneprobe/apiimpl/TheOneProbeImp.java#L77

Seriously Please drop the "Integer" id System that is autogenerated. This causes the bug continuously, you didnt fix it.
I gave you a Proper example with #472
And yet you are still breaking the implementation.

register(ResourceLocation, Class<IElement>, Function<FriendlyByteBuf, IElement>).

Then your IElement does not need a getId function because you get it based on the class. Since there is no way to duplicate classes + paths you cant have any duplication. Yet you are still using Integer IDs.

Do i need to make a patch so it is properly implemented?

**Comment by McJty** [comment]
Those integers you are talking about pure internal. They are not exposed so there is no problem. I'm not a fan of using classes for anything so I prefer the solution that I used

**Comment by Speiger** [comment]
If you are not a fan of classes then remove the integers and use resourcelocations.
Still the class thing is much saver and simpler. It reduces the I have to provide ID from twice to just once and reduces messups because there is only 1 way to do it and the compiler throws errors if you make a mistake. A resourceLocation if that has a typo or someone overrides it does not cause compiling errors. It just crashes the game or causes freezes like you got reported.
