### ISSUE TITLE
Array Configs are broken [1.14-1.16]

### ISSUE THREAD

**Issue by Speiger** [McJty/TheOneProbe#505]
showContentsWithoutSneaking = ["storagedrawers:basicdrawers", "storagedrawersextra:extra_drawers"]

When you try to expand this or any other array config it automatically resets the config because the implementation that is used is wrong.
It use: Define instead of defineList. Since you use define forge checks if the entries are "lists/collections" not "strings" and since that is impossible it will automatically reset the configs. That means any array based config is not a config but Here is your setting live with it.

How to fix it: just change array based configs from define to defineList

**Comment by McJty** [comment]
Should be fixed for 1.16 and 1.17 in the next release

**Comment by Speiger** [comment]
Thanks for the quick patch. I am going to give feedback soon.
