### ISSUE TITLE
Mod does not work in 1.17

### ISSUE THREAD

**Issue by UlIlI** [McJty/TheOneProbe#507]
Hi. I have been having a serious problem that this mod does not work as intended on the latest version of the mod. (And don't even try to say to me: Are you equipping the Probe in your hand/off-hand, I tried that, it still wouldn't work) This is just a request to update your mod and fix it.

**Comment by McJty** [comment]
You will have to be more specific. People are using it without problems so the mod does work. What version of Forge are you using? Can you give me the logs? I need more information because you're the only one so far who reported this problem so I have nothing to debug with

**Comment by McJty** [comment]
Also are you using the mod on a server?

**Comment by UlIlI** [comment]
1. I am not using a server or connected to LAN
2. Forge version 1.17.1-forge-37.0.34 
here is the logs from today: [latest.log](https://github.com/McJtyMods/TheOneProbe/files/6988969/latest.log)
Edit: Also forgot that I am using the latest version of the mod (the one from August 7th)

**Comment by McJty** [comment]
Very weird. The only thing that I can think of is that you accidently pressed the hotkey to disable the probe. Check your key controls to see what key that is assigned too. If it's not assign then do that and try pressing it to see if that helps

**Comment by UlIlI** [comment]
The problem is that no information to the block I am looking at (not even a chest and it's content). The UI is 100% visible.

**Comment by McJty** [comment]
Ah wait. That's something else. First can you show me a screenshot?

**Comment by UlIlI** [comment]
Contents of the chest:
![2021-08-16_14 01 29](https://user-images.githubusercontent.com/85249301/129609041-5eec1c78-4ddc-45f4-a516-e48c7e04ae5c.png)
Me looking at the same chest with the probe in my hand
![2021-08-16_14 01 55](https://user-images.githubusercontent.com/85249301/129609138-b86dce4e-6b9c-41a0-9fed-c023996d12a1.png)
It just gives me an error that says: theoneprobe:default.

**Comment by McJty** [comment]
Can you show me the logs? (debug.log and latest.log)

**Comment by McJty** [comment]
I have a suspicion that it might be a bad mod which is causing this and I also think I know why. But I need to see logs for that

**Comment by McJty** [comment]
I figured it out. Seems latest forge breaks TOP. I'll fix this

**Comment by McJty** [comment]
It's fixed
