### ISSUE TITLE
[1.10.2] [Bug]  Guess this is a bug

### ISSUE THREAD

**Issue by Dijkstra1** [McJty/TheOneProbe#51]
Guess this is a bug this is a bug do not how/why it happening,
[TOP.zip](https://github.com/McJty/TheOneProbe/files/458698/TOP.zip)
This is a RFTools Dim, if that makes any difference

**Comment by McJty** [comment]
Can you enable liquids in WAILA (I think it is '1' hotkey on numpad) and see what WAILA says?

**Comment by Dijkstra1** [comment]
I turned liquids early because I was taking damage and getting slowest in "water" it never got turn back off so liquids are on in the video, when look liquids in WAILA it says unknown, but in this case it looks like WAILA is getting right.

**Comment by McJty** [comment]
Are you on a server? If so this was most likely fixed in the latest version of RFTools Dimensions (4.30beta50). Can you check that? Reopen this if the bug still occurs
