### ISSUE TITLE
[1.17] Mob heath not being displayed on GUI

### ISSUE THREAD

**Issue by ffuentesm** [McJty/TheOneProbe#513]
I am using the 1.17 version and in the config, I am setting so that it shows the mob health, but the GUI does not show it. 
The mod version is: TheOneProbe 1.17-4.0.2

![image](https://user-images.githubusercontent.com/44974827/132139222-4a4e8c9a-3b97-47ac-8928-cc66787338ca.png)

**Comment by markygnlg** [comment]
i had the same problem until I replaced the numbers with words, ie.:

#Show mob health (0 = not, 1 = always, 2 = sneak)
showMobHealth = "1"

changed to:

showMobHealth = "NORMAL"

I had the same problem with the setting:

#Show horse stats setting (0 = not, 1 = always, 2 = sneak)
showHorseStatSetting = "1"

changed to

showHorseStatSetting = "EXTENDED" (for crouch)
showHorseStatSetting = "NORMAL"  (for always)

... so I'd suggest trying "EXTENDED" or  "NORMAL" for settings that ask for a number but fail to enable/disable an option.
