### ISSUE TITLE
1.12-1.4.28 Error executing task.

### ISSUE THREAD

**Issue by ktole1999** [McJty/TheOneProbe#516]
This happens on server only. SSP works just fine. once the crash occurs i have to nbt edit the block out. as soon as you look at the item it causes the client crash. no errors on the server. The item is the rftools sequencer.

[crash-2021-09-16_16.04.09-client.txt](https://github.com/McJtyMods/TheOneProbe/files/7186334/crash-2021-09-16_16.04.09-client.txt)

**Comment by McJty** [comment]
Can't do much with this I'm afraid. First you're the first reporting this and the sequencer and TOP are used a lot in 1.12. Secondly the crash you gave to me is not even in one of my mods and lastly I no longer develop on 1.12.

Very weird crash though. Maybe the sequencer got corrupted somehow?

**Comment by ktole1999** [comment]
no worries at all. I can try and redownwload the mod and see if that fixes otherwise i will find a work around. Love all your mods.
