### ISSUE TITLE
does mod work w/ waila?

### ISSUE THREAD

**Issue by HexaboardCanSuckMyNuts** [McJty/TheOneProbe#521]
i want to know

**Comment by McJty** [comment]
You want to know what? I don't understand the question. Both are different mods which roughly do the same thing

**Comment by HexaboardCanSuckMyNuts** [comment]
I mean't that if this is a HWYLA addon as the description in curseforge didn't leave it clear for me, sorry
also i meant hwyla, i constantly confuse them both

**Comment by McJty** [comment]
This is not an addon. It's a standalone mod independent of either of those HWYLA, WAILA, whatever

**Comment by HexaboardCanSuckMyNuts** [comment]
Oh okay, thank you!
