### ISSUE TITLE
Bug on the spawners

### ISSUE THREAD

**Issue by Geogeo59** [McJty/TheOneProbe#533]
![2022-01-13_14 45 55](https://user-images.githubusercontent.com/44133645/149528449-61aec2b5-8a4c-43d5-95c7-3fa0bbdfbd65.png)

Hello,

I do not know if it is normal but when we pass the mouse on a spawner it writes error (example in photo)

Thank you in advance.

**Comment by McJty** [comment]
Version please

**Comment by Geogeo59** [comment]
1.18- 5.0.2

**Comment by McJty** [comment]
Ok, thanks. I will check it out

**Comment by Geogeo59** [comment]
Thank you very much

**Comment by McJty** [comment]
Fixed in the upcoming release
