### ISSUE TITLE
Crash when removing top from mods folder. 1.18.1

### ISSUE THREAD

**Issue by ZeldasWetDream** [McJty/TheOneProbe#540]
I wanted to remove TOP from my modded play through top test other alternatives. Doing so lead to repeated "crashes" where the game would finish booting up but all text would be squares and all my resource packs would be removed.

[crash-2022-02-08_01.30.11-client.txt](https://github.com/McJtyMods/TheOneProbe/files/8021539/crash-2022-02-08_01.30.11-client.txt)

**Comment by McJty** [comment]
It's crashing in dungeonsmod. It probably does something weird. Report to them. I can't fix bugs in a mod that isn't present anymore :-)

**Comment by ZeldasWetDream** [comment]
Thanks for letting me know. The mod is cool and all but it is kinda invasive with how many dungeons it spawns, but it will go put the report over there as well.
