### ISSUE TITLE
crash on startup. early loading fabric 1.18.2

### ISSUE THREAD

**Issue by TheRanker** [McJty/TheOneProbe#547]
having a crash with the one probe fabric 1.18 5.1.0 
minecraft 1.18.2
fabric 0.13.3
i have a modpack im developing and i just switched to this mod in the 1.18.2 version 
ended up getting crash 
https://pastebin.ubuntu.com/p/YmFQ9X7Dyj/

tested with vanilla fabric and the one probe and works as intended.  so its a mod interaction at the cause of it.

**Comment by McJty** [comment]
The One Probe is a forge mod. Doesn't work on Fabric
