### ISSUE TITLE
[1.16.5] Crash on startup when adding mod Resynth

### ISSUE THREAD

**Issue by ghost** [McJty/TheOneProbe#549]
Forge version: 36.2.33
Minecraft version: 1.16.5
TheOneProbe version: 3.1.5
Resynth version: 6.2.0

Hi, I wanted to try out mod Resynth but after adding that mod, my game crashes on startup, crashlog bellow:

https://pastebin.com/RW662AL4

**Comment by McJty** [comment]
Report with them. They are using the API wrong

**Comment by ghost** [comment]
Ok, thanks a lot :)
