### ISSUE TITLE
[1.10.2] Crash on post-init with EnderIO 3.0.1.110 installed

### ISSUE THREAD

**Issue by Gepett0** [McJty/TheOneProbe#55]
Issue Description:

With latest EnderIo-beta and latest The One Probe MC crashes at start.
Maybe a TOP problem? Did x-post @EnderIO.

What happens:

MC crashes while post-initializing

What you expected to happen:

Playing as normal

Steps to reproduce:

Install Forge
Install Ender IO + EnderCore
Install TOP
Play (at least try)
Crash on startup
Affected Versions (Do not use "latest"):

EnderIO: 3.0.1.110
EnderCore: 0.4.1.55
Minecraft: 1.10.2
Forge: 2089+ (tested on 2089 and 2092)
Your most recent log file where the issue was present:

http://pastebin.com/86ZA40i8

**Comment by mkleiman312** [comment]
Confirming same crash.  Downgrading EnderIO  resolves conflict.

The One Probe: 1.10.1.1.1
McJtyLib: 1.10.2.1.1
EnderIO: 3.0.1.110
EnderCore: 0.4.1.55
Minecraft: 1.10.2
Forge: 2092

http://pastebin.com/FM0gpHAp

**Comment by McJty** [comment]
Workaround added for next release
