### ISSUE TITLE
FPS with TOP and Taterzen Mod

### ISSUE THREAD

**Issue by winnetrie83** [McJty/TheOneProbe#552]
**Minecraft Version:** 1.18.2
**Forge Version:**  40.0.54
**The One Probe Version:** theoneprobe-1.18-5.1.0.jar
**Taterzen:** taterzens-1.8.6-forge.jar

- Create a NPC
- Look at it and experience FPS drop ( mine went from a steady 60 FPS to 15-20 FPS
[latest.log](https://github.com/McJtyMods/TheOneProbe/files/8507791/latest.log)
)
The latest.log file was to large for pastebin, so i added the file here. Basicly it is the same error over and over again.
This is a log file while 1 min in game (more or less)

**Comment by McJty** [comment]
Those are bugs in the taterzen mod:

java.lang.ClassCastException: class net.minecraft.client.multiplayer.ClientChunkCache cannot be cast to class net.minecraft.server.level.ServerChunkCache (net.minecraft.client.multiplayer.ClientChunkCache and net.minecraft.server.level.ServerChunkCache are in module minecraft@1.18.2 of loader 'TRANSFORMER' @623ebac7)
	at org.samo_lego.taterzens.npc.TaterzenNPC.sendProfileUpdates(TaterzenNPC.java:567) ~[taterzens-1.8.6-forge.jar%2352!/:?]
