### ISSUE TITLE
Color Config Formatting Issue

### ISSUE THREAD

**Issue by Jengateng** [McJty/TheOneProbe#56]
I'm having nothing but trouble with color formatting in your mod. Before I seemed to be able to just take a normal 6-digit hex and add two digits on the end for transparency (using this [table](http://stackoverflow.com/questions/15852122/hex-transparency-in-colors/17239853#17239853) ), however in the latest version, when using the mod options menu, colors seem to defy all logic.

For example ff000000 in your mod would be pure black with no transparency.
However, I would rather expect it to be pure red with no transparency.

The latter seemed to be the case before, and while not conforming to minecraft color in general, it conformed to normal hex color logic.

However, using this [link](https://developer.android.com/reference/android/graphics/Color.html) I was able to use these android ints successfully as colors in your mod options menu.

Is my complete lack of knowledge regarding different color spaces getting in the way, or did I stumble upon an actual bug? Or did you just overhaul how colors work in your mod? Or am I just an insane person? (Posted to your curse page as well.)

**Comment by McJty** [comment]
FF000000 is supposed to be pure black with no transparency. The code is: AARRGGBB with AA alpha, RR red, GG green, BB blue. So FF000000 is no transparency and 0 for R,G,B and that's black.
