### ISSUE TITLE
renderBlacklist not working

### ISSUE THREAD

**Issue by MainsaRZ** [McJty/TheOneProbe#568]
In renderBlacklist I try to put [minecraft:painting] and it shows that it is an invalid value
Is it a bug or am I doing something wrong?
version: theoneprobe-1.18-5.1.0

**Comment by McJty** [comment]
Show me exactly how you put it in the config

**Comment by McJty** [comment]
It seems like you are missing quotes

**Comment by MainsaRZ** [comment]
> It seems like you are missing quotes
apparently that was it.
Thank
