### ISSUE TITLE
Server Crash (Right now Indev but forge might change this)

### ISSUE THREAD

**Issue by Speiger** [McJty/TheOneProbe#569]
Since IC2C has a one probe plugin and i try to test it on servers too this happened to me.

```
	Index: 2
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4124/0x0000000801625548@635b5740
		2: ASM: class mcjty.theoneprobe.config.ConfigReload onLoad(Lnet/minecraftforge/fml/event/config/ModConfigEvent$Loading;)V

java.lang.IllegalStateException: Cannot get config value before config is loaded.
This error is currently only thrown in the development environment, to avoid breaking published mods.
In a future version, this will also throw in the production environment
```

**Comment by Speiger** [comment]
How to reproduce: Try to run your mod on a dedicated server indev and it will automatically happen...

**Comment by McJty** [comment]
I don't understand this error though. The error happens in this routine:

```
    private static <T> T getOrDefault(ForgeConfigSpec spec, ConfigValue<T> config) {
        if (spec.isLoaded()) {
            return config.get();
        } else {
            return config.getDefault();
        }
    }

```

And in the debugger I could so that spec.isLoaded() is returning true. So the config should be loaded. But still config.get() throws that error. Not sure what to do about that to be honest

**Comment by McJty** [comment]
nm, found it

**Comment by McJty** [comment]
Fixed on maven

**Comment by Speiger** [comment]
@McJty would be nice if this would be published to CF since i am using CurseMaven.

**Comment by McJty** [comment]
Ah ok. I can do that later. But why use CurseMaven though?

**Comment by Speiger** [comment]
Because it is 1 unified maven that i can get any mod for any released version from even if the dev shuts down his own stuff
And it cleans up the code if you have a lot of mods installed for support.
(Right now we have 4 1.19 but in 1.16 it was like 8 mods and 1.12 it was a lot more then that and 1.7.10 was even more)
Also the packaging is more consistent between all mods.
implementation fg.deobf("curse.maven:the-one-probe-245211:3838419") (curse.maven:ModUrlName-ProjectID:FileID)

**Comment by Speiger** [comment]
@McJty would have been nice if you would have made 2 versions one with Forge 63 and forge 64,
because right now I cant use the latest build because JEI/Curio still need to update. Ugh....
I fixed the problem temp on my side by setting forges server to production in my IDE.

Thanks for fixing it anyways.

**Comment by McJty** [comment]
Ah right didn't think of that. But anyway, you can still use the right version of TOP from my maven. That should be an easy (temporary?) fix for you

**Comment by Speiger** [comment]
Nah I already have a fix that works as Temp fix. Just setting the forge flag of production mode on server and then just use the broken version.
I can update to the new version maybe in a week or two when most of the mods have updated because I have a beta running and I can't just kill like 5-10 modpacks that are made just for testing.

And another maven in this case is much more annoying then setting a runtime configuration flag that i don't need to fix afterwards either.
