### ISSUE TITLE
theoneprobe config just got changed on the file system! fatal error

### ISSUE THREAD

**Issue by lordudi** [McJty/TheOneProbe#572]
in the game output log it says: mcjty.theoneprobe.TheOneProbe
Thread-1
theoneprobe config just got changed on the file system! in the fatal error level

**Comment by McJty** [comment]
yes it says that all the time. Not a problem

**Comment by lordudi** [comment]
> yes it says that all the time. Not a problem

ok thanks and sorry for bothering
