### ISSUE TITLE
Too Much/Duplicate Information Displayed with Storage Drawers

### ISSUE THREAD

**Issue by JadeKaiser** [McJty/TheOneProbe#578]
I play multiple different modpacks. This hasn't been a problem in older ones, or the older versions of ones that I've recently updated, but the newest versions of The One Probe seem to give far, FAR too much information when looking at Storage Drawers blocks. Or more accurately, they double up on the information, displaying it in two different formats at the same time, taking up way too much of the screen and making it very hard to see what I'm doing. See screenshot:
![Screenshot (85)](https://user-images.githubusercontent.com/83559853/186309886-9b787375-0feb-4bf1-940e-4fdd21b4ffc9.png)
And this screenshot was taken while standing a bit farther away from the drawers than usual, with a lowered GUI size.
I've tried checking the configs and using The One Probe Readme item, but it doesn't seem to be something that I can change in the settings.

**Comment by DrManganese** [comment]
The top bit comes from StorageDrawers itself, the info in the blue box is added by TOP Addons.

It should be possible to exclude the TOP Addons information by adding "topaddons:storagedrawers" to the list of "excluded_providers" in the one probe's config.

**Comment by JadeKaiser** [comment]
> The top bit comes from StorageDrawers itself, the info in the blue box is added by TOP Addons.
> 
> It should be possible to exclude the TOP Addons information by adding "topaddons:storagedrawers" to the list of "excluded_providers" in the one probe's config.

Thanks, I'll give that a try.

**Comment by McJty** [comment]
Anyway, not a bug in TOP itself. Possibly talk to the TOPAddons author

**Comment by JadeKaiser** [comment]
I'm actually not finding an "excluded_providers" line anywhere in either theoneprobe-client.toml or theoneprobe-common.toml, is there a different file I should be looking for? I tried using ctrl+f in case I missed it, no dice.

**Comment by JadeKaiser** [comment]
Though I suppose I can change the settings in topaddons' own config file.
