### ISSUE TITLE
Design Flaw: PacketGenerateLag

### ISSUE THREAD

**Issue by calvinbalke13** [McJty/TheOneProbe#58]
PacketGenerateLag should probably not exist or should require permissions on the server to use it.  Currently, anybody is able to use PacketGenerateLag to lag or completely freeze a Minecraft server.

**Comment by McJty** [comment]
You can only use this from within a mod. And if you can make/add a mod on a server then you can just implement your own lag generating package

**Comment by calvinbalke13** [comment]
Any client is able to use this packet with a custom mod.  The custom mod doesn't have to be on the server to cause lag.  If TheOneProbe is on a server, and somebody creates a client-side mod to send 500 GenerateLag packets, the server will freeze for 1000 seconds.

**Comment by McJty** [comment]
If you have a custom mod then there are thousands of other ways to create a lot of lag on a server

**Comment by McJty** [comment]
Removed the class since it was only used for testing anyway
