### ISSUE TITLE
1.19.2 Builds not on Maven

### ISSUE THREAD

**Issue by cech12** [McJty/TheOneProbe#582]
Unfortunately, the builds for the 1.19.2 TOP versions (1.19-6.2.1 & 1.19-6.2.2) are not available in your Maven repository: https://maven.k-4u.nl/mcjty/theoneprobe/theoneprobe/

I would like to add support for some of my 1.19.2 mods, but the version 1.19-6.2.0 cannot be started in MC 1.19.2

It would be great if you can add the actual version to your Maven repository :)

**Comment by McJty** [comment]
I'm using that TOP maven myself for my own 1.19.2 mods. It works fine

**Comment by cech12** [comment]
The Maven works fine, yes, but the actual versions 1.19-6.2.1 and 1.19-6.2.2 are missing. Please click on the link and search for the versions. They are not available.

**Comment by McJty** [comment]
I know but they shouldn't be needed. 6.2.0 works just fine on 1.19.2

**Comment by cech12** [comment]
I got an error message that a class was not found. After some research I found out, that I was on Forge 41.0.62 and some breaking changes were made in 41.0.94. 
After bumbing Forge to a newer version, your mod works fine. :) Thanks for your time!
