### ISSUE TITLE
No fluid amount info on some mods example "open blocks fluid tank".

### ISSUE THREAD

**Issue by Thelastlion1** [McJty/TheOneProbe#583]
Why is there no fluid information for some mods? Instead HWYLA does show it but i want to use The One Probe and not HWYLA. Version 1.12-1.4.28.

**Comment by McJty** [comment]
What mods? Can you be more specific?

**Comment by Thelastlion1** [comment]
I fixed it i had a config file modified so i had to delete it and re-launch Minecraft, thank you anyways. I am really enjoying this mod keep it up!
