### ISSUE TITLE
Newest applied energistics 2 1.18.2 incompatibility?

### ISSUE THREAD

**Issue by FearAK** [McJty/TheOneProbe#585]
So after the new ae2 update theoneprobe doesn't allow me to open minecraft anymore and gives me this crashlog.
[crash-2022-10-05_16.12.46-fml.txt](https://github.com/McJtyMods/TheOneProbe/files/9716344/crash-2022-10-05_16.12.46-fml.txt)

**Comment by McJty** [comment]
Why are you reporting this here? Report to ae2

**Comment by FearAK** [comment]
Jeez.. sorry I guess. I don't always know who to report to, tought it might be something that had to be fixed on your side.. guess I was wrong.

**Comment by McJty** [comment]
Well technically that could be the case but if it happened through an update of ae the logical first thing to check is that mod
