### ISSUE TITLE
[1.16.5] crash when I look at a block with a probe, seems to have to do with the overlay

### ISSUE THREAD

**Issue by veccyboi** [McJty/TheOneProbe#590]
**whenever i look at a block with the probe, the game crashes.**
**technical info**
my mods folder: 
![image](https://user-images.githubusercontent.com/85643556/198886841-f2870a20-3d4a-468e-a328-2471ec66905f.png)
game version: 1.16.5
forge version:36.2.2
mod version: 1.16-3.1.7
**more specifics of what happened:**
the game loads up fine with the mod installed. I loaded up a world and (in creative mode) obtained a helmet with probe. however, as soon as I put it on, the game crashed: [crash-2022-10-30_10.06.19-client.txt](https://github.com/McJtyMods/TheOneProbe/files/9896184/crash-2022-10-30_10.06.19-client.txt)
i removed the mod and reinstalled it, and the game loaded fine, but as soon as i tried to load the same world as mentioned above, the game crashed again with what looked like the exact same error message and crash report, confirming that it most likely is something to do with this mod
I'm not sure if this is a mod incompatibility since the crash report doesn't suggest that and i don't have the time to check all my mods.
removing the mod obviously fixes the issue

**Comment by McJty** [comment]
Update forge
