### ISSUE TITLE
Mod not being loaded at all

### ISSUE THREAD

**Issue by ghost** [McJty/TheOneProbe#599]
So the mod doesnt get loaded, doesnt show up in the mod menu, nothing. im playing on 1.18.2 on fabric and the version is theoneprobe-1.18-5.1.2.

All the other mods work and i updated java and all that. It is also on the server, atleast i hope its also loaded on the server, but it is definetly in the mod folder.

**Comment by ghost** [comment]
now checking, it also doesnt get loaded in the server either.

**Comment by McJty** [comment]
The One Probe is a forge mod
