### ISSUE TITLE
[1.10.2] Crash when looking at a Mekanism Robit

### ISSUE THREAD

**Issue by b0bst3r** [McJty/TheOneProbe#60]
http://pastebin.com/kYNw0EpE

Mekanism-1.10.2-9.2.0.292
theoneprobe-1.10-1.1.2
topaddons-1.10.2-0.7.0

**Comment by McJty** [comment]
Report to them. That's most likely a problem at their side

**Comment by b0bst3r** [comment]
ok no chance of this being fixed then :/ mekanism updates are like non-existant.

**Comment by McJty** [comment]
Would like to keep this open. If they can't fix it I can perhaps add protection for it on my end

**Comment by McJty** [comment]
Added protection for bad behaving mods so this does not cause crashes. The error will be put in the log
