### ISSUE TITLE
Shows mod id instead of mod name with GroovyScript Custom Items

### ISSUE THREAD

**Issue by IntegerLimit** [McJty/TheOneProbe#606]
This is more of a question, than a bug report. See the title for the issue.

I have fixed this issue, but it requires GroovyScript as a dep. What should I do? I could use a mod to patch it in, or would you rather me PR it, or do you want me to make it as a separate mod on CurseForge?

**Comment by McJty** [comment]
What exactly? Can you give a bit more details?

**Comment by IntegerLimit** [comment]
Because custom items created with GroovyScript use a different way of storing mod names, it is inaccessible without reading it from the mod itself. I can give you the source code I used to fix it tomorrow, but I pretty much just added a test in Tools.java, where it would see if the registry name's domain of the itemStack is equal to the mod id set in GroovyScript.

This is all due to the fact that GroovyScript allows you to define a custom mod id and mod name for your custom items.

**Comment by McJty** [comment]
You can submit a PR but no guarantee I will merge it. Depends

**Comment by IntegerLimit** [comment]
I think the main problem is that the solution requires GroovyScript as a dep, but I'm unsure of how to make that check only happen if GroovyScript is installed, thus making it an optional dep, but I'll see what I can do tomorrow. Thank you for your quick responses.

**Comment by IntegerLimit** [comment]
Also, I forgot to mention, this is all for 1.12.2.

**Comment by McJty** [comment]
Oh, in that case you will have to make your own addition. I don't support 1.12.2 anymore

**Comment by IntegerLimit** [comment]
Oh, ok.
