### ISSUE TITLE
TOP compatibility with Advanced Compass

### ISSUE THREAD

**Issue by Gamerbolts** [McJty/TheOneProbe#612]
Hello. I am using the Fabric 1.19.2 version of your mod for my modpack. Trying to set up the GUIs and everything and TOP GUI over laps the Advanced Compass one. I tried the Y offset put it did not seem to be moving. I guess I could have it above the hotbar but I wanted to have it just below the advanced compass area. I used the Mod Menu config change to try an change it in game, do I need to change the config file outside of the game? or would a /reload for the configs work. Any help is appreciated. Thanks!

**Comment by McJty** [comment]
The Fabric 1.19.2 version? What? I'm not aware of such a version? I don't work on Fabric

**Comment by Gamerbolts** [comment]
Whoops I am sorry. I got mixed up. Please disregard
