### ISSUE TITLE
1.20 Text rendering issues

### ISSUE THREAD

**Issue by Buuz135** [McJty/TheOneProbe#617]
TOP Version: `theoneprobe-1.20.1-10.0.0.jar`

`RenderHelper.renderItemStack` renders the txt variable twice, one big and one small
`RenderHelper.renderText` that uses the component renders from right to left

![2023-06-28_12 59 05](https://github.com/McJtyMods/TheOneProbe/assets/3874674/246dab81-2b7a-4039-88a0-f76d9448b3ec)
![NVIDIA_Share_ESJZOTx7c4](https://github.com/McJtyMods/TheOneProbe/assets/3874674/4fc0dec4-a4df-4a17-866c-9e7960c72fe7)

**Comment by Gantros** [comment]
I am having this issue as well, where the percentage of a block breaking is outside the info box.

**Comment by McJty** [comment]
yes, I'm aware of these issues and will fix them soon. Thanks for reporting

**Comment by McJty** [comment]
Fixed
