### ISSUE TITLE
1.20.1 - Server Crash

### ISSUE THREAD

**Issue by AzureDoom** [McJty/TheOneProbe#627]
```
Mod File: /home/mch/multicraft/servers/server77146/mods/theoneprobe-1.20.1-10.0.1.jar
    Failure message: The One Probe (theoneprobe) has failed to load correctly
        java.lang.reflect.InvocationTargetException: null
    Mod Version: 1.20.1-10.0.1
    Mod Issue URL: http://github.com/McJtyMods/TheOneProbe/issues
    Exception message: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraft.client.resources.language.I18n
```
Modpack used: https://www.curseforge.com/minecraft/modpacks/mysticmodpackunleashed/files/4853270

**Comment by McJty** [comment]
I need to see the full log

**Comment by AzureDoom** [comment]
Hmm, it seems redoing the install here is allowing it to start normally now 🤷🏻 Just gonna blame this on Forge forging things 😆

**Comment by shBLOCK** [comment]
Having the same problem, the stacktrace points to [here](https://github.com/McJtyMods/TheOneProbe/blob/5975e2de08fbea200446f6dc30f3c0de77f14bdc/src/main/java/mcjty/theoneprobe/TheOneProbe.java#L92C9-L92C69), doesn't really make sense this would load the I18n class though. Using a customized [ATM9](https://www.curseforge.com/minecraft/modpacks/all-the-mods-9) pack, but I can confirm this happens with the original ATM9 as well. I didn't test with a clean server though.
[crash-2023-11-28_23.56.38-fml.txt](https://github.com/McJtyMods/TheOneProbe/files/13490348/crash-2023-11-28_23.56.38-fml.txt)

**Comment by McJty** [comment]
I have no clue what to do about this @shBLOCK . I looked at the code and that line shouldn't trigger any client code
