### ISSUE TITLE
1.16.5 ``Client Crash`` when ``disabling 3d Model rendering``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [McJty/TheOneProbe#630]
https://github.com/McJtyMods/TheOneProbe/issues/333#issuecomment-1868371813

**Comment by P3rf3ctXZer0** [comment]
This further enforces; we need a way to disable 3d rendering.

**Comment by McJty** [comment]
You didn't set the config correctly:

renderBlacklist = ["*"]

**Comment by McJty** [comment]
Please don't make a duplicate bug ticket
