### ISSUE TITLE
Server error 1.20.4

### ISSUE THREAD

**Issue by Edivad99** [McJty/TheOneProbe#639]
![Screenshot 2024-02-22 alle 11 04 39](https://github.com/McJtyMods/TheOneProbe/assets/25778604/7b4ddc9b-1722-4484-be9a-2258d1fecf7c)
As soon as I enter a server where the TOP is, it crashes.
I also tried to clone the repo and the problem is there.
https://pastebin.com/BNCjfFNA

**Comment by McJty** [comment]
Fixed
