### ISSUE TITLE
[1.20.4] Crashing world with TOP

### ISSUE THREAD

**Issue by yanny7** [McJty/TheOneProbe#641]
On 1.20.4 my world is crashing with error (while developing my own mod, removing TOP fixed crashing)
`[19:54:44] [Render thread/WARN] [minecraft/ClientCommonPacketListenerImpl]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/24 (ClientboundCustomPayloadPacket) was larger than I expected, found 22 bytes extra whilst reading packet 24`

Version of TOP: [1.20.4_neo-11.0.1-2](https://maven.k-4u.nl/mcjty/theoneprobe/theoneprobe/1.20.4_neo-11.0.1-2/)

**Comment by McJty** [comment]
11.0.2 fixes this but I didn't update the maven. I will do that soon
