### ISSUE TITLE
[1.02.5/1.20.6] sync error and client kick when lighting a nether portal

### ISSUE THREAD

**Issue by desht** [McJty/TheOneProbe#645]
Lighting a Nether portal in the usual way causes the player to be kicked with a sync error, triggered by TOP

Stacktrace here: https://gist.github.com/desht/d97031c4da6307cbeb66ea2654467507

Looks like you might need to be using a `ItemStack.OPTIONAL_STREAM_CODEC` rather than `ItemStack.STREAM_CODEC` there.

(Update: quite a big problem, since the player immediately gets kicked again when logging back in. Guessing it's because the nether portal block the player is looking at has no item drop?)

**Comment by McJty** [comment]
I'll check it out soon

**Comment by McJty** [comment]
Fixed
