### ISSUE TITLE
minecraft 1.21

### ISSUE THREAD

**Issue by pinchmedal5365** [McJty/TheOneProbe#648]
when I try to launch minecraft 1.21 with the one probe it wont work 
![Uploading Screenshot 2024-07-03 112410.png…]()
please fix

**Comment by McJty** [comment]
That screenshot isn't working. I can't access it

**Comment by EAhn19** [comment]
I'm having this issue too. Here's a picture and a recent crash log.
![Screenshot 2024-07-04 004019](https://github.com/McJtyMods/TheOneProbe/assets/174681608/4d639070-a4e4-44db-b7a4-01a9c26de194)
[crash-2024-07-04_00.37.04-fml.txt](https://github.com/user-attachments/files/16093878/crash-2024-07-04_00.37.04-fml.txt)

**Comment by McJty** [comment]
The One Probe uses NeoForge. You are using Forge. That will not work

**Comment by EAhn19** [comment]
I thought it was a neoforge file. This is the file that gets downloaded into a modpack for forge 1.21.
![Screenshot 2024-07-04 011401](https://github.com/McJtyMods/TheOneProbe/assets/174681608/0a9dbe62-0ce3-447d-aabf-ca6b674e1e62)
![Screenshot 2024-07-04 011420](https://github.com/McJtyMods/TheOneProbe/assets/174681608/340cd177-3b90-438a-ae20-4b77077435a1)

**Comment by McJty** [comment]
Yes, old versions were for Forge. I can't help it that CurseForge still shows that for newer versions that no longer support Forge

**Comment by EAhn19** [comment]
Oh, okay. Thank you.
