### ISSUE TITLE
`TankReference` crashes while encoding/decoding empty fluids

### ISSUE THREAD

**Issue by Matyrobbrt** [McJty/TheOneProbe#649]
In 1.21, `TankReference` uses `FluidStack.STREAM_CODEC` for fluid network operations, however that stream codec cannot accept empty fluid stacks. `OPTIONAL_STREAM_CODEC` should be used instead

**Comment by McJty** [comment]
I'll fix it soon

**Comment by McJty** [comment]
Will be fixed upcoming release

**Comment by Matyrobbrt** [comment]
The encoder still uses `STREAM_CODEC`

**Comment by McJty** [comment]
Ah oops. Will have to fix later

**Comment by McJty** [comment]
Should be fixed now. I hope :-)
Thanks for reporting
