### ISSUE TITLE
Not supporting the display of items related to ArchitectureCraftmod

### ISSUE THREAD

**Issue by VillagerGold** [McJty/TheOneProbe#653]
![image](https://github.com/user-attachments/assets/df6ab627-9d99-4e52-85e5-0658c1317b64)
如图所示，1.12.2版本的检测器mod不支持建筑师工艺重置版mod相关物品的显示，希望能够修复
As shown in the figure, TOPmod version 1.12.2 does not support the display of ArchitectureCraftmod related items. We hope to fix this issue
相关链接Related links：https://www.curseforge.com/minecraft/mc-mods/architecturecraft-tridev

**Comment by McJty** [comment]
That's not for TOP to fix. The other mod seems to be doing something wrong. Please report to them
