### ISSUE TITLE
Request: API-only artifacts published to Maven

### ISSUE THREAD

**Issue by squeek502** [McJty/TheOneProbe#66]
See [JEI for an example](https://github.com/mezz/JustEnoughItems/blob/1.10/build.gradle#L124-L135):

```
task apiJar(type: Jar) {
    from sourceSets.main.allSource
    from sourceSets.main.output
    include 'mezz/jei/api/**/*'
    classifier = 'api'
}

artifacts {
    archives apiJar
}
```

Would allow mods to add support for TOP without having to add TOP itself to the dev environment.

**Comment by McJty** [comment]
TOP already has a maven here:

http://ci.tterrag.com/job/TheOneProbe/

Just use that in your build.gradle and you will be fine. TOP (and the API) will be available automatically in your dev env

**Comment by squeek502** [comment]
You seem to have misunderstood--I don't want to include the full mod in the dev environment, I only want the API package. Again, see JEI for an example:

http://dvs1.progwml6.com/files/maven/mezz/jei/jei_1.10.2/3.7.12.239/jei_1.10.2-3.7.12.239-api.jar

It only includes the files in the mezz/jei/api directory, which allows you to successfully import and compile against the API, but will not add the mod itself to the environment.

I do the same thing for AppleCore: https://github.com/squeek502/AppleCore/wiki/Building-against-AppleCore

**Comment by McJty** [comment]
Why would you want that? That way you cannot test your API work?

**Comment by squeek502** [comment]
I could then add and remove TOP from the dev environment at will by including the TOP jar in the mods directory as normal.

**Comment by McJty** [comment]
What exactly is the problem with having TOP in the dev env all the time? I always have WAILA, TOP, JEI and a few other mods in all my dev envs constantly

**Comment by squeek502** [comment]
It's a personal preference, but I think it has a few benefits:
- Decreases the potential for conflicts/bugs/etc to not be found because they are covered up by the mod always being in the dev environment (for example, something that is intended to be optional not actually being optional)
- Reduces potential issues when setting up a new dev environment (or bumping dependencies, etc)
- Reduces loadtime of a fresh dev environment
- Increases flexibility of what mods you have included in your dev environment

Including the full mod is totally fine when making an addon, but that's not what I'm doing. I just want to add optional support and this use case is exactly why the API package exists.

**Comment by McJty** [comment]
I'm a noob on things related to maven but can you explain to me more how exactly to set this up so it actually publishes fine on the maven that I already have? And how would one then use this instead of the current way? i.e. what does one have to use in build.gradle to get only the api and not the full package?

**Comment by squeek502** [comment]
Sure, it should be pretty easy. I've never use the maven-publishing plugin, but from what I can tell, you'd just need to add `artifact apiJar` after [this line](https://github.com/McJty/TheOneProbe/blob/1.10/build.gradle#L98) and add this somewhere in build.gradle:

```
task apiJar(type: Jar) {
    from sourceSets.main.output
    include 'mcjty/theoneprobe/api/**'
    classifier = 'api'
}

artifacts {
    archives apiJar
}
```

The new API artifact could then be included in a dev environment by doing:

```
deobfCompile "mcjty.theoneprobe:TheOneProbe:1.10-1.1.4-35:api"
```

instead of 

```
deobfCompile "mcjty.theoneprobe:TheOneProbe:1.10-1.1.4-35"
```

EDIT: See also [how JEI suggests including JEI in a dev environment](https://github.com/mezz/JustEnoughItems#developing-addons)--API-only at compile time, and the mod at runtime.

**Comment by squeek502** [comment]
Thanks for doing this @McJty.
