### ISSUE TITLE
Add support for Baubles

### ISSUE THREAD

**Issue by Dilnu** [McJty/TheOneProbe#67]
It would be cool if you could put the one Probe into a baubles slot. I think it would be a lot more convenient. I've taken to carrying it in my off hand but then things that require an empty hand often don't work.

**Comment by McJty** [comment]
Yes that's a good idea. But you know you can also use a helmet with the one probe in it? The vanilla helmets are supported but also EnderIO does this

**Comment by Dilnu** [comment]
I know that but I'm a big Botania player and I'd prefer to wear Botania equipment. I'm considering asking Vazkii to add support like they did for the Helm of revealing Thaumcraft integration but as noted on the bug talking about an enchantment, asking every mod that adds armor to provide integration is hard to scale.

**Comment by maxhenkes** [comment]
@Dilnu https://mods.curse.com/mc-mods/minecraft/247111-top-addons TOP-Addons let's you craft the probe with any helmet, like the terrasteel one :)

**Comment by VT-14** [comment]
@iPencil That page says TOP-Addons only adds support for Blood Magic, Botania, and Forestry helmets (at this time).  It sounds like that won't help with the billion other modded armor sets.  Adding helmets case by case requires too much upkeep.

I personally think it would be great if The One Probe could be added to any helmet slot item.  I've seen IC2 do something similar with their Electric Jetpack on chestplate armor in JEI (who wouldn't want a jetpack on a sleeping bag?), but I haven't actually tried it.

Baubles is a great alternative as it is extremely common.  Ideally, there could be both options.

**Comment by maxhenkes** [comment]
@VT-14 

He especially mentioned Botania that's why I linked it. Baubles support is great and all, but not everyone has baubles installed. The way this works is by adding a simple NBT tag to a helmet, that way I can pretty much work with 99.999% of the helmets out there and isn't exactly hard to maintain. 

Ideally it would be a config option where you add helmet namespaces so the recipe is automatically added.

Baubles support is appreciated, but I currently don't have ANY free slots available for something as trivial as TOP with just Botania installed :P

**Comment by VT-14** [comment]
My suggestions are intended for the base mod.  It would be great if The One Probe could be applied to all helmet slot items, and/or if The One Probe had Baubles support.

Add-ons are great for adding extended support for mods.  It is completely unreasonable to ask for McJty to support Blood Magic's weird altar crafting in the HUD, as there are an unreasonably huge number of other things that would be asked for.  That kind of stuff is perfect for an add-on to add.

On the other hand, access to the base mod's features isn't something that should need an add-on.  In my opinion, I shouldn't need to install a 3rd mod to strap a probe to Mekanism's Osmium Helmet.  A generic 'works with all helmets' approach would be fantastic.  I'm pretty much asking for your 'works 99.999% of the time' solution to be put in the base mod.

As for Baubles; To me it seems like a good alternative in case a generic solution isn't possible or reasonable to implement.  It would still be nice in the off-hand chance that someone doesn't want to wear a helmet but still have TOP capabilities.

**Comment by McJty** [comment]
Implemented
