### ISSUE TITLE
needsProbe=2 breaks TOP crafted Helmets

### ISSUE THREAD

**Issue by maxhenkes** [McJty/TheOneProbe#70]
EDIT: totally forgot:
1.10.2, Forge 2017, TOP 1.10.1.1.6

I'm gonna assume this is a bug, because you are basically crafting the probe into a helmet, and that should count as "having a probe" right?

We're trying to stop people from just using TOP without items on my server and after setting needsProbe=2 the item still works fine:
http://i.imgur.com/yLwPZHV.png

but the helmet shows this:

http://i.imgur.com/GwGY99y.png

I'm reverting the config option for now, but would be great to get this fixed :)

**Comment by McJty** [comment]
Yes that looks like a bug. I'll check it out

**Comment by McJty** [comment]
Fixed next release
