### ISSUE TITLE
small visual bug with tank bar

### ISSUE THREAD

**Issue by DreiPixel** [McJty/TheOneProbe#73]
http://imgur.com/a/HqJZU
0/10 Literally unplayable

there is this line probably from the tank bar that doesnt get moved when setting TOP to top center. 

im using version 1.1.6 of TOP

i dunno if this is fixed in 1.2. it isnt in the changelog.

**Comment by DrManganese** [comment]
That's the tank gauge from TOP Addons, and that's fixed in the next release ^^.

**Comment by DreiPixel** [comment]
oh didn't knew that :V
