### ISSUE TITLE
[Suggestion] Always on option as a config (disabled by default)

### ISSUE THREAD

**Issue by jawsawn** [McJty/TheOneProbe#76]
TOP seems really great, so why can't it be the next waila or wawla? I suggest a config option to make it visible from the start like waila. Of course this config would be disabled by default. 
Sure there is TOP on an helmet but you can't use it on other armor than the vanilla. 

(also make the probe bauble-able for any slot of baubles)

**Comment by McJty** [comment]
That config option is already there. needsProbe=0

**Comment by CelestialPhoenix** [comment]
Can you add a note to the config explaining what this setting does, and what do settings 0, 1, 2, and 3 do?
Right now the config looks like this, and I would have missed it completely if it weren't for this issue and using ctrl-f to find it.
(my apologies if you've got this in a later version of Minecraft; I'm running 1.12-1.4.28)
```  
 # The maximum packet size to send an itemstack from client to server. Reduce this if you have issues with network lag caused by TOP [range: -1 ~ 32768, default: 20000]
    I:maxPacketToServer=20000
    I:needsProbe=3
```
