### ISSUE TITLE
[1.10.2-1.2.1] Crash when looking at DecoCraft2 decobench

### ISSUE THREAD

**Issue by RealGrep** [McJty/TheOneProbe#77]
Initially filed this with DecoCraft2, but was told it should be filed with TOP:

https://minecraft.curseforge.com/projects/decocraft2/issues/1579

In short, I made a decobench and the client crashed as I looked at it. I got this crash log:
https://gist.github.com/RealGrep/7dd896cea2864cc438d369c8068fcc2a

Forge 2116, DecoCraft2 2.3.4.

Thanks :)

**Comment by McJty** [comment]
Sorry but that's not a bug in TOP. getPickBlock() should _not_ crash in this situation

**Comment by RealGrep** [comment]
Thanks, that was my initial thought. I'll sling it back to them.
