### ISSUE TITLE
[1.10.2] [Possible Bug] Visual weirdness with rendering item frames in TOP

### ISSUE THREAD

**Issue by SnowShock35** [McJty/TheOneProbe#80]
Hello,

I believe I might have found a bug in The One Probe for Minecraft 1.10.2

### Important Information

- Minecraft 1.10.2
- Minecraft Forge 12.18.2.2122
- The One Probe 1.10-1.2.2
- **Other:**
  - TOP Addons 1.10.2-0.9.0

### Issue Description 

See bellow visual. Minecraft's item frame renders lower than it should within The One Probe HUD. 

### Issue Media

![Issue Media #1](http://ss.snowshock35.com/2016/11/1478561193-8b000c1d.png)

**Comment by josephcsible** [comment]
Still happens with the latest git version for 1.12 today. New screenshot since the old link is broken: 
![2017-12-28_14 36 25](https://user-images.githubusercontent.com/16061266/34421320-9cecdf8a-ebdc-11e7-9b2e-b8df0e4208b9.png)

**Comment by josephcsible** [comment]
Note that this happens with paintings too.

**Comment by josephcsible** [comment]
The next release will contain the fix.
