### ISSUE TITLE
tooltip is not visible without probe or helmet

### ISSUE THREAD

**Issue by Unleased** [McJty/TheOneProbe#83]
I have just created a server through MCProHosting using the Hermitcraft 1.10.2 pack. and when trying to enable TOP it is only visible with a proble or helmet. I am aware that there is a config setting to change this and I have  I:needsProbe=0 and saved it and restarted the server and still in the client I cannot see anything unless I am using a probe or wearing a helmet. 
Is there something stupid I am missing or is this a bug?

**Comment by McJty** [comment]
Did you set it to needsProbe=0 on both client and server?

**Comment by Unleased** [comment]
It's set to that in the config file for the server where is the client side one?

**Comment by McJty** [comment]
Well same config file ('theoneprobe.cfg') but then on the client

**Comment by Unleased** [comment]
Ah right. Yep I'm just stupid. 
Thanks :)
