### ISSUE TITLE
SSP CTD when tconstruct is present

### ISSUE THREAD

**Issue by xenoflot** [McJty/TheOneProbe#85]
Hi McJty,

http://pastebin.com/1cR4hksj

Upgraded to TOP 1.3.0 just now and the client crashed with the linked log when entering a fresh world.
Stripped all mods except TOP, mcjtylib, tconstruct and mantle and the problem remains.
Removed tconstruct and mantle and I'm in the world.

mcjtylib 2.2.0
tconstruct 2.5.6b
mantle 1.1.1

Cheers

**Comment by McJty** [comment]
Already fixed in 1.3.1
