### ISSUE TITLE
Crash on world load.

### ISSUE THREAD

**Issue by scalda** [McJty/TheOneProbe#86]
Hi i am just testing out latest version (theoneprobe-1.10-1.3.1.jar) and every time i load an existing world and a new world, i get this crash report generated [link](http://pastebin.com/VmdM2BYG)

This is in a dev version of hermitpack 1.4.0, it was the only mod i updated today

Any questions please ask

Regards

Scalda

Edit: i just saw that you had fixed this very crash in the 1.3.0 version and then released the version above but it still seems to be there unfortunately.

**Comment by McJty** [comment]
Your pastebin link is broken

**Comment by scalda** [comment]
There we go all fixed, i put in wrong sorry

**Comment by lordshade88** [comment]
[My Crash Report](http://pastebin.com/WKrHeKzb), same here on world load with the last 2 new "The One Probe". Aweasome mods by the way  : D

**Comment by SmallSansSerif** [comment]
Yes just got the same.. http://pastebin.com/bCAZabRz

**Comment by McJty** [comment]
Fixed in 1.3.2. And I tested this time

**Comment by scalda** [comment]
Thanks McJty
