### ISSUE TITLE
(Suggestion) Add a config option to disable giving read me at start

### ISSUE THREAD

**Issue by jawsawn** [McJty/TheOneProbe#87]
Or is there an already existing option?

**Comment by McJty** [comment]
Why do you need that?

**Comment by jawsawn** [comment]
I want a cleaner starting inventory. For a map.

**Comment by bbgott** [comment]
I have to agree with JAWSAWN, I prefer to be able to start without forced mod items in my inventory when building a pack.  Please make it an option to disable the read me at start.

**Comment by McJty** [comment]
Implemented next release (new 'spawnNote' config option)
