### ISSUE TITLE
Nothing displayed for crops

### ISSUE THREAD

**Issue by rckymtnrfc** [McJty/TheOneProbe#9]
Using theoneprobe-1.9.4-1.0.4 & mcjtylib-1.9.4-1.8.7 along with Forge 1941, I'm not seeing anything displayed when looking at crops.

**Comment by McJty** [comment]
Hmm. I'll investigate that later. You sure you didn't disable it? Also are you sneaking or not?

**Comment by rckymtnrfc** [comment]
I wanted to test it without other mods, so I just created a fresh instance, didn't edit the configs.  Also not sneaking.

To clarify, I'm not seeing the border/box, block name, or crop percentage for crops. It's completely gone. Other blocks seem to be working fine.

**Comment by McJty** [comment]
What crops are you using it on? Can you show a screenshot?

**Comment by McJty** [comment]
Also any messages in the log?

**Comment by rckymtnrfc** [comment]
It seemed to be all crops.  At least wheat and beats I remember looking at.  In the new instance I was just using wheat.

Here are the screenshots - http://imgur.com/a/PXVBa

It does look like there is an error in the logs - http://pastebin.com/t5DFdWk1

**Comment by rckymtnrfc** [comment]
Also, please don't ask me why I made a 3x3 crop area to test when I could have just made a single one.  =)

**Comment by McJty** [comment]
Ok I see the problem. Not sure how to solve it yet though

**Comment by McJty** [comment]
Found it. Will be fixed next release.
