### ISSUE TITLE
[Suggestion] Make TOP a non-stackable item

### ISSUE THREAD

**Issue by zmbush** [McJty/TheOneProbe#93]
The [spectre anchor](https://randomthingsminecraftmod.wikispaces.com/Spectre+Anchor) from random things allows an effect similar to soulbind, but only works on non-stackable items.

It'd be great to be able to anchor the probe especially when it's in the bauble slot.

**Comment by McJty** [comment]
Yes, I always forget to fix that. Will do that for next release
