### ISSUE TITLE
Client Crash - looking at a newly formed forestry papaya

### ISSUE THREAD

**Issue by ProsperCraft** [McJty/TheOneProbe#94]
https://gist.github.com/ProsperCraft/83e5059de2a2e2e4ff47f580dbfd5ebd

reproduced here - 
https://gist.github.com/ProsperCraft/a33d37c070ee6c240b8c1825329ba646

You can look at a fully formed Papaya on a Forestry papaya tree, but if you look at one right after the tree sprouts and is forming, it crashes the client.

**Comment by McJty** [comment]
@mezz, looks like a problem on your side?

**Comment by mezz** [comment]
Yes, this looks like a Forestry issue. I can fix it soon.

**Comment by mezz** [comment]
Fixed here: https://github.com/ForestryMC/ForestryMC/commit/098b739dcaeac2b5809eed7680d6bbb4f06c4feb
