### ISSUE TITLE
Show mod names on item tooltips

### ISSUE THREAD

**Issue by Gaelan** [McJty/TheOneProbe#97]
Could we have mod names in inventory item tooltips in TOP? I'm building a WAILA-less pack but want that feature. Something like this: 
![7mces57](https://cloud.githubusercontent.com/assets/4495750/20506487/5e76a70a-b009-11e6-8802-8d98c7389e4e.png)
(screenshot is from Vazkii's LiMI, which does exactly this but was not updated past 1.7)

**Comment by McJty** [comment]
Not in TOP but there is another mod from @mezz that does this. Forgot the name but you can find it out if you check his projects. It is included in FTB Hermitcraft for example

**Comment by mezz** [comment]
https://minecraft.curseforge.com/projects/mod-name-tooltip
